/* 饭泰 FANTHA - 词汇数据 */
window.APP_DATA = window.APP_DATA || {};
window.APP_DATA.VOCAB = [
  { id: 'vocab-bl-001', cat: 'bl', word: 'คู่', roman: 'khu', zhuyin: '库', meaning: '对/CP', pos: 'n.', ex_thai: 'คู่นี้ล็อคแล้ว', ex_cn: '这对锁死了', freq: 18 },
  { id: 'vocab-bl-002', cat: 'bl', word: 'นี้', roman: 'ni', zhuyin: '尼', meaning: '这', pos: '', ex_thai: 'คู่นี้ล็อคแล้ว', ex_cn: '这对锁死了', freq: 18 },
  { id: 'vocab-bl-003', cat: 'bl', word: 'ดู', roman: 'du', zhuyin: '嘟', meaning: '看', pos: 'v.', ex_thai: 'ดูแล้วยิ้มตลอด', ex_cn: '看了全程傻笑', freq: 7 },
  { id: 'vocab-bl-004', cat: 'bl', word: 'อยาก', roman: 'yak', zhuyin: '亚', meaning: '想/要', pos: 'v.', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE结局', freq: 7 },
  { id: 'vocab-bl-005', cat: 'bl', word: 'ฟีด', roman: 'fit', zhuyin: '费', meaning: '营业/发糖', pos: 'n.', ex_thai: 'คู่นี้ฟีดจริงๆ', ex_cn: '这对真的在营业', freq: 6 },
  { id: 'vocab-bl-006', cat: 'bl', word: 'ดีมาก', roman: 'di mak', zhuyin: '迪玛', meaning: '很好', pos: 'adj.', ex_thai: 'เคมีดีมาก', ex_cn: '化学反应好强', freq: 5 },
  { id: 'vocab-bl-007', cat: 'bl', word: 'ตลอด', roman: 'talot', zhuyin: '达洛', meaning: '一直/始终', pos: 'adv.', ex_thai: 'ดูแล้วยิ้มตลอด', ex_cn: '看了全程傻笑', freq: 5 },
  { id: 'vocab-bl-008', cat: 'bl', word: 'ฉาก', roman: 'chak', zhuyin: '查', meaning: '场景/场次', pos: 'n.', ex_thai: 'ฉากนี้เด็ดสุด', ex_cn: '这场戏绝了', freq: 5 },
  { id: 'vocab-bl-009', cat: 'bl', word: 'น่ารัก', roman: 'na rak', zhuyin: '那拉克', meaning: '可爱', pos: 'adj.', ex_thai: 'พวกเขาน่ารักมาก', ex_cn: '他们好可爱', freq: 4 },
  { id: 'vocab-bl-010', cat: 'bl', word: 'หวาน', roman: 'wan', zhuyin: '弯', meaning: '甜', pos: 'adj.', ex_thai: 'หวานจัง ตายหรือเปล่า', ex_cn: '甜死了要', freq: 4 },
  { id: 'vocab-bl-011', cat: 'bl', word: 'ไหว', roman: 'wai', zhuyin: '歪', meaning: '撑得住', pos: 'adj.', ex_thai: 'ไม่ไหวแล้ว หวานเกิน', ex_cn: '不行了太甜了', freq: 4 },
  { id: 'vocab-bl-012', cat: 'bl', word: 'จบ', roman: 'chop', zhuyin: '绰不', meaning: '结束', pos: 'v.', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE结局', freq: 4 },
  { id: 'vocab-bl-013', cat: 'bl', word: 'ได้', roman: 'dai', zhuyin: '代', meaning: '可以', pos: '', ex_thai: 'มีเคมีแบบนี้ไม่คบกันได้ไง', ex_cn: '这化学反应不在一起行吗', freq: 4 },
  { id: 'vocab-bl-014', cat: 'bl', word: 'ร้องไห้', roman: 'rong hai', zhuyin: '隆海', meaning: '哭', pos: 'v.', ex_thai: 'ร้องไห้ตลอดตอน', ex_cn: '全程在哭', freq: 4 },
  { id: 'vocab-bl-015', cat: 'bl', word: 'จน', roman: 'chon', zhuyin: '巾', meaning: '直到', pos: '', ex_thai: 'เจ็บจนหายใจไม่ออก', ex_cn: '虐到喘不过气', freq: 4 },
  { id: 'vocab-bl-016', cat: 'bl', word: 'จัง', roman: 'chang', zhuyin: '章', meaning: '好/真', pos: 'adv.', ex_thai: 'หวานจัง ตายหรือเปล่า', ex_cn: '甜死了要', freq: 3 },
  { id: 'vocab-bl-017', cat: 'bl', word: 'เคมี', roman: 'khemri', zhuyin: '肯里', meaning: '化学反应', pos: '', ex_thai: 'เคมีดีมาก', ex_cn: '化学反应好强', freq: 3 },
  { id: 'vocab-bl-018', cat: 'bl', word: 'ยิ้ม', roman: 'yim', zhuyin: '伊', meaning: '笑', pos: '', ex_thai: 'ดูแล้วยิ้มตลอด', ex_cn: '看了全程傻笑', freq: 3 },
  { id: 'vocab-bl-019', cat: 'bl', word: 'หัวใจ', roman: 'hua chai', zhuyin: '华柴', meaning: '心', pos: '', ex_thai: 'หัวใจละลาย', ex_cn: '心都化了', freq: 3 },
  { id: 'vocab-bl-020', cat: 'bl', word: 'ความรัก', roman: 'khwam rak', zhuyin: '康拉克', meaning: '爱情', pos: 'n.', ex_thai: 'ตาของเขามีแต่ความรัก', ex_cn: '他眼里全是爱', freq: 3 },
  { id: 'vocab-bl-021', cat: 'bl', word: 'ดูแล', roman: 'du lae', zhuyin: '嘟莱', meaning: '照顾', pos: 'v.', ex_thai: 'เขาดูแลกันดีมาก', ex_cn: '他们互相照顾得很好', freq: 3 },
  { id: 'vocab-bl-022', cat: 'bl', word: 'แบบนี้', roman: 'baep ni', zhuyin: '拜尼', meaning: '这样', pos: '', ex_thai: 'มีเคมีแบบนี้ไม่คบกันได้ไง', ex_cn: '这化学反应不在一起行吗', freq: 3 },
  { id: 'vocab-bl-023', cat: 'bl', word: 'สุด', roman: 'sut', zhuyin: '素', meaning: '最', pos: 'adv.', ex_thai: 'ฉากนี้เด็ดสุด', ex_cn: '这场戏绝了', freq: 3 },
  { id: 'vocab-bl-024', cat: 'bl', word: 'เจ็บ', roman: 'chep', zhuyin: '切', meaning: '疼/痛', pos: '', ex_thai: 'ตอนนี้เจ็บมาก', ex_cn: '这集好虐', freq: 3 },
  { id: 'vocab-bl-025', cat: 'bl', word: 'คนรัก', roman: 'khon rak', zhuyin: '坤拉克', meaning: '恋人', pos: 'n.', ex_thai: 'หวงแหนคนรักมาก', ex_cn: '占有欲很强', freq: 3 },
  { id: 'vocab-bl-026', cat: 'bl', word: 'เลิก', roman: 'loek', zhuyin: '律', meaning: '结束/解除', pos: '', ex_thai: 'เลิกคู่กันแล้ว', ex_cn: '解绑了', freq: 3 },
  { id: 'vocab-bl-027', cat: 'bl', word: 'จิ้ง', roman: 'ching', zhuyin: '精', meaning: '嗑(CP)', pos: '', ex_thai: 'คู่จิ้งคู่นี้ดีสุด', ex_cn: '这对CP最好磕', freq: 3 },
  { id: 'vocab-bl-028', cat: 'bl', word: 'เบื้องหลัง', roman: 'bueng lang', zhuyin: '本朗', meaning: '幕后', pos: '', ex_thai: 'เบื้องหลังน่ารักมาก', ex_cn: '幕后好可爱', freq: 3 },
  { id: 'vocab-bl-029', cat: 'bl', word: 'ละลาย', roman: 'lalai', zhuyin: '拉莱', meaning: '融化', pos: '', ex_thai: 'หัวใจละลาย', ex_cn: '心都化了', freq: 2 },
  { id: 'vocab-bl-030', cat: 'bl', word: 'ใจสั่น', roman: 'chai san', zhuyin: '柴桑', meaning: '心动', pos: '', ex_thai: 'มองกันแล้วใจสั่น', ex_cn: '对视一眼就心动', freq: 2 },
  { id: 'vocab-bl-031', cat: 'bl', word: 'คบ', roman: 'khop', zhuyin: '阔不', meaning: '交往', pos: '', ex_thai: 'ขอให้คบกันจริงๆ นะ', ex_cn: '希望他们真的在一起', freq: 2 },
  { id: 'vocab-bl-032', cat: 'bl', word: 'เห็น', roman: 'hen', zhuyin: '恨', meaning: '看见', pos: 'v.', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE结局', freq: 2 },
  { id: 'vocab-bl-033', cat: 'bl', word: 'HE', roman: 'H E', zhuyin: 'H E', meaning: 'Happy Ending', pos: '', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE结局', freq: 2 },
  { id: 'vocab-bl-034', cat: 'bl', word: 'ฟินจน', roman: 'fin chon', zhuyin: '芬巾', meaning: '爽到', pos: '', ex_thai: 'ฟินจนไม่ไหว', ex_cn: '上头到不行', freq: 2 },
  { id: 'vocab-bl-035', cat: 'bl', word: 'ไง', roman: 'ngai', zhuyin: '恩盖', meaning: '怎样(口语)', pos: '', ex_thai: 'มีเคมีแบบนี้ไม่คบกันได้ไง', ex_cn: '这化学反应不在一起行吗', freq: 2 },
  { id: 'vocab-bl-036', cat: 'bl', word: 'ตอนที่', roman: 'ton thi', zhuyin: '盾提', meaning: '第...集', pos: '', ex_thai: 'ตอนที่เท่าไหร่แล้ว', ex_cn: '更新到第几集了', freq: 2 },
  { id: 'vocab-bl-037', cat: 'bl', word: 'ซัน', roman: 'san', zhuyin: '三', meaning: '太阳', pos: '', ex_thai: 'ซีซัน 2 มีไหม', ex_cn: '有第二季吗', freq: 2 },
  { id: 'vocab-bl-038', cat: 'bl', word: 'ฟิน', roman: 'fin', zhuyin: '芬', meaning: '爽/心动', pos: '', ex_thai: 'ฉากสุดท้ายฟินสุด', ex_cn: '最后一场太爽了', freq: 2 },
  { id: 'vocab-bl-039', cat: 'bl', word: 'บท', roman: 'bot', zhuyin: '波', meaning: '集/篇章', pos: '', ex_thai: 'บทนี้เขียนดีมาก', ex_cn: '这集剧本写得好', freq: 2 },
  { id: 'vocab-bl-040', cat: 'bl', word: 'เขียน', roman: 'khian', zhuyin: '基安', meaning: '写', pos: 'v.', ex_thai: 'บทนี้เขียนดีมาก', ex_cn: '这集剧本写得好', freq: 2 },
  { id: 'vocab-bl-041', cat: 'bl', word: 'รอ', roman: 'ro', zhuyin: '罗', meaning: '等', pos: 'v.', ex_thai: 'กำลังรอตอนใหม่', ex_cn: '在等更新', freq: 2 },
  { id: 'vocab-bl-042', cat: 'bl', word: 'เยอะ', roman: 'yoe', zhuyin: '哟', meaning: '多', pos: '', ex_thai: 'คาดหวังเยอะมาก', ex_cn: '期待值拉满', freq: 2 },
  { id: 'vocab-bl-043', cat: 'bl', word: 'ชอบ', roman: 'chop', zhuyin: '绰不', meaning: '喜欢', pos: 'v.', ex_thai: 'ชอบตอนที่เขาสารภาพรัก', ex_cn: '喜欢表白那场戏', freq: 2 },
  { id: 'vocab-bl-044', cat: 'bl', word: 'รัก', roman: 'rak', zhuyin: '拉克', meaning: '爱', pos: 'v.', ex_thai: 'ชอบตอนที่เขาสารภาพรัก', ex_cn: '喜欢表白那场戏', freq: 2 },
  { id: 'vocab-bl-045', cat: 'bl', word: 'ว่า', roman: 'wa', zhuyin: '瓦', meaning: '说/称', pos: '', ex_thai: 'คาดไม่ถึงว่าจะจบแบบนี้', ex_cn: '没想到会这样结局', freq: 2 },
  { id: 'vocab-bl-046', cat: 'bl', word: 'รอบ', roman: 'rop', zhuyin: '罗', meaning: '轮次/场', pos: '', ex_thai: 'ฉากนี้ดูกี่รอบก็ไม่เบื่อ', ex_cn: '这场戏看几遍都不腻', freq: 2 },
  { id: 'vocab-bl-047', cat: 'bl', word: 'ดี', roman: 'di', zhuyin: '迪', meaning: '好', pos: '', ex_thai: 'ความเร็วเรื่องดีพอดี', ex_cn: '节奏刚好', freq: 2 },
  { id: 'vocab-bl-048', cat: 'bl', word: 'บอ', roman: 'bo', zhuyin: '波', meaning: '宝(名)', pos: '', ex_thai: 'เขาเป็นท็อปหรือบอท', ex_cn: '他是攻还是受', freq: 2 },
  { id: 'vocab-bl-049', cat: 'bl', word: 'เย็นชา', roman: 'yen cha', zhuyin: '燕查', meaning: '冷淡', pos: '', ex_thai: 'นิสัยเย็นชาแต่ใจดี', ex_cn: '外冷内热型', freq: 2 },
  { id: 'vocab-bl-050', cat: 'bl', word: 'แกล้ง', roman: 'klaeng', zhuyin: '格朗', meaning: '故意', pos: '', ex_thai: 'ขี้เล่นชอบแกล้ง', ex_cn: '调皮爱逗人型', freq: 2 },
  { id: 'vocab-gl-051', cat: 'gl', word: 'ดู', roman: 'du', zhuyin: '嘟', meaning: '看', pos: 'v.', ex_thai: 'ยังไม่ได้ดู อย่าสปอยล์', ex_cn: '还没看别剧透', freq: 13 },
  { id: 'vocab-gl-052', cat: 'gl', word: 'นี้', roman: 'ni', zhuyin: '尼', meaning: '这', pos: '', ex_thai: 'คู่นี้หวานจัง', ex_cn: '这对好甜', freq: 11 },
  { id: 'vocab-gl-053', cat: 'gl', word: 'เธอ', roman: 'thoe', zhuyin: '特', meaning: '你(女)/她', pos: '', ex_thai: 'ตาของเธอมีแต่ความรัก', ex_cn: '她眼里全是爱', freq: 8 },
  { id: 'vocab-gl-054', cat: 'gl', word: 'ความรัก', roman: 'khwam rak', zhuyin: '康拉克', meaning: '爱情', pos: 'n.', ex_thai: 'ตาของเธอมีแต่ความรัก', ex_cn: '她眼里全是爱', freq: 8 },
  { id: 'vocab-gl-055', cat: 'gl', word: 'อยาก', roman: 'yak', zhuyin: '亚', meaning: '想/要', pos: 'v.', ex_thai: 'อยากให้คบกันจริงๆ', ex_cn: '好想她们真在一起', freq: 6 },
  { id: 'vocab-gl-056', cat: 'gl', word: 'ดีมาก', roman: 'di mak', zhuyin: '迪玛', meaning: '很好', pos: 'adj.', ex_thai: 'เคมีดีมาก', ex_cn: '化学反应好强', freq: 6 },
  { id: 'vocab-gl-057', cat: 'gl', word: 'จบ', roman: 'chop', zhuyin: '绰不', meaning: '结束', pos: 'v.', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE', freq: 6 },
  { id: 'vocab-gl-058', cat: 'gl', word: 'คู่', roman: 'khu', zhuyin: '库', meaning: '对/CP', pos: 'n.', ex_thai: 'คู่นี้หวานจัง', ex_cn: '这对好甜', freq: 5 },
  { id: 'vocab-gl-059', cat: 'gl', word: 'จัง', roman: 'chang', zhuyin: '章', meaning: '好/真', pos: 'adv.', ex_thai: 'คู่นี้หวานจัง', ex_cn: '这对好甜', freq: 5 },
  { id: 'vocab-gl-060', cat: 'gl', word: 'น่ารัก', roman: 'na rak', zhuyin: '那拉克', meaning: '可爱', pos: 'adj.', ex_thai: 'น้องสาวน่ารักมาก', ex_cn: '妹妹好可爱', freq: 5 },
  { id: 'vocab-gl-061', cat: 'gl', word: 'เรื่อง', roman: 'rueang', zhuyin: '软', meaning: '部/故事', pos: 'n.', ex_thai: 'ความเร็วเรื่องดีพอดี', ex_cn: '节奏刚好', freq: 5 },
  { id: 'vocab-gl-062', cat: 'gl', word: 'สวย', roman: 'suai', zhuyin: '随', meaning: '漂亮', pos: 'adj.', ex_thai: 'ผู้หญิงรักกันสวยจัง', ex_cn: '女生相爱好美', freq: 4 },
  { id: 'vocab-gl-063', cat: 'gl', word: 'ดูแล', roman: 'du lae', zhuyin: '嘟莱', meaning: '照顾', pos: 'v.', ex_thai: 'ดูแลกันอบอุ่นมาก', ex_cn: '互相照顾好温暖', freq: 4 },
  { id: 'vocab-gl-064', cat: 'gl', word: 'คนอื่น', roman: 'khon uen', zhuyin: '坤温', meaning: '别人', pos: 'n.', ex_thai: 'ไม่ต้องสนใจสายตาคนอื่น', ex_cn: '不用在意别人眼光', freq: 4 },
  { id: 'vocab-gl-065', cat: 'gl', word: 'คนรัก', roman: 'khon rak', zhuyin: '坤拉克', meaning: '恋人', pos: 'n.', ex_thai: 'หวงแหนคนรัก', ex_cn: '占有欲强', freq: 4 },
  { id: 'vocab-gl-066', cat: 'gl', word: 'พี่สาว', roman: 'phi sao', zhuyin: '屁嫂', meaning: '姐姐', pos: '', ex_thai: 'พี่สาวเท่มาก', ex_cn: '姐姐好飒', freq: 3 },
  { id: 'vocab-gl-067', cat: 'gl', word: 'หวาน', roman: 'wan', zhuyin: '弯', meaning: '甜', pos: 'adj.', ex_thai: 'คู่นี้หวานจัง', ex_cn: '这对好甜', freq: 3 },
  { id: 'vocab-gl-068', cat: 'gl', word: 'น้องสาว', roman: 'nong sao', zhuyin: '弄嫂', meaning: '妹妹', pos: '', ex_thai: 'น้องสาวน่ารักมาก', ex_cn: '妹妹好可爱', freq: 3 },
  { id: 'vocab-gl-069', cat: 'gl', word: 'ผู้หญิง', roman: 'phu ying', zhuyin: '普英', meaning: '女人', pos: '', ex_thai: 'ผู้หญิงรักกันสวยจัง', ex_cn: '女生相爱好美', freq: 3 },
  { id: 'vocab-gl-070', cat: 'gl', word: 'รัก', roman: 'rak', zhuyin: '拉克', meaning: '爱', pos: 'v.', ex_thai: 'ผู้หญิงรักกันสวยจัง', ex_cn: '女生相爱好美', freq: 3 },
  { id: 'vocab-gl-071', cat: 'gl', word: 'ซี', roman: 'si', zhuyin: '西', meaning: '系列/季', pos: '', ex_thai: 'ขอให้มีซีซัน 2', ex_cn: '希望能有第二季', freq: 3 },
  { id: 'vocab-gl-072', cat: 'gl', word: 'ซัน', roman: 'san', zhuyin: '三', meaning: '太阳', pos: '', ex_thai: 'ขอให้มีซีซัน 2', ex_cn: '希望能有第二季', freq: 3 },
  { id: 'vocab-gl-073', cat: 'gl', word: 'อบอุ่น', roman: 'op un', zhuyin: '奥温', meaning: '温暖', pos: '', ex_thai: 'ดูแลกันอบอุ่นมาก', ex_cn: '互相照顾好温暖', freq: 3 },
  { id: 'vocab-gl-074', cat: 'gl', word: 'แบบ', roman: 'baep', zhuyin: '别不', meaning: '方式/像', pos: '', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE', freq: 3 },
  { id: 'vocab-gl-075', cat: 'gl', word: 'ใหม่', roman: 'mai', zhuyin: '迈', meaning: '新', pos: 'adj.', ex_thai: 'ตอนใหม่ออกยัง', ex_cn: '更新了吗', freq: 3 },
  { id: 'vocab-gl-076', cat: 'gl', word: 'เจ็บ', roman: 'chep', zhuyin: '切', meaning: '疼/痛', pos: '', ex_thai: 'ตอนนี้เจ็บมาก', ex_cn: '这集好虐', freq: 3 },
  { id: 'vocab-gl-077', cat: 'gl', word: 'ร้องไห้', roman: 'rong hai', zhuyin: '隆海', meaning: '哭', pos: 'v.', ex_thai: 'ร้องไห้ตลอด', ex_cn: '全程在哭', freq: 3 },
  { id: 'vocab-gl-078', cat: 'gl', word: 'ตลอด', roman: 'talot', zhuyin: '达洛', meaning: '一直/始终', pos: 'adv.', ex_thai: 'ร้องไห้ตลอด', ex_cn: '全程在哭', freq: 3 },
  { id: 'vocab-gl-079', cat: 'gl', word: 'บท', roman: 'bot', zhuyin: '波', meaning: '集/篇章', pos: '', ex_thai: 'บทเขียนดีมาก', ex_cn: '剧本写得好', freq: 3 },
  { id: 'vocab-gl-080', cat: 'gl', word: 'เขียน', roman: 'khian', zhuyin: '基安', meaning: '写', pos: 'v.', ex_thai: 'บทเขียนดีมาก', ex_cn: '剧本写得好', freq: 3 },
  { id: 'vocab-gl-081', cat: 'gl', word: 'ข้างใน', roman: 'khang nai', zhuyin: '康乃', meaning: '里面', pos: '', ex_thai: 'เธอสวยทั้งข้างนอกและข้างใน', ex_cn: '她内外皆美', freq: 3 },
  { id: 'vocab-gl-082', cat: 'gl', word: 'จน', roman: 'chon', zhuyin: '巾', meaning: '直到', pos: '', ex_thai: 'เจ็บจนหายใจไม่ออก', ex_cn: '虐到喘不过气', freq: 3 },
  { id: 'vocab-gl-083', cat: 'gl', word: 'เท่', roman: 'the', zhuyin: '贴', meaning: '酷/飒', pos: 'adj.', ex_thai: 'พี่สาวเท่มาก', ex_cn: '姐姐好飒', freq: 2 },
  { id: 'vocab-gl-084', cat: 'gl', word: 'สุด', roman: 'sut', zhuyin: '素', meaning: '最', pos: 'adv.', ex_thai: 'คู่นี้ฟินสุด', ex_cn: '这对太上头了', freq: 2 },
  { id: 'vocab-gl-085', cat: 'gl', word: 'ใจสั่น', roman: 'chai san', zhuyin: '柴桑', meaning: '心动', pos: '', ex_thai: 'มองกันแล้วใจสั่น', ex_cn: '对视就心动', freq: 2 },
  { id: 'vocab-gl-086', cat: 'gl', word: 'หัวใจ', roman: 'hua chai', zhuyin: '华柴', meaning: '心', pos: '', ex_thai: 'หัวใจละลาย', ex_cn: '心都化了', freq: 2 },
  { id: 'vocab-gl-087', cat: 'gl', word: 'ละลาย', roman: 'lalai', zhuyin: '拉莱', meaning: '融化', pos: '', ex_thai: 'หัวใจละลาย', ex_cn: '心都化了', freq: 2 },
  { id: 'vocab-gl-088', cat: 'gl', word: 'ไหว', roman: 'wai', zhuyin: '歪', meaning: '撑得住', pos: 'adj.', ex_thai: 'ไม่ไหว หวานเกิน', ex_cn: '不行了太甜了', freq: 2 },
  { id: 'vocab-gl-089', cat: 'gl', word: 'HE', roman: 'H E', zhuyin: 'H E', meaning: 'Happy Ending', pos: '', ex_thai: 'อยากเห็นคู่นี้จบแบบ HE', ex_cn: '想看这对HE', freq: 2 },
  { id: 'vocab-gl-090', cat: 'gl', word: 'น้อง', roman: 'nong', zhuyin: '弄', meaning: '弟弟/妹妹', pos: 'n.', ex_thai: 'พี่สาวดูแลน้องดีมาก', ex_cn: '姐姐照顾妹妹好细心', freq: 2 },
  { id: 'vocab-gl-091', cat: 'gl', word: 'ความสัมพันธ์', roman: 'khwam sam phan', zhuyin: '宽桑潘', meaning: '关系', pos: '', ex_thai: 'ความสัมพันธ์นี้สวยมาก', ex_cn: '这段关系好美', freq: 2 },
  { id: 'vocab-gl-092', cat: 'gl', word: 'วัน', roman: 'wan', zhuyin: '弯', meaning: '天/日', pos: 'n.', ex_thai: 'ออกอากาศวันไหน', ex_cn: '哪天播出', freq: 2 },
  { id: 'vocab-gl-093', cat: 'gl', word: 'ได้', roman: 'dai', zhuyin: '代', meaning: '可以', pos: '', ex_thai: 'ยังไม่ได้ดู อย่าสปอยล์', ex_cn: '还没看别剧透', freq: 2 },
  { id: 'vocab-gl-094', cat: 'gl', word: 'เด็ด', roman: 'det', zhuyin: '代', meaning: '绝/棒', pos: '', ex_thai: 'ฉากนี้เด็ดสุด', ex_cn: '这场戏绝了', freq: 2 },
  { id: 'vocab-gl-095', cat: 'gl', word: 'แบบนี้', roman: 'baep ni', zhuyin: '拜尼', meaning: '这样', pos: '', ex_thai: 'จบแบบนี้คือ HE หรือ BE', ex_cn: '结局是HE还是BE', freq: 2 },
  { id: 'vocab-gl-096', cat: 'gl', word: 'ดี', roman: 'di', zhuyin: '迪', meaning: '好', pos: '', ex_thai: 'ความเร็วเรื่องดีพอดี', ex_cn: '节奏刚好', freq: 2 },
  { id: 'vocab-gl-097', cat: 'gl', word: 'รอ', roman: 'ro', zhuyin: '罗', meaning: '等', pos: 'v.', ex_thai: 'รอตอนใหม่ทุกสัปดาห์', ex_cn: '每周等更新', freq: 2 },
  { id: 'vocab-gl-098', cat: 'gl', word: 'ชอบ', roman: 'chop', zhuyin: '绰不', meaning: '喜欢', pos: 'v.', ex_thai: 'ชอบตอนที่สารภาพรัก', ex_cn: '喜欢表白那场戏', freq: 2 },
  { id: 'vocab-gl-099', cat: 'gl', word: 'รอบ', roman: 'rop', zhuyin: '罗', meaning: '轮次/场', pos: '', ex_thai: 'ดูกี่รอบก็ไม่เบื่อ', ex_cn: '看几遍都不腻', freq: 2 },
  { id: 'vocab-gl-100', cat: 'gl', word: 'เบื่อ', roman: 'buea', zhuyin: '别雅', meaning: '无聊/厌烦', pos: '', ex_thai: 'ดูกี่รอบก็ไม่เบื่อ', ex_cn: '看几遍都不腻', freq: 2 },
  { id: 'vocab-star-101', cat: 'star', word: 'เธอ', roman: 'thoe', zhuyin: '特', meaning: '你(女)/她', pos: '', ex_thai: 'เธอคือแสงของฉัน', ex_cn: '你是我的光', freq: 18 },
  { id: 'vocab-star-102', cat: 'star', word: 'ได้', roman: 'dai', zhuyin: '代', meaning: '可以', pos: '', ex_thai: 'เธอไม่ได้สู้คนเดียว', ex_cn: '你不是一个人在战斗', freq: 13 },
  { id: 'vocab-star-103', cat: 'star', word: 'เซ็น', roman: 'sen', zhuyin: '森', meaning: '签名', pos: 'v.', ex_thai: 'ขอเซ็นให้หน่อย', ex_cn: '可以签个名吗', freq: 12 },
  { id: 'vocab-star-104', cat: 'star', word: 'ขอ', roman: 'kho', zhuyin: '阔', meaning: '要/请求', pos: 'v.', ex_thai: 'ขอถ่ายรูปหน่อยได้ไหม', ex_cn: '可以拍个照吗', freq: 10 },
  { id: 'vocab-star-105', cat: 'star', word: 'พี่', roman: 'phi', zhuyin: '屁', meaning: '哥哥/姐姐', pos: 'n.', ex_thai: 'พี่คือ number one', ex_cn: '哥哥是第一名', freq: 7 },
  { id: 'vocab-star-106', cat: 'star', word: 'ขอบคุณ', roman: 'khop khun', zhuyin: '阔不坤', meaning: '谢谢', pos: 'phrase', ex_thai: 'ขอบคุณที่เกิดมา', ex_cn: '感谢你的存在', freq: 6 },
  { id: 'vocab-star-107', cat: 'star', word: 'ดี', roman: 'di', zhuyin: '迪', meaning: '好', pos: '', ex_thai: 'เขียนชื่ออะไรดี', ex_cn: '写什么名字好', freq: 5 },
  { id: 'vocab-star-108', cat: 'star', word: 'ที่สุด', roman: 'thi sut', zhuyin: '提素', meaning: '最', pos: 'adv.', ex_thai: 'น่ารักที่สุด', ex_cn: '最可爱了', freq: 4 },
  { id: 'vocab-star-109', cat: 'star', word: 'รัก', roman: 'rak', zhuyin: '拉克', meaning: '爱', pos: 'v.', ex_thai: 'รักนะ', ex_cn: '爱你', freq: 4 },
  { id: 'vocab-star-110', cat: 'star', word: 'เก่ง', roman: 'keng', zhuyin: '庚', meaning: '厉害', pos: 'adj.', ex_thai: 'เก่งมากๆ', ex_cn: '好厉害', freq: 4 },
  { id: 'vocab-star-111', cat: 'star', word: 'สู้', roman: 'su', zhuyin: '素', meaning: '加油/战斗', pos: 'v.', ex_thai: 'สู้ๆ นะ', ex_cn: '加油', freq: 4 },
  { id: 'vocab-star-112', cat: 'star', word: 'ทำ', roman: 'tham', zhuyin: '探', meaning: '做', pos: '', ex_thai: 'ทำต่อไปนะ', ex_cn: '继续做下去', freq: 4 },
  { id: 'vocab-star-113', cat: 'star', word: 'รอ', roman: 'ro', zhuyin: '罗', meaning: '等', pos: 'v.', ex_thai: 'รอผลงานต่อไป', ex_cn: '期待接下来的作品', freq: 4 },
  { id: 'vocab-star-114', cat: 'star', word: 'ถึง', roman: 'thueng', zhuyin: '统', meaning: '到', pos: 'v.', ex_thai: 'ไปให้ถึงฝันนะ', ex_cn: '去实现梦想吧', freq: 4 },
  { id: 'vocab-star-115', cat: 'star', word: 'หล่อ', roman: 'lo', zhuyin: '劳', meaning: '帅', pos: 'adj.', ex_thai: 'หล่อมาก', ex_cn: '好帅', freq: 3 },
  { id: 'vocab-star-116', cat: 'star', word: 'แฟนคลับ', roman: 'faen khlup', zhuyin: '粉克鲁', meaning: '粉丝团', pos: 'n.', ex_thai: 'อยากเป็นแฟนคลับตลอดไป', ex_cn: '想当一辈子粉丝', freq: 3 },
  { id: 'vocab-star-117', cat: 'star', word: 'สวย', roman: 'suai', zhuyin: '随', meaning: '漂亮', pos: 'adj.', ex_thai: 'สวยมาก', ex_cn: '好美', freq: 3 },
  { id: 'vocab-star-118', cat: 'star', word: 'ใจ', roman: 'chai', zhuyin: '柴', meaning: '心', pos: '', ex_thai: 'ใจเธองดงาม', ex_cn: '你的心灵很美', freq: 3 },
  { id: 'vocab-star-119', cat: 'star', word: 'เสมอ', roman: 'sa moe', zhuyin: '萨摩', meaning: '总是/一直', pos: 'adv.', ex_thai: 'เชียร์เธอเสมอ', ex_cn: '一直为你加油', freq: 3 },
  { id: 'vocab-star-120', cat: 'star', word: 'อย่า', roman: 'ya', zhuyin: '雅', meaning: '别/不要', pos: '', ex_thai: 'อย่ายอมแพ้นะ', ex_cn: '不要放弃', freq: 3 },
  { id: 'vocab-star-121', cat: 'star', word: 'ว่า', roman: 'wa', zhuyin: '瓦', meaning: '说/称', pos: '', ex_thai: 'ไม่ว่ายังไงก็สนับสนุน', ex_cn: '不管怎样都支持你', freq: 3 },
  { id: 'vocab-star-122', cat: 'star', word: 'ฝัน', roman: 'fan', zhuyin: '范', meaning: '梦想', pos: '', ex_thai: 'ไปให้ถึงฝันนะ', ex_cn: '去实现梦想吧', freq: 3 },
  { id: 'vocab-star-123', cat: 'star', word: 'สนามบิน', roman: 'sanambin', zhuyin: '萨南宾', meaning: '机场', pos: 'n.', ex_thai: 'รออยู่ที่สนามบิน', ex_cn: '在机场等', freq: 3 },
  { id: 'vocab-star-124', cat: 'star', word: 'ถ่ายรูป', roman: 'thai rup', zhuyin: '泰鲁', meaning: '拍照', pos: '', ex_thai: 'ขอถ่ายรูปหน่อยได้ไหม', ex_cn: '可以拍个照吗', freq: 3 },
  { id: 'vocab-star-125', cat: 'star', word: 'ขอให้', roman: 'kho hai', zhuyin: '阔海', meaning: '希望/祝', pos: '', ex_thai: 'ขอให้เดินทางราบรื่น', ex_cn: '祝旅途顺利', freq: 3 },
  { id: 'vocab-star-126', cat: 'star', word: 'เขียน', roman: 'khian', zhuyin: '基安', meaning: '写', pos: 'v.', ex_thai: 'เขียนชื่ออะไรดี', ex_cn: '写什么名字好', freq: 3 },
  { id: 'vocab-star-127', cat: 'star', word: 'ดีใจ', roman: 'di chai', zhuyin: '迪柴', meaning: '高兴', pos: 'phrase', ex_thai: 'ดีใจมากที่ได้เซ็น', ex_cn: '很高兴能签到', freq: 3 },
  { id: 'vocab-star-128', cat: 'star', word: 'วันนี้', roman: 'wan ni', zhuyin: '弯尼', meaning: '今天', pos: '', ex_thai: 'ฝันถึงวันนี้มานาน', ex_cn: '梦到这一天很久了', freq: 3 },
  { id: 'vocab-star-129', cat: 'star', word: 'ของขวัญ', roman: 'khong khwan', zhuyin: '孔宽', meaning: '礼物', pos: 'n.', ex_thai: 'ของขวัญเล็กๆ นะ', ex_cn: '小礼物', freq: 3 },
  { id: 'vocab-star-130', cat: 'star', word: 'น่ารัก', roman: 'na rak', zhuyin: '那拉克', meaning: '可爱', pos: 'adj.', ex_thai: 'น่ารักที่สุด', ex_cn: '最可爱了', freq: 2 },
  { id: 'vocab-star-131', cat: 'star', word: 'ตลอดไป', roman: 'talot pai', zhuyin: '塔洛拜', meaning: '永远', pos: '', ex_thai: 'อยากเป็นแฟนคลับตลอดไป', ex_cn: '想当一辈子粉丝', freq: 2 },
  { id: 'vocab-star-132', cat: 'star', word: 'เท่า', roman: 'thao', zhuyin: '涛', meaning: '相等/如此', pos: '', ex_thai: 'ไม่มีใครเท่าเธอ', ex_cn: '没人比得上你', freq: 2 },
  { id: 'vocab-star-133', cat: 'star', word: 'มีความสุข', roman: 'mi khwam suk', zhuyin: '米康素', meaning: '幸福', pos: 'adj.', ex_thai: 'ทำให้ฉันมีความสุข', ex_cn: '你让我很开心', freq: 2 },
  { id: 'vocab-star-134', cat: 'star', word: 'ข้างหลัง', roman: 'khang lang', zhuyin: '康朗', meaning: '后面', pos: '', ex_thai: 'เราอยู่ข้างหลังเธอเสมอ', ex_cn: '我们永远在你身后', freq: 2 },
  { id: 'vocab-star-135', cat: 'star', word: 'ตัว', roman: 'tua', zhuyin: '妥', meaning: '身体/自身', pos: '', ex_thai: 'ภูมิใจในตัวเธอ', ex_cn: '为你骄傲', freq: 2 },
  { id: 'vocab-star-136', cat: 'star', word: 'ต่อไป', roman: 'to pai', zhuyin: '多拜', meaning: '接下来', pos: '', ex_thai: 'ทำต่อไปนะ', ex_cn: '继续做下去', freq: 2 },
  { id: 'vocab-star-137', cat: 'star', word: 'ไทย', roman: 'thai', zhuyin: '泰', meaning: '泰国/泰语', pos: '', ex_thai: 'ยินดีต้อนรับมาไทย', ex_cn: '欢迎来泰国', freq: 2 },
  { id: 'vocab-star-138', cat: 'star', word: 'เจอ', roman: 'choe', zhuyin: '卓', meaning: '找到/遇到', pos: 'v.', ex_thai: 'ได้เจอแล้ว คุ้มแล้ว', ex_cn: '见到了值了', freq: 2 },
  { id: 'vocab-star-139', cat: 'star', word: 'กลับ', roman: 'klap', zhuyin: '格拉不', meaning: '回', pos: '', ex_thai: 'กลับถึงบ้านหรือยัง', ex_cn: '到家了吗', freq: 2 },
  { id: 'vocab-star-140', cat: 'star', word: 'พักผ่อน', roman: 'phak phron', zhuyin: '帕普恩', meaning: '休息', pos: '', ex_thai: 'พักผ่อนเยอะๆ นะ', ex_cn: '多休息', freq: 2 },
  { id: 'vocab-star-141', cat: 'star', word: 'เยอะ', roman: 'yoe', zhuyin: '哟', meaning: '多', pos: '', ex_thai: 'พักผ่อนเยอะๆ นะ', ex_cn: '多休息', freq: 2 },
  { id: 'vocab-star-142', cat: 'star', word: 'เดินทาง', roman: 'doen thang', zhuyin: '顿汤', meaning: '旅行/出发', pos: 'v.', ex_thai: 'เดินทางดูแลตัวเองนะ', ex_cn: '路上照顾好自己', freq: 2 },
  { id: 'vocab-star-143', cat: 'star', word: 'วันที่', roman: 'wan thi', zhuyin: '弯提', meaning: '日期', pos: '', ex_thai: 'รอวันที่ได้เจอกันอีก', ex_cn: '期待再见面', freq: 2 },
  { id: 'vocab-star-144', cat: 'star', word: 'เซ็นชื่อ', roman: 'sen chue', zhuyin: '森朱', meaning: '签名', pos: '', ex_thai: 'เซ็นชื่อให้หน่อยได้ไหม', ex_cn: '可以签个名吗', freq: 2 },
  { id: 'vocab-star-145', cat: 'star', word: 'คิว', roman: 'khiu', zhuyin: '丘', meaning: '队列/排队', pos: 'n.', ex_thai: 'รอคิวนานไหม', ex_cn: '排队排很久吗', freq: 2 },
  { id: 'vocab-star-146', cat: 'star', word: 'นาน', roman: 'nan', zhuyin: '南', meaning: '久', pos: '', ex_thai: 'รอคิวนานไหม', ex_cn: '排队排很久吗', freq: 2 },
  { id: 'vocab-star-147', cat: 'star', word: 'ตัวจริง', roman: 'tua jing', zhuyin: '妥晶', meaning: '真身/本人', pos: '', ex_thai: 'ตัวจริงหล่อกว่าในจอ', ex_cn: '真人比屏幕上还帅', freq: 2 },
  { id: 'vocab-star-148', cat: 'star', word: 'กว่า', roman: 'kwa', zhuyin: '瓜', meaning: '比/超过', pos: '', ex_thai: 'ตัวจริงหล่อกว่าในจอ', ex_cn: '真人比屏幕上还帅', freq: 2 },
  { id: 'vocab-star-149', cat: 'star', word: 'จอ', roman: 'cho', zhuyin: '卓', meaning: '屏幕/预订', pos: '', ex_thai: 'ตัวจริงหล่อกว่าในจอ', ex_cn: '真人比屏幕上还帅', freq: 2 },
  { id: 'vocab-star-150', cat: 'star', word: 'กิจกรรม', roman: 'kit thi kam', zhuyin: '吉提甘', meaning: '活动', pos: '', ex_thai: 'ขอบคุณที่มีกิจกรรมนี้', ex_cn: '谢谢有这个活动', freq: 2 },
  { id: 'vocab-concert-151', cat: 'concert', word: 'ตั๋ว', roman: 'tua', zhuyin: '杜阿', meaning: '票', pos: 'n.', ex_thai: 'ซื้อตั๋วออนไลน์ที่ไหน', ex_cn: '网上在哪买票', freq: 10 },
  { id: 'vocab-concert-152', cat: 'concert', word: 'ซื้อ', roman: 'sue', zhuyin: '素', meaning: '买', pos: 'v.', ex_thai: 'ซื้อตั๋วออนไลน์ที่ไหน', ex_cn: '网上在哪买票', freq: 7 },
  { id: 'vocab-concert-153', cat: 'concert', word: 'ที่นั่ง', roman: 'thi nang', zhuyin: '提囊', meaning: '座位', pos: 'n.', ex_thai: 'ที่นั่งโซนอะไร', ex_cn: '哪个区的座位', freq: 7 },
  { id: 'vocab-concert-154', cat: 'concert', word: 'ได้', roman: 'dai', zhuyin: '代', meaning: '可以', pos: '', ex_thai: 'ซื้อตั๋ว VIP ได้ไหม', ex_cn: '可以买VIP票吗', freq: 7 },
  { id: 'vocab-concert-155', cat: 'concert', word: 'เพลง', roman: 'phleng', zhuyin: '碰', meaning: '歌', pos: 'n.', ex_thai: 'เพลงนี้', ex_cn: '这首歌', freq: 7 },
  { id: 'vocab-concert-156', cat: 'concert', word: 'ขอ', roman: 'kho', zhuyin: '阔', meaning: '要/请求', pos: 'v.', ex_thai: 'ขอแอนคอร์', ex_cn: '安可安可', freq: 7 },
  { id: 'vocab-concert-157', cat: 'concert', word: 'ที่ไหน', roman: 'thi nai', zhuyin: '提乃', meaning: '哪里', pos: '', ex_thai: 'ซื้อตั๋วออนไลน์ที่ไหน', ex_cn: '网上在哪买票', freq: 5 },
  { id: 'vocab-concert-158', cat: 'concert', word: 'คอนเสิร์ต', roman: 'khon soet', zhuyin: '康瑟', meaning: '演唱会', pos: 'n.', ex_thai: 'คอนเสิร์ตกี่โมงเริ่ม', ex_cn: '演唱会几点开始', freq: 5 },
  { id: 'vocab-concert-159', cat: 'concert', word: 'นี้', roman: 'ni', zhuyin: '尼', meaning: '这', pos: '', ex_thai: 'โซนนี้ถูกไหม', ex_cn: '这个区对吗', freq: 5 },
  { id: 'vocab-concert-160', cat: 'concert', word: 'ส่ง', roman: 'song', zhuyin: '送', meaning: '发/送', pos: 'v.', ex_thai: 'ตั๋วส่งทางไปรษณีย์ไหม', ex_cn: '票邮寄吗', freq: 4 },
  { id: 'vocab-concert-161', cat: 'concert', word: 'ทางออก', roman: 'thang ok', zhuyin: '唐欧', meaning: '出口', pos: 'n.', ex_thai: 'ทางออกฉุกเฉินอยู่ไหน', ex_cn: '紧急出口在哪', freq: 4 },
  { id: 'vocab-concert-162', cat: 'concert', word: 'สี', roman: 'si', zhuyin: '西', meaning: '颜色', pos: 'n.', ex_thai: 'สีอะไร', ex_cn: '应援色是什么', freq: 4 },
  { id: 'vocab-concert-163', cat: 'concert', word: 'หมด', roman: 'mot', zhuyin: '摩', meaning: '完了/全部', pos: '', ex_thai: 'ตั๋วหมดแล้ว', ex_cn: '票卖完了', freq: 3 },
  { id: 'vocab-concert-164', cat: 'concert', word: 'ราคา', roman: 'rakha', zhuyin: '拉卡', meaning: '价格', pos: 'n.', ex_thai: 'ตั๋วราคาเท่าไหร่', ex_cn: '票多少钱', freq: 3 },
  { id: 'vocab-concert-165', cat: 'concert', word: 'โมง', roman: 'mong', zhuyin: '蒙', meaning: '点(时间)', pos: '', ex_thai: 'คอนเสิร์ตกี่โมงเริ่ม', ex_cn: '演唱会几点开始', freq: 3 },
  { id: 'vocab-concert-166', cat: 'concert', word: 'บ้าง', roman: 'bang', zhuyin: '邦', meaning: '一些/有些', pos: '', ex_thai: 'มีคอนเสิร์ตวันไหนบ้าง', ex_cn: '有哪几场', freq: 3 },
  { id: 'vocab-concert-167', cat: 'concert', word: 'ขอบคุณ', roman: 'khop khun', zhuyin: '阔不坤', meaning: '谢谢', pos: 'phrase', ex_thai: 'ขอบคุณสำหรับคอนเสิร์ต', ex_cn: '感谢这场演唱会', freq: 3 },
  { id: 'vocab-concert-168', cat: 'concert', word: 'อันดับ', roman: 'andap', zhuyin: '安达', meaning: '排名', pos: '', ex_thai: 'เพลงขึ้นอันดับแล้ว', ex_cn: '歌曲上榜了', freq: 3 },
  { id: 'vocab-concert-169', cat: 'concert', word: 'ออนไลน์', roman: 'onlai', zhuyin: '翁莱', meaning: '线上', pos: '', ex_thai: 'ซื้อตั๋วออนไลน์ที่ไหน', ex_cn: '网上在哪买票', freq: 2 },
  { id: 'vocab-concert-170', cat: 'concert', word: 'โซน', roman: 'son', zhuyin: '松', meaning: '区', pos: '', ex_thai: 'ที่นั่งโซนอะไร', ex_cn: '哪个区的座位', freq: 2 },
  { id: 'vocab-concert-171', cat: 'concert', word: 'เปิด', roman: 'poet', zhuyin: '珀', meaning: '开', pos: 'v.', ex_thai: 'ประตูเปิดกี่โมง', ex_cn: '几点开门', freq: 2 },
  { id: 'vocab-concert-172', cat: 'concert', word: 'ต้อง', roman: 'tong', zhuyin: '东', meaning: '必须', pos: '', ex_thai: 'ต้องมาก่อนกี่โมง', ex_cn: '需要提前几小时来', freq: 2 },
  { id: 'vocab-concert-173', cat: 'concert', word: 'ฉุกเฉิน', roman: 'chuk choen', zhuyin: '出春', meaning: '紧急', pos: '', ex_thai: 'ทางออกฉุกเฉินอยู่ไหน', ex_cn: '紧急出口在哪', freq: 2 },
  { id: 'vocab-concert-174', cat: 'concert', word: 'พัก', roman: 'phak', zhuyin: '帕', meaning: '住/休息', pos: '', ex_thai: 'มีที่นั่งพักไหม', ex_cn: '有休息区吗', freq: 2 },
  { id: 'vocab-concert-175', cat: 'concert', word: 'ถูก', roman: 'thuk', zhuyin: '图', meaning: '便宜', pos: 'adj.', ex_thai: 'โซนนี้ถูกไหม', ex_cn: '这个区对吗', freq: 2 },
  { id: 'vocab-concert-176', cat: 'concert', word: 'ตาม', roman: 'tam', zhuyin: '探', meaning: '跟随/按照', pos: '', ex_thai: 'ตะโกนตามฉัน', ex_cn: '跟我喊', freq: 2 },
  { id: 'vocab-concert-177', cat: 'concert', word: 'ฟังเพลง', roman: 'fang pleng', zhuyin: '方普棱', meaning: '听歌', pos: '', ex_thai: 'ช่วยฟังเพลงนี้', ex_cn: '请听这首歌', freq: 2 },
  { id: 'vocab-concert-178', cat: 'concert', word: 'ขอให้', roman: 'kho hai', zhuyin: '阔海', meaning: '希望/祝', pos: '', ex_thai: 'ขอให้ขึ้นอันดับ 1', ex_cn: '希望能上第一', freq: 2 },
  { id: 'vocab-concert-179', cat: 'concert', word: 'ใหม่', roman: 'mai', zhuyin: '迈', meaning: '新', pos: 'adj.', ex_thai: 'เพลงใหม่ออกแล้ว', ex_cn: '新歌发了', freq: 2 },
  { id: 'vocab-concert-180', cat: 'concert', word: 'โทรศัพท์', roman: 'thorasap', zhuyin: '托拉萨', meaning: '手机', pos: '', ex_thai: 'โทรศัพท์หาย', ex_cn: '手机丢了', freq: 2 },
  { id: 'vocab-concert-181', cat: 'concert', word: 'หาย', roman: 'hai', zhuyin: '海', meaning: '消失/丢失', pos: '', ex_thai: 'โทรศัพท์หาย', ex_cn: '手机丢了', freq: 2 },
  { id: 'vocab-concert-182', cat: 'concert', word: 'รับ', roman: 'rap', zhuyin: '拉不', meaning: '取/收', pos: '', ex_thai: 'รับตั๋วที่ไหน', ex_cn: '在哪取票', freq: 1 },
  { id: 'vocab-concert-183', cat: 'concert', word: 'ยังมี', roman: 'yang mi', zhuyin: '央米', meaning: '还有', pos: '', ex_thai: 'ยังมีตั๋วเหลือไหม', ex_cn: '还有票吗', freq: 1 },
  { id: 'vocab-concert-184', cat: 'concert', word: 'เหลือ', roman: 'luea', zhuyin: '律雅', meaning: '剩/剩余', pos: '', ex_thai: 'ยังมีตั๋วเหลือไหม', ex_cn: '还有票吗', freq: 1 },
  { id: 'vocab-concert-185', cat: 'concert', word: 'VIP', roman: 'VIP', zhuyin: 'VIP', meaning: 'VIP', pos: '', ex_thai: 'ซื้อตั๋ว VIP ได้ไหม', ex_cn: '可以买VIP票吗', freq: 1 },
  { id: 'vocab-concert-186', cat: 'concert', word: 'แถวหน้า', roman: 'thaeo na', zhuyin: '泰欧那', meaning: '前排', pos: '', ex_thai: 'ที่นั่งแถวหน้า', ex_cn: '前排座位', freq: 1 },
  { id: 'vocab-concert-187', cat: 'concert', word: 'แถว', roman: 'thaeo', zhuyin: '泰欧', meaning: '排/区域', pos: 'n.', ex_thai: 'ที่นั่งแถวหลัง', ex_cn: '后排座位', freq: 1 },
  { id: 'vocab-concert-188', cat: 'concert', word: 'เริ่ม', roman: 'roem', zhuyin: '伦', meaning: '开始', pos: '', ex_thai: 'คอนเสิร์ตกี่โมงเริ่ม', ex_cn: '演唱会几点开始', freq: 1 },
  { id: 'vocab-concert-189', cat: 'concert', word: 'ประตู', roman: 'pratu', zhuyin: '普拉度', meaning: '门', pos: 'n.', ex_thai: 'ประตูเปิดกี่โมง', ex_cn: '几点开门', freq: 1 },
  { id: 'vocab-concert-190', cat: 'concert', word: 'เร็ว', roman: 'reo', zhuyin: '列', meaning: '快', pos: 'adj.', ex_thai: 'ตั๋วหมดเร็วมาก', ex_cn: '票卖得很快', freq: 1 },
  { id: 'vocab-concert-191', cat: 'concert', word: 'แล้วแต่', roman: 'laeo tae', zhuyin: '料代', meaning: '取决于', pos: '', ex_thai: 'แล้วแต่โชค', ex_cn: '看运气', freq: 1 },
  { id: 'vocab-concert-192', cat: 'concert', word: 'โชค', roman: 'chok', zhuyin: '卓', meaning: '运气', pos: '', ex_thai: 'แล้วแต่โชค', ex_cn: '看运气', freq: 1 },
  { id: 'vocab-concert-193', cat: 'concert', word: 'resell', roman: 'ri sel', zhuyin: 'resell', meaning: '转卖', pos: '', ex_thai: 'ซื้อตั๋ว resell ได้ไหม', ex_cn: '可以买转让票吗', freq: 1 },
  { id: 'vocab-concert-194', cat: 'concert', word: 'โชว์', roman: 'cho', zhuyin: '卓', meaning: '展示/Show', pos: '', ex_thai: 'ต้องโชว์บัตรประชาชนไหม', ex_cn: '需要出示身份证吗', freq: 1 },
  { id: 'vocab-concert-195', cat: 'concert', word: 'บัตรประชาชน', roman: 'bat pra chachon', zhuyin: '巴普拉查充', meaning: '身份证', pos: '', ex_thai: 'ต้องโชว์บัตรประชาชนไหม', ex_cn: '需要出示身份证吗', freq: 1 },
  { id: 'vocab-concert-196', cat: 'concert', word: 'ทางไปรษณีย์', roman: 'thang pra sai', zhuyin: '汤普拉塞', meaning: '邮政', pos: '', ex_thai: 'ตั๋วส่งทางไปรษณีย์ไหม', ex_cn: '票邮寄吗', freq: 1 },
  { id: 'vocab-concert-197', cat: 'concert', word: 'e-ticket', roman: 'i thik et', zhuyin: 'e-ticket', meaning: '电子票', pos: '', ex_thai: 'ตั๋ว e-ticket ใช้ได้ไหม', ex_cn: '电子票可以吗', freq: 1 },
  { id: 'vocab-concert-198', cat: 'concert', word: 'ใช้ได้', roman: 'chai dai', zhuyin: '柴代', meaning: '可以用', pos: '', ex_thai: 'ตั๋ว e-ticket ใช้ได้ไหม', ex_cn: '电子票可以吗', freq: 1 },
  { id: 'vocab-concert-199', cat: 'concert', word: 'วัน', roman: 'wan', zhuyin: '弯', meaning: '天/日', pos: 'n.', ex_thai: 'มีคอนเสิร์ตวันไหนบ้าง', ex_cn: '有哪几场', freq: 1 },
  { id: 'vocab-concert-200', cat: 'concert', word: 'ทางเข้า', roman: 'thang khao', zhuyin: '唐考', meaning: '入口', pos: '', ex_thai: 'ทางเข้าอยู่ไหน', ex_cn: '入口在哪', freq: 1 },
  { id: 'vocab-social-201', cat: 'social', word: 'โหวต', roman: 'wot', zhuyin: '沃', meaning: '投票', pos: 'v.', ex_thai: 'โหวตให้หน่อย', ex_cn: '帮投个票', freq: 12 },
  { id: 'vocab-social-202', cat: 'social', word: 'ขอ', roman: 'kho', zhuyin: '阔', meaning: '要/请求', pos: 'v.', ex_thai: 'ขอคอมเมนต์ดีๆ', ex_cn: '求好评', freq: 9 },
  { id: 'vocab-social-203', cat: 'social', word: 'ไลฟ์', roman: 'laif', zhuyin: '莱', meaning: '直播/Live', pos: 'n.', ex_thai: 'มีไลฟ์ไลฟ์ไหม', ex_cn: '有直播吗', freq: 9 },
  { id: 'vocab-social-204', cat: 'social', word: 'โพสต์', roman: 'phot', zhuyin: '波', meaning: '发帖', pos: 'n.', ex_thai: 'รีโพสต์ด้วยนะ', ex_cn: '请转发', freq: 7 },
  { id: 'vocab-social-205', cat: 'social', word: 'คอมเมนต์', roman: 'khammet', zhuyin: '康门', meaning: '评论', pos: 'n.', ex_thai: 'คอมเมนต์ด้วย', ex_cn: '也评论一下', freq: 7 },
  { id: 'vocab-social-206', cat: 'social', word: 'เทรนด์', roman: 'throet', zhuyin: '特伦', meaning: '趋势', pos: 'n.', ex_thai: 'เทรนด์อันดับ 1', ex_cn: '趋势第一', freq: 6 },
  { id: 'vocab-social-207', cat: 'social', word: 'แชร์', roman: 'chaoe', zhuyin: '切', meaning: '分享', pos: 'v.', ex_thai: 'แชร์โพสต์นี้', ex_cn: '分享这条', freq: 5 },
  { id: 'vocab-social-208', cat: 'social', word: 'นี้', roman: 'ni', zhuyin: '尼', meaning: '这', pos: '', ex_thai: 'แชร์โพสต์นี้', ex_cn: '分享这条', freq: 5 },
  { id: 'vocab-social-209', cat: 'social', word: 'ใหม่', roman: 'mai', zhuyin: '迈', meaning: '新', pos: 'adj.', ex_thai: 'มีข่าวใหม่ไหม', ex_cn: '有新消息吗', freq: 5 },
  { id: 'vocab-social-210', cat: 'social', word: 'กด', roman: 'kot', zhuyin: '过', meaning: '按', pos: 'v.', ex_thai: 'กดถูกใจด้วย', ex_cn: '也点赞', freq: 4 },
  { id: 'vocab-social-211', cat: 'social', word: 'สวย', roman: 'suai', zhuyin: '随', meaning: '漂亮', pos: 'adj.', ex_thai: 'สวยมาก', ex_cn: '好美', freq: 4 },
  { id: 'vocab-social-212', cat: 'social', word: 'เยอะ', roman: 'yoe', zhuyin: '哟', meaning: '多', pos: '', ex_thai: 'ยอดวิวเยอะจัง', ex_cn: '播放量好高', freq: 4 },
  { id: 'vocab-social-213', cat: 'social', word: 'วิดีโอ', roman: 'wi di o', zhuyin: '维迪欧', meaning: '视频', pos: 'n.', ex_thai: 'วิดีโอติดเทรนด์', ex_cn: '视频上热门了', freq: 4 },
  { id: 'vocab-social-214', cat: 'social', word: 'แท็ก', roman: 'thaek', zhuyin: '泰', meaning: 'tag/标记', pos: '', ex_thai: 'แท็กหน่อย', ex_cn: 'tag一下', freq: 3 },
  { id: 'vocab-social-215', cat: 'social', word: 'ติด', roman: 'tit', zhuyin: '低', meaning: '上瘾/粘', pos: '', ex_thai: 'ติดเทรนด์แล้ว', ex_cn: '上趋势了', freq: 3 },
  { id: 'vocab-social-216', cat: 'social', word: 'ดี', roman: 'di', zhuyin: '迪', meaning: '好', pos: '', ex_thai: 'ขอคอมเมนต์ดีๆ', ex_cn: '求好评', freq: 3 },
  { id: 'vocab-social-217', cat: 'social', word: 'บัญชี', roman: 'ban chue', zhuyin: '班朱', meaning: '账户', pos: '', ex_thai: 'บัญชีทวิตเตอร์คืออะไร', ex_cn: '推特账号是什么', freq: 3 },
  { id: 'vocab-social-218', cat: 'social', word: 'จัง', roman: 'chang', zhuyin: '章', meaning: '好/真', pos: 'adv.', ex_thai: 'เซลฟี่นี้ดีจัง', ex_cn: '这自拍绝了', freq: 3 },
  { id: 'vocab-social-219', cat: 'social', word: 'วิว', roman: 'wiu', zhuyin: '维尤', meaning: 'Views(浏览量)', pos: '', ex_thai: 'วิวสวยมาก', ex_cn: '风景好美', freq: 3 },
  { id: 'vocab-social-220', cat: 'social', word: 'ดู', roman: 'du', zhuyin: '嘟', meaning: '看', pos: 'v.', ex_thai: 'แชร์ให้เพื่อนดู', ex_cn: '分享给朋友看', freq: 3 },
  { id: 'vocab-social-221', cat: 'social', word: 'เพลง', roman: 'phleng', zhuyin: '碰', meaning: '歌', pos: 'n.', ex_thai: 'เพลงนี้เพราะ', ex_cn: '这首歌好听', freq: 3 },
  { id: 'vocab-social-222', cat: 'social', word: 'รี', roman: 'ri', zhuyin: '里', meaning: '里(前缀)', pos: '', ex_thai: 'รีโพสต์ด้วยนะ', ex_cn: '请转发', freq: 2 },
  { id: 'vocab-social-223', cat: 'social', word: 'ฟอ', roman: 'fo', zhuyin: '佛', meaning: '福(名)', pos: '', ex_thai: 'ฟอลลอว์กลับด้วย', ex_cn: '求回关', freq: 2 },
  { id: 'vocab-social-224', cat: 'social', word: 'ลลอว์', roman: 'la lo', zhuyin: '拉洛', meaning: 'Lalow(名)', pos: '', ex_thai: 'ฟอลลอว์กลับด้วย', ex_cn: '求回关', freq: 2 },
  { id: 'vocab-social-225', cat: 'social', word: 'กลับ', roman: 'klap', zhuyin: '格拉不', meaning: '回', pos: '', ex_thai: 'ฟอลลอว์กลับด้วย', ex_cn: '求回关', freq: 2 },
  { id: 'vocab-social-226', cat: 'social', word: 'ช่วยกัน', roman: 'chuai kan', zhuyin: '猜甘', meaning: '互相帮助', pos: '', ex_thai: 'ช่วยกันเทรนด์', ex_cn: '一起冲趋势', freq: 2 },
  { id: 'vocab-social-227', cat: 'social', word: 'อย่า', roman: 'ya', zhuyin: '雅', meaning: '别/不要', pos: '', ex_thai: 'อย่าลืมแท็ก', ex_cn: '别忘了tag', freq: 2 },
  { id: 'vocab-social-228', cat: 'social', word: 'ลืม', roman: 'luem', zhuyin: '伦', meaning: '忘', pos: 'v.', ex_thai: 'อย่าลืมแท็ก', ex_cn: '别忘了tag', freq: 2 },
  { id: 'vocab-social-229', cat: 'social', word: 'บ่อยๆ', roman: 'boi boi', zhuyin: '波衣波衣', meaning: '经常', pos: '', ex_thai: 'อัปเดทบ่อยๆ นะ', ex_cn: '多更新哦', freq: 2 },
  { id: 'vocab-social-230', cat: 'social', word: 'รอ', roman: 'ro', zhuyin: '罗', meaning: '等', pos: 'v.', ex_thai: 'รอโพสต์ใหม่', ex_cn: '等新帖', freq: 2 },
  { id: 'vocab-social-231', cat: 'social', word: 'สตอ', roman: 'sa to', zhuyin: '萨多', meaning: 'Story', pos: '', ex_thai: 'สตอรี่น่ารัก', ex_cn: 'story好可爱', freq: 2 },
  { id: 'vocab-social-232', cat: 'social', word: 'รี่', roman: 'ri', zhuyin: '里', meaning: '里(语气)', pos: '', ex_thai: 'สตอรี่น่ารัก', ex_cn: 'story好可爱', freq: 2 },
  { id: 'vocab-social-233', cat: 'social', word: 'น่ารัก', roman: 'na rak', zhuyin: '那拉克', meaning: '可爱', pos: 'adj.', ex_thai: 'สตอรี่น่ารัก', ex_cn: 'story好可爱', freq: 2 },
  { id: 'vocab-social-234', cat: 'social', word: 'เพิ่ม', roman: 'phoem', zhuyin: '蓬', meaning: '增加', pos: '', ex_thai: 'ขอสตอรี่เพิ่ม', ex_cn: '多发story', freq: 2 },
  { id: 'vocab-social-235', cat: 'social', word: 'ดีมาก', roman: 'di mak', zhuyin: '迪玛', meaning: '很好', pos: 'adj.', ex_thai: 'รีลดีมาก', ex_cn: 'Reel很好看', freq: 2 },
  { id: 'vocab-social-236', cat: 'social', word: 'เพื่อน', roman: 'phuean', zhuyin: '朋', meaning: '朋友', pos: 'n.', ex_thai: 'แชร์ให้เพื่อนดู', ex_cn: '分享给朋友看', freq: 2 },
  { id: 'vocab-social-237', cat: 'social', word: 'ไลค์', roman: 'lai', zhuyin: '赖', meaning: '点赞', pos: '', ex_thai: 'ไลค์แล้ว', ex_cn: '已点赞', freq: 2 },
  { id: 'vocab-social-238', cat: 'social', word: 'ยอด', roman: 'yot', zhuyin: '约', meaning: '顶级', pos: '', ex_thai: 'ยอดวิวเยอะจัง', ex_cn: '播放量好高', freq: 2 },
  { id: 'vocab-social-239', cat: 'social', word: 'ทำ', roman: 'tham', zhuyin: '探', meaning: '做', pos: '', ex_thai: 'ขอทำชาเลนจ์', ex_cn: '想做挑战', freq: 2 },
  { id: 'vocab-social-240', cat: 'social', word: 'ลิงก์', roman: 'ling', zhuyin: '林', meaning: '链接', pos: '', ex_thai: 'ขอลิงก์เพลง', ex_cn: '求歌曲链接', freq: 2 },
  { id: 'vocab-social-241', cat: 'social', word: 'ขอบคุณ', roman: 'khop khun', zhuyin: '阔不坤', meaning: '谢谢', pos: 'phrase', ex_thai: 'ขอบคุณสำหรับไลฟ์', ex_cn: '谢谢直播', freq: 2 },
  { id: 'vocab-social-242', cat: 'social', word: 'ชนะ', roman: 'cha na', zhuyin: '嘉纳', meaning: '赢', pos: '', ex_thai: 'เกือบชนะแล้ว', ex_cn: '快赢了', freq: 2 },
  { id: 'vocab-social-243', cat: 'social', word: 'อันดับ', roman: 'andap', zhuyin: '安达', meaning: '排名', pos: '', ex_thai: 'เทรนด์อันดับ 1', ex_cn: '趋势第一', freq: 1 },
  { id: 'vocab-social-244', cat: 'social', word: 'ชื่อ', roman: 'chue', zhuyin: '切', meaning: '名字', pos: 'n.', ex_thai: 'ชื่อแฮชแท็กอะไร', ex_cn: '话题标签是什么', freq: 1 },
  { id: 'vocab-social-245', cat: 'social', word: 'แฮ', roman: 'hae', zhuyin: '嘿', meaning: '哈(语气)', pos: '', ex_thai: 'ชื่อแฮชแท็กอะไร', ex_cn: '话题标签是什么', freq: 1 },
  { id: 'vocab-social-246', cat: 'social', word: 'ล่าสุด', roman: 'la sut', zhuyin: '拉素', meaning: '最新', pos: '', ex_thai: 'โพสต์ล่าสุด', ex_cn: '最新推文', freq: 1 },
  { id: 'vocab-social-247', cat: 'social', word: 'ข่าว', roman: 'khao', zhuyin: '考', meaning: '新闻', pos: '', ex_thai: 'มีข่าวใหม่ไหม', ex_cn: '有新消息吗', freq: 1 },
  { id: 'vocab-social-248', cat: 'social', word: 'เร', roman: 're', zhuyin: '热', meaning: '热(语气)', pos: '', ex_thai: 'เรทวิตให้แล้ว', ex_cn: '已经转推了', freq: 1 },
  { id: 'vocab-social-249', cat: 'social', word: 'ทวิ', roman: 'thawi', zhuyin: '塔维', meaning: '双/二', pos: '', ex_thai: 'เรทวิตให้แล้ว', ex_cn: '已经转推了', freq: 1 },
  { id: 'vocab-social-250', cat: 'social', word: 'โปรไฟล์', roman: 'pro fai', zhuyin: '普罗法衣', meaning: '个人资料/Profile', pos: '', ex_thai: 'โปรไฟล์อัปเดตแล้ว', ex_cn: '主页更新了', freq: 1 },
  { id: 'vocab-offline-251', cat: 'offline', word: 'ขอ', roman: 'kho', zhuyin: '阔', meaning: '要/请求', pos: 'v.', ex_thai: 'ขอถ่ายรูปที่นี่', ex_cn: '想在这里拍照', freq: 19 },
  { id: 'vocab-offline-252', cat: 'offline', word: 'แฟนคลับ', roman: 'faen khlup', zhuyin: '粉克鲁', meaning: '粉丝团', pos: 'n.', ex_thai: 'แฟนคลับมาเยอะไหม', ex_cn: '粉丝来多吗', freq: 6 },
  { id: 'vocab-offline-253', cat: 'offline', word: 'นี้', roman: 'ni', zhuyin: '尼', meaning: '这', pos: '', ex_thai: 'ร้านนี้พวกเขามากินจริงไหม', ex_cn: '这家店他们真来吃过吗', freq: 5 },
  { id: 'vocab-offline-254', cat: 'offline', word: 'ส่ง', roman: 'song', zhuyin: '送', meaning: '发/送', pos: 'v.', ex_thai: 'ค่าส่งเท่าไหร่', ex_cn: '运费多少', freq: 5 },
  { id: 'vocab-offline-255', cat: 'offline', word: 'โหวต', roman: 'wot', zhuyin: '沃', meaning: '投票', pos: 'v.', ex_thai: 'โหวตยังไง', ex_cn: '怎么投票', freq: 5 },
  { id: 'vocab-offline-256', cat: 'offline', word: 'ที่นี่', roman: 'thi ni', zhuyin: '提尼', meaning: '这里', pos: 'n.', ex_thai: 'ที่นี่ถ่ายหนังเรื่องอะไร', ex_cn: '这里拍了什么剧', freq: 4 },
  { id: 'vocab-offline-257', cat: 'offline', word: 'ซื้อ', roman: 'sue', zhuyin: '素', meaning: '买', pos: 'v.', ex_thai: 'ซื้อออนไลน์ได้ไหม', ex_cn: '可以网购吗', freq: 4 },
  { id: 'vocab-offline-258', cat: 'offline', word: 'ได้', roman: 'dai', zhuyin: '代', meaning: '可以', pos: '', ex_thai: 'ซื้อออนไลน์ได้ไหม', ex_cn: '可以网购吗', freq: 4 },
  { id: 'vocab-offline-259', cat: 'offline', word: 'ถึง', roman: 'thueng', zhuyin: '统', meaning: '到', pos: 'v.', ex_thai: 'ส่งถึงสถานที่จัดกิจกรรม', ex_cn: '送到活动场地', freq: 4 },
  { id: 'vocab-offline-260', cat: 'offline', word: 'หนัง', roman: 'nang', zhuyin: '囊', meaning: '电影', pos: 'n.', ex_thai: 'เหมือนในหนังเลย', ex_cn: '跟剧里一样', freq: 3 },
  { id: 'vocab-offline-261', cat: 'offline', word: 'สั่ง', roman: 'sang', zhuyin: '桑', meaning: '点单/命令', pos: 'v.', ex_thai: 'ขอสั่งอันนั้นด้วย', ex_cn: '来一份', freq: 3 },
  { id: 'vocab-offline-262', cat: 'offline', word: 'บ้าง', roman: 'bang', zhuyin: '邦', meaning: '一些/有些', pos: '', ex_thai: 'สีอะไรมีบ้าง', ex_cn: '有什么颜色', freq: 3 },
  { id: 'vocab-offline-263', cat: 'offline', word: 'พวงมาลัย', roman: 'phuang malai', zhuyin: '普安玛莱', meaning: '花环', pos: 'n.', ex_thai: 'สั่งพวงมาลัย', ex_cn: '订花篮', freq: 3 },
  { id: 'vocab-offline-264', cat: 'offline', word: 'เขียน', roman: 'khian', zhuyin: '基安', meaning: '写', pos: 'v.', ex_thai: 'ขอเขียนการ์ด', ex_cn: '想写卡片', freq: 3 },
  { id: 'vocab-offline-265', cat: 'offline', word: 'สมัคร', roman: 'samak', zhuyin: '萨玛', meaning: '注册', pos: '', ex_thai: 'สมัครแฟนคลับยังไง', ex_cn: '怎么加入粉丝团', freq: 3 },
  { id: 'vocab-offline-266', cat: 'offline', word: 'สมาชิก', roman: 'samachik', zhuyin: '萨玛吉', meaning: '会员', pos: '', ex_thai: 'ค่าสมาชิกเท่าไหร่', ex_cn: '会费多少', freq: 3 },
  { id: 'vocab-offline-267', cat: 'offline', word: 'ถ่ายหนัง', roman: 'thai nang', zhuyin: '泰囊', meaning: '拍电影', pos: '', ex_thai: 'ที่นี่ถ่ายหนังเรื่องอะไร', ex_cn: '这里拍了什么剧', freq: 2 },
  { id: 'vocab-offline-268', cat: 'offline', word: 'ร้าน', roman: 'ran', zhuyin: '兰', meaning: '店', pos: 'n.', ex_thai: 'ร้านนี้พวกเขามากินจริงไหม', ex_cn: '这家店他们真来吃过吗', freq: 2 },
  { id: 'vocab-offline-269', cat: 'offline', word: 'อันนั้น', roman: 'an nan', zhuyin: '安南', meaning: '那个', pos: '', ex_thai: 'ขอสั่งอันนั้นด้วย', ex_cn: '来一份', freq: 2 },
  { id: 'vocab-offline-270', cat: 'offline', word: 'สถานที่', roman: 'sa than thi', zhuyin: '萨探提', meaning: '地点/场所', pos: '', ex_thai: 'สถานที่ถ่ายทำ', ex_cn: '拍摄地点', freq: 2 },
  { id: 'vocab-offline-271', cat: 'offline', word: 'ถ่ายทำ', roman: 'thai tham', zhuyin: '泰探', meaning: '拍摄', pos: '', ex_thai: 'สถานที่ถ่ายทำ', ex_cn: '拍摄地点', freq: 2 },
  { id: 'vocab-offline-272', cat: 'offline', word: 'สวย', roman: 'suai', zhuyin: '随', meaning: '漂亮', pos: 'adj.', ex_thai: 'วิวสวยจัง', ex_cn: '风景好美', freq: 2 },
  { id: 'vocab-offline-273', cat: 'offline', word: 'ราคา', roman: 'rakha', zhuyin: '拉卡', meaning: '价格', pos: 'n.', ex_thai: 'ราคาเท่าไหร่', ex_cn: '多少钱', freq: 2 },
  { id: 'vocab-offline-274', cat: 'offline', word: 'ออนไลน์', roman: 'onlai', zhuyin: '翁莱', meaning: '线上', pos: '', ex_thai: 'ซื้อออนไลน์ได้ไหม', ex_cn: '可以网购吗', freq: 2 },
  { id: 'vocab-offline-275', cat: 'offline', word: 'ใหม่', roman: 'mai', zhuyin: '迈', meaning: '新', pos: 'adj.', ex_thai: 'มีลายใหม่ไหม', ex_cn: '有新款式吗', freq: 2 },
  { id: 'vocab-offline-276', cat: 'offline', word: 'ดู', roman: 'du', zhuyin: '嘟', meaning: '看', pos: 'v.', ex_thai: 'ขอดูอันนั้น', ex_cn: '看那个', freq: 2 },
  { id: 'vocab-offline-277', cat: 'offline', word: 'สี', roman: 'si', zhuyin: '西', meaning: '颜色', pos: 'n.', ex_thai: 'สีอะไรมีบ้าง', ex_cn: '有什么颜色', freq: 2 },
  { id: 'vocab-offline-278', cat: 'offline', word: 'ของแถม', roman: 'khong thaem', zhuyin: '孔探', meaning: '赠品', pos: '', ex_thai: 'ของแถมมีไหม', ex_cn: '有赠品吗', freq: 2 },
  { id: 'vocab-offline-279', cat: 'offline', word: 'ค่า', roman: 'kha', zhuyin: '卡', meaning: '费用/价值', pos: '', ex_thai: 'ค่าส่งเท่าไหร่', ex_cn: '运费多少', freq: 2 },
  { id: 'vocab-offline-280', cat: 'offline', word: 'วัน', roman: 'wan', zhuyin: '弯', meaning: '天/日', pos: 'n.', ex_thai: 'ส่งถึงวันไหน', ex_cn: '送到哪天', freq: 2 },
  { id: 'vocab-offline-281', cat: 'offline', word: 'งาน', roman: 'ngan', zhuyin: '恩', meaning: '工作/活动', pos: '', ex_thai: 'ตั้งอยู่หน้างาน', ex_cn: '放在活动门口', freq: 2 },
  { id: 'vocab-offline-282', cat: 'offline', word: 'ขอบคุณ', roman: 'khop khun', zhuyin: '阔不坤', meaning: '谢谢', pos: 'phrase', ex_thai: 'ขอบคุณมาก', ex_cn: '非常感谢', freq: 2 },
  { id: 'vocab-offline-283', cat: 'offline', word: 'กิจกรรม', roman: 'kit thi kam', zhuyin: '吉提甘', meaning: '活动', pos: '', ex_thai: 'มีกิจกรรมไหม', ex_cn: '有活动吗', freq: 2 },
  { id: 'vocab-offline-284', cat: 'offline', word: 'ต่อไป', roman: 'to pai', zhuyin: '多拜', meaning: '接下来', pos: '', ex_thai: 'มีกิจกรรมต่อไปไหม', ex_cn: '有后续活动吗', freq: 2 },
  { id: 'vocab-offline-285', cat: 'offline', word: 'ภูมิใจ', roman: 'phum chai', zhuyin: '普姆柴', meaning: '自豪', pos: '', ex_thai: 'ภูมิใจที่เป็นแฟนคลับ', ex_cn: '以粉丝身份为荣', freq: 2 },
  { id: 'vocab-offline-286', cat: 'offline', word: 'ผ่าน', roman: 'phan', zhuyin: '潘', meaning: '通过', pos: '', ex_thai: 'ผ่านเข้ารอบไหม', ex_cn: '进了吗', freq: 2 },
  { id: 'vocab-offline-287', cat: 'offline', word: 'เข้ารอบ', roman: 'khao rop', zhuyin: '考罗', meaning: '入围/晋级', pos: '', ex_thai: 'ผ่านเข้ารอบไหม', ex_cn: '进了吗', freq: 2 },
  { id: 'vocab-offline-288', cat: 'offline', word: 'รอบ', roman: 'rop', zhuyin: '罗', meaning: '轮次/场', pos: '', ex_thai: 'รอบต่อไป', ex_cn: '下一轮', freq: 2 },
  { id: 'vocab-offline-289', cat: 'offline', word: 'ชิง', roman: 'ching', zhuyin: '精', meaning: '争夺/抢', pos: '', ex_thai: 'รอบชิง', ex_cn: '决赛', freq: 2 },
  { id: 'vocab-offline-290', cat: 'offline', word: 'ผล', roman: 'phon', zhuyin: '喷', meaning: '结果', pos: '', ex_thai: 'รอผล', ex_cn: '等结果', freq: 2 },
  { id: 'vocab-offline-291', cat: 'offline', word: 'โทร', roman: 'tho', zhuyin: '托', meaning: '打电话', pos: '', ex_thai: 'โทรเรียกแท็กซี่', ex_cn: '打电话叫出租车', freq: 2 },
  { id: 'vocab-offline-292', cat: 'offline', word: 'ชาร์จ', roman: 'cha', zhuyin: '查', meaning: '充电', pos: '', ex_thai: 'ขอชาร์จโทรศัพท์', ex_cn: '充电', freq: 2 },
  { id: 'vocab-offline-293', cat: 'offline', word: 'เบอร์', roman: 'boe', zhuyin: '珀', meaning: '号码', pos: 'n.', ex_thai: 'เบอร์โทรเท่าไหร่', ex_cn: '电话多少', freq: 2 },
  { id: 'vocab-offline-294', cat: 'offline', word: 'ใกล้', roman: 'klai', zhuyin: '克莱', meaning: '近', pos: '', ex_thai: 'โรงพยาบาลใกล้สุด', ex_cn: '最近的医院', freq: 2 },
  { id: 'vocab-offline-295', cat: 'offline', word: 'เรื่อง', roman: 'rueang', zhuyin: '软', meaning: '部/故事', pos: 'n.', ex_thai: 'ที่นี่ถ่ายหนังเรื่องอะไร', ex_cn: '这里拍了什么剧', freq: 1 },
  { id: 'vocab-offline-296', cat: 'offline', word: 'กิน', roman: 'kin', zhuyin: '金', meaning: '吃', pos: '', ex_thai: 'ร้านนี้พวกเขามากินจริงไหม', ex_cn: '这家店他们真来吃过吗', freq: 1 },
  { id: 'vocab-offline-297', cat: 'offline', word: 'จริง', roman: 'ching', zhuyin: '晶', meaning: '真', pos: 'adv.', ex_thai: 'ร้านนี้พวกเขามากินจริงไหม', ex_cn: '这家店他们真来吃过吗', freq: 1 },
  { id: 'vocab-offline-298', cat: 'offline', word: 'ถ่ายรูป', roman: 'thai rup', zhuyin: '泰鲁', meaning: '拍照', pos: '', ex_thai: 'ขอถ่ายรูปที่นี่', ex_cn: '想在这里拍照', freq: 1 },
  { id: 'vocab-offline-299', cat: 'offline', word: 'โรงเรียน', roman: 'rong rian', zhuyin: '隆里安', meaning: '学校', pos: '', ex_thai: 'โรงเรียนนี้ใช้ถ่ายหนังหรือเปล่า', ex_cn: '这学校是用来拍戏的吗', freq: 1 },
  { id: 'vocab-offline-300', cat: 'offline', word: 'ใช้', roman: 'chai', zhuyin: '柴', meaning: '使用', pos: '', ex_thai: 'โรงเรียนนี้ใช้ถ่ายหนังหรือเปล่า', ex_cn: '这学校是用来拍戏的吗', freq: 1 },
];
