/* 活人泰语点读卡 · 追星专版 - 数据文件 */
window.APP_DATA = {
  CATEGORIES: [
    { id: 'bl', name: 'BL腐剧', icon: '💜', desc: '磕CP · 剧情 · 人设 · CP文化' },
    { id: 'gl', name: 'GL百合', icon: '💗', desc: '百合CP · 剧情 · 专属表达' },
    { id: 'star', name: '追星应援', icon: '⭐', desc: '夸赞 · 打call · 接机 · 签售' },
    { id: 'concert', name: '演唱会', icon: '🎤', desc: '买票 · 场馆 · 应援 · 打榜' },
    { id: 'social', name: '社交媒体', icon: '📱', desc: '推特 · IG · TikTok · 饭圈黑话' },
    { id: 'offline', name: '线下实用', icon: '📍', desc: '巡礼 · 周边 · 花篮 · 粉丝团' },
  ],
  SUBCATS: {
    bl: [
      { id: 'bl-cp', name: '磕CP甜言蜜语' },
      { id: 'bl-plot', name: '剧情讨论' },
      { id: 'bl-char', name: '角色人设' },
      { id: 'bl-culture', name: 'CP文化' },
      { id: 'bl-emotion', name: '情感表达' },
      { id: 'bl-behind', name: '幕后花絮' },
    ],
    gl: [
      { id: 'gl-cp', name: '磕CP表达' },
      { id: 'gl-plot', name: '剧情讨论' },
      { id: 'gl-exclusive', name: '百合专属' },
      { id: 'gl-char', name: '角色讨论' },
      { id: 'gl-emotion', name: '情感共鸣' },
      { id: 'gl-rec', name: '推荐安利' },
    ],
    star: [
      { id: 'star-praise', name: '夸赞表白' },
      { id: 'star-cheer', name: '打call应援' },
      { id: 'star-airport', name: '接机送机' },
      { id: 'star-sign', name: '签售会' },
      { id: 'star-meet', name: '粉丝见面会' },
      { id: 'star-gift', name: '送礼写信' },
    ],
    concert: [
      { id: 'concert-ticket', name: '买票取票' },
      { id: 'concert-venue', name: '场馆导航' },
      { id: 'concert-cheer', name: '应援现场' },
      { id: 'concert-chart', name: '音乐打榜' },
      { id: 'concert-merch', name: '周边购买' },
      { id: 'concert-help', name: '安保求助' },
    ],
    social: [
      { id: 'social-twitter', name: 'Twitter/X' },
      { id: 'social-ig', name: 'Instagram' },
      { id: 'social-tiktok', name: 'TikTok' },
      { id: 'social-slang', name: '饭圈黑话' },
      { id: 'social-live', name: '直播互动' },
      { id: 'social-vote', name: '超话打榜' },
    ],
    offline: [
      { id: 'offline-pilgrim', name: '圣地巡礼' },
      { id: 'offline-merch', name: '周边购买' },
      { id: 'offline-wreath', name: '应援花篮' },
      { id: 'offline-fanclub', name: '粉丝团' },
      { id: 'offline-audition', name: '选秀综艺' },
      { id: 'offline-emergency', name: '日常应急' },
    ],
  },
  SENTENCES: [
    { id: 'bl-cp-001', cat: 'bl', sub: 'bl-cp', thai: 'พวกเขาน่ารักมาก', cn: '他们好可爱' },
    { id: 'bl-cp-002', cat: 'bl', sub: 'bl-cp', thai: 'คู่นี้ล็อคแล้ว', cn: '这对锁死了' },
    { id: 'bl-cp-003', cat: 'bl', sub: 'bl-cp', thai: 'มาแต่งงานกันเถอะ', cn: '快结婚吧' },
    { id: 'bl-cp-004', cat: 'bl', sub: 'bl-cp', thai: 'หวานจัง ตายหรือเปล่า', cn: '甜死了要' },
    { id: 'bl-cp-005', cat: 'bl', sub: 'bl-cp', thai: 'เคมีดีมาก', cn: '化学反应好强' },
    { id: 'bl-cp-006', cat: 'bl', sub: 'bl-cp', thai: 'ดูแล้วยิ้มตลอด', cn: '看了全程傻笑' },
    { id: 'bl-cp-007', cat: 'bl', sub: 'bl-cp', thai: 'หัวใจละลาย', cn: '心都化了' },
    { id: 'bl-cp-008', cat: 'bl', sub: 'bl-cp', thai: 'คู่นี้ฟีดจริงๆ', cn: '这对真的在营业' },
    { id: 'bl-cp-009', cat: 'bl', sub: 'bl-cp', thai: 'มองกันแล้วใจสั่น', cn: '对视一眼就心动' },
    { id: 'bl-cp-010', cat: 'bl', sub: 'bl-cp', thai: 'ไม่ไหวแล้ว หวานเกิน', cn: '不行了太甜了' },
    { id: 'bl-cp-011', cat: 'bl', sub: 'bl-cp', thai: 'ขอให้คบกันจริงๆ นะ', cn: '希望他们真的在一起' },
    { id: 'bl-cp-012', cat: 'bl', sub: 'bl-cp', thai: 'ตาของเขามีแต่ความรัก', cn: '他眼里全是爱' },
    { id: 'bl-cp-013', cat: 'bl', sub: 'bl-cp', thai: 'จับมือกันน่ารักจัง', cn: '牵手好可爱' },
    { id: 'bl-cp-014', cat: 'bl', sub: 'bl-cp', thai: 'ยิ้มให้กันทำไมหวานงี้', cn: '互相笑得这么甜干嘛' },
    { id: 'bl-cp-015', cat: 'bl', sub: 'bl-cp', thai: 'คู่นี้คือคู่แท้', cn: '这对是真CP' },
    { id: 'bl-cp-016', cat: 'bl', sub: 'bl-cp', thai: 'อยากเห็นคู่นี้จบแบบ HE', cn: '想看这对HE结局' },
    { id: 'bl-cp-017', cat: 'bl', sub: 'bl-cp', thai: 'เขาห่วงกันมาก', cn: '他们好互相牵挂' },
    { id: 'bl-cp-018', cat: 'bl', sub: 'bl-cp', thai: 'นี่คือความรักแท้ๆ', cn: '这就是真爱' },
    { id: 'bl-cp-019', cat: 'bl', sub: 'bl-cp', thai: 'เขาดูแลกันดีมาก', cn: '他们互相照顾得很好' },
    { id: 'bl-cp-020', cat: 'bl', sub: 'bl-cp', thai: 'อยากให้เป็นคู่จริงในชีวิต', cn: '想让他们现实中也是一对' },
    { id: 'bl-cp-021', cat: 'bl', sub: 'bl-cp', thai: 'ฟินจนไม่ไหว', cn: '上头到不行' },
    { id: 'bl-cp-022', cat: 'bl', sub: 'bl-cp', thai: 'มีเคมีแบบนี้ไม่คบกันได้ไง', cn: '这化学反应不在一起行吗' },
    { id: 'bl-plot-001', cat: 'bl', sub: 'bl-plot', thai: 'ตอนที่เท่าไหร่แล้ว', cn: '更新到第几集了' },
    { id: 'bl-plot-002', cat: 'bl', sub: 'bl-plot', thai: 'ฉากนี้เด็ดสุด', cn: '这场戏绝了' },
    { id: 'bl-plot-003', cat: 'bl', sub: 'bl-plot', thai: 'จบแบบนี้คือ HE หรือ BE', cn: '这个结局是HE还是BE' },
    { id: 'bl-plot-004', cat: 'bl', sub: 'bl-plot', thai: 'ยังไม่ได้ดู อย่าสปอยล์', cn: '还没看别剧透' },
    { id: 'bl-plot-005', cat: 'bl', sub: 'bl-plot', thai: 'วันไหนออกอากาศ', cn: '哪天播出' },
    { id: 'bl-plot-006', cat: 'bl', sub: 'bl-plot', thai: 'มีกี่ตอน', cn: '一共几集' },
    { id: 'bl-plot-007', cat: 'bl', sub: 'bl-plot', thai: 'ซีซัน 2 มีไหม', cn: '有第二季吗' },
    { id: 'bl-plot-008', cat: 'bl', sub: 'bl-plot', thai: 'ตอนนี้เจ็บมาก', cn: '这集好虐' },
    { id: 'bl-plot-009', cat: 'bl', sub: 'bl-plot', thai: 'ร้องไห้ตลอดตอน', cn: '全程在哭' },
    { id: 'bl-plot-010', cat: 'bl', sub: 'bl-plot', thai: 'ฉากสุดท้ายฟินสุด', cn: '最后一场太爽了' },
    { id: 'bl-plot-011', cat: 'bl', sub: 'bl-plot', thai: 'บทนี้เขียนดีมาก', cn: '这集剧本写得好' },
    { id: 'bl-plot-012', cat: 'bl', sub: 'bl-plot', thai: 'กำลังรอตอนใหม่', cn: '在等更新' },
    { id: 'bl-plot-013', cat: 'bl', sub: 'bl-plot', thai: 'คาดหวังเยอะมาก', cn: '期待值拉满' },
    { id: 'bl-plot-014', cat: 'bl', sub: 'bl-plot', thai: 'อยากให้ต่อยาวหน่อย', cn: '想拍长一点' },
    { id: 'bl-plot-015', cat: 'bl', sub: 'bl-plot', thai: 'จบแล้วใจหาย', cn: '结束了心空了' },
    { id: 'bl-plot-016', cat: 'bl', sub: 'bl-plot', thai: 'พล็อตนี้คลาสสิค', cn: '这个剧情很经典' },
    { id: 'bl-plot-017', cat: 'bl', sub: 'bl-plot', thai: 'ชอบตอนที่เขาสารภาพรัก', cn: '喜欢表白那场戏' },
    { id: 'bl-plot-018', cat: 'bl', sub: 'bl-plot', thai: 'คาดไม่ถึงว่าจะจบแบบนี้', cn: '没想到会这样结局' },
    { id: 'bl-plot-019', cat: 'bl', sub: 'bl-plot', thai: 'ฉากนี้ดูกี่รอบก็ไม่เบื่อ', cn: '这场戏看几遍都不腻' },
    { id: 'bl-plot-020', cat: 'bl', sub: 'bl-plot', thai: 'ใครเขียนบทเนี่ย อัจฉริยะ', cn: '谁写的剧本天才' },
    { id: 'bl-plot-021', cat: 'bl', sub: 'bl-plot', thai: 'ความเร็วเรื่องดีพอดี', cn: '节奏刚好' },
    { id: 'bl-char-001', cat: 'bl', sub: 'bl-char', thai: 'เขาเป็นท็อปหรือบอท', cn: '他是攻还是受' },
    { id: 'bl-char-002', cat: 'bl', sub: 'bl-char', thai: 'น้องหมาประเภท', cn: '奶狗型' },
    { id: 'bl-char-003', cat: 'bl', sub: 'bl-char', thai: 'พี่เบ่งบางมาก', cn: '哥哥好霸气' },
    { id: 'bl-char-004', cat: 'bl', sub: 'bl-char', thai: 'คู่รุ่นพี่รุ่นน้อง', cn: '学长学弟CP' },
    { id: 'bl-char-005', cat: 'bl', sub: 'bl-char', thai: 'นิสัยเย็นชาแต่ใจดี', cn: '外冷内热型' },
    { id: 'bl-char-006', cat: 'bl', sub: 'bl-char', thai: 'ขี้อายแต่น่ารัก', cn: '害羞但可爱' },
    { id: 'bl-char-007', cat: 'bl', sub: 'bl-char', thai: 'หน้าตาเด็กแต่ทำตัวเป็นผู้ใหญ่', cn: '长得嫩但行为成熟' },
    { id: 'bl-char-008', cat: 'bl', sub: 'bl-char', thai: 'คาสาโน่ว่าไง', cn: '花花公子型' },
    { id: 'bl-char-009', cat: 'bl', sub: 'bl-char', thai: 'ซันเบาะ', cn: '阳光小狗型' },
    { id: 'bl-char-010', cat: 'bl', sub: 'bl-char', thai: 'สายเสพ้า', cn: '总裁霸总型' },
    { id: 'bl-char-011', cat: 'bl', sub: 'bl-char', thai: 'อ่อนโยนดูแลคนอื่น', cn: '温柔照顾人型' },
    { id: 'bl-char-012', cat: 'bl', sub: 'bl-char', thai: 'เย็นชาแต่ข้างในอบอุ่น', cn: '高冷但内心温暖' },
    { id: 'bl-char-013', cat: 'bl', sub: 'bl-char', thai: 'ขี้เล่นชอบแกล้ง', cn: '调皮爱逗人型' },
    { id: 'bl-char-014', cat: 'bl', sub: 'bl-char', thai: 'จริงจังกับความรัก', cn: '对感情认真型' },
    { id: 'bl-char-015', cat: 'bl', sub: 'bl-char', thai: 'หวงแหนคนรักมาก', cn: '占有欲很强' },
    { id: 'bl-char-016', cat: 'bl', sub: 'bl-char', thai: 'ยอมทุกอย่างเพื่อคนรัก', cn: '为爱人什么都愿意' },
    { id: 'bl-char-017', cat: 'bl', sub: 'bl-char', thai: 'ปากแข็งแต่ใจอ่อน', cn: '嘴硬心软' },
    { id: 'bl-char-018', cat: 'bl', sub: 'bl-char', thai: 'รอคอยคนรักตลอด', cn: '一直等待爱人' },
    { id: 'bl-char-019', cat: 'bl', sub: 'bl-char', thai: 'เสียใจแต่ทำเป็นไม่สน', cn: '难过但装不在意' },
    { id: 'bl-char-020', cat: 'bl', sub: 'bl-char', thai: 'เป็นคนเข้าอกเข้าใจ', cn: '善解人意型' },
    { id: 'bl-culture-001', cat: 'bl', sub: 'bl-culture', thai: 'คู่นี้กำลังป้อน', cn: '这对正在营业' },
    { id: 'bl-culture-002', cat: 'bl', sub: 'bl-culture', thai: 'เลิกคู่กันแล้ว', cn: '解绑了' },
    { id: 'bl-culture-003', cat: 'bl', sub: 'bl-culture', thai: 'ชื่อ CP คืออะไร', cn: 'CP名叫什么' },
    { id: 'bl-culture-004', cat: 'bl', sub: 'bl-culture', thai: 'ยังไม่เลิกคู่กัน', cn: '还没解绑' },
    { id: 'bl-culture-005', cat: 'bl', sub: 'bl-culture', thai: 'ฟีดกันตลอด', cn: '一直在营业' },
    { id: 'bl-culture-006', cat: 'bl', sub: 'bl-culture', thai: 'งานนี้ฟีดหนักมาก', cn: '这次营业好猛' },
    { id: 'bl-culture-007', cat: 'bl', sub: 'bl-culture', thai: 'แฟนคลับชิปเรือล่ม', cn: 'CP翻船了' },
    { id: 'bl-culture-008', cat: 'bl', sub: 'bl-culture', thai: 'ยังไม่มีข่าวเลิกคู่', cn: '还没解绑消息' },
    { id: 'bl-culture-009', cat: 'bl', sub: 'bl-culture', thai: 'คู่จิ้งคู่นี้ดีสุด', cn: '这对CP最好磕' },
    { id: 'bl-culture-010', cat: 'bl', sub: 'bl-culture', thai: 'คู่นี้แฟนคลับเยอะ', cn: '这对粉丝很多' },
    { id: 'bl-culture-011', cat: 'bl', sub: 'bl-culture', thai: 'มีอีเวนต์ด้วยกันไหม', cn: '有合体活动吗' },
    { id: 'bl-culture-012', cat: 'bl', sub: 'bl-culture', thai: 'อยากเห็นเขาออกงานด้วยกัน', cn: '想看合体营业' },
    { id: 'bl-culture-013', cat: 'bl', sub: 'bl-culture', thai: 'จิ้งคู่นี้มานานแล้ว', cn: '磕这对很久了' },
    { id: 'bl-culture-014', cat: 'bl', sub: 'bl-culture', thai: 'อยากให้คู่นี้กลับมาฟีด', cn: '想让这对重新营业' },
    { id: 'bl-culture-015', cat: 'bl', sub: 'bl-culture', thai: 'เรือล่มแล้ว', cn: '船翻了' },
    { id: 'bl-culture-016', cat: 'bl', sub: 'bl-culture', thai: 'ขอบคุณที่ฟีดกันมา', cn: '感谢一直营业' },
    { id: 'bl-culture-017', cat: 'bl', sub: 'bl-culture', thai: 'คู่นี้เคมีไม่เคยเปลี่ยน', cn: '化学反应从未改变' },
    { id: 'bl-culture-018', cat: 'bl', sub: 'bl-culture', thai: 'คู่นี้คือตำนาน', cn: '这对是传奇' },
    { id: 'bl-culture-019', cat: 'bl', sub: 'bl-culture', thai: 'จิ้งมาตั้งแต่เริ่ม', cn: '从一开始就在磕' },
    { id: 'bl-culture-020', cat: 'bl', sub: 'bl-culture', thai: 'ฟีดของจริง', cn: '真营业' },
    { id: 'bl-emotion-001', cat: 'bl', sub: 'bl-emotion', thai: 'ร้องไห้น้ำตาไหล', cn: '哭得眼泪直流' },
    { id: 'bl-emotion-002', cat: 'bl', sub: 'bl-emotion', thai: 'ใจสั่นมาก', cn: '心动得不行' },
    { id: 'bl-emotion-003', cat: 'bl', sub: 'bl-emotion', thai: 'หัวใจเต้นแรง', cn: '心跳加速' },
    { id: 'bl-emotion-004', cat: 'bl', sub: 'bl-emotion', thai: 'ฟินจนไม่ไหว', cn: '爽到不行' },
    { id: 'bl-emotion-005', cat: 'bl', sub: 'bl-emotion', thai: 'เสียใจแทนเขา', cn: '替他难过' },
    { id: 'bl-emotion-006', cat: 'bl', sub: 'bl-emotion', thai: 'โกรธแทนตัวละคร', cn: '替角色生气' },
    { id: 'bl-emotion-007', cat: 'bl', sub: 'bl-emotion', thai: 'น้ำตาตกให้ฉากนี้', cn: '为这场戏落泪' },
    { id: 'bl-emotion-008', cat: 'bl', sub: 'bl-emotion', thai: 'ยิ้มหัวใจละลาย', cn: '笑到心融化' },
    { id: 'bl-emotion-009', cat: 'bl', sub: 'bl-emotion', thai: 'เจ็บจนหายใจไม่ออก', cn: '虐到喘不过气' },
    { id: 'bl-emotion-010', cat: 'bl', sub: 'bl-emotion', thai: 'ดีใจจนร้องไห้', cn: '高兴到哭' },
    { id: 'bl-emotion-011', cat: 'bl', sub: 'bl-emotion', thai: 'หวานจนฟันผุ', cn: '甜到蛀牙' },
    { id: 'bl-emotion-012', cat: 'bl', sub: 'bl-emotion', thai: 'เรียกน้ำตา', cn: '催泪' },
    { id: 'bl-emotion-013', cat: 'bl', sub: 'bl-emotion', thai: 'ใจหายใจวูบ', cn: '心脏漏跳一拍' },
    { id: 'bl-emotion-014', cat: 'bl', sub: 'bl-emotion', thai: 'หลงรักเขาแล้ว', cn: '爱上他了' },
    { id: 'bl-emotion-015', cat: 'bl', sub: 'bl-emotion', thai: 'ไม่อยากให้จบเรื่อง', cn: '不想故事结束' },
    { id: 'bl-emotion-016', cat: 'bl', sub: 'bl-emotion', thai: 'คิดถึงตลอดเวลา', cn: '一直在想' },
    { id: 'bl-emotion-017', cat: 'bl', sub: 'bl-emotion', thai: 'ทนดูไม่ได้ ร้องไห้', cn: '看不下去在哭' },
    { id: 'bl-emotion-018', cat: 'bl', sub: 'bl-emotion', thai: 'มีความสุขมากที่ได้ดู', cn: '看得很开心' },
    { id: 'bl-emotion-019', cat: 'bl', sub: 'bl-emotion', thai: 'เจ็บจัง', cn: '好虐' },
    { id: 'bl-emotion-020', cat: 'bl', sub: 'bl-emotion', thai: 'หัวใจบอกว่าฟิน', cn: '心里觉得爽' },
    { id: 'bl-behind-001', cat: 'bl', sub: 'bl-behind', thai: 'มีบุพพอยไหม', cn: '有花絮吗' },
    { id: 'bl-behind-002', cat: 'bl', sub: 'bl-behind', thai: 'ดูบุพพอยแล้วหัวเราะ', cn: '看花絮笑死' },
    { id: 'bl-behind-003', cat: 'bl', sub: 'bl-behind', thai: 'เบื้องหลังน่ารักมาก', cn: '幕后好可爱' },
    { id: 'bl-behind-004', cat: 'bl', sub: 'bl-behind', thai: 'ขำกับตอนแกล้งกัน', cn: '被恶搞片段笑到' },
    { id: 'bl-behind-005', cat: 'bl', sub: 'bl-behind', thai: 'NG กันหลายรอบ', cn: 'NG了好多次' },
    { id: 'bl-behind-006', cat: 'bl', sub: 'bl-behind', thai: 'ดูเบื้องหลังแล้วรักมากขึ้น', cn: '看了幕后更喜欢了' },
    { id: 'bl-behind-007', cat: 'bl', sub: 'bl-behind', thai: 'เขาสนิทกันจริงๆ', cn: '他们真的好熟' },
    { id: 'bl-behind-008', cat: 'bl', sub: 'bl-behind', thai: 'ขำจนไม่ไหว', cn: '笑到不行' },
    { id: 'bl-behind-009', cat: 'bl', sub: 'bl-behind', thai: 'ฉากนี้ถ่ายกี่ครั้ง', cn: '这场戏拍了几次' },
    { id: 'bl-behind-010', cat: 'bl', sub: 'bl-behind', thai: 'พวกเขาล้อกันตลก', cn: '互怼好搞笑' },
    { id: 'bl-behind-011', cat: 'bl', sub: 'bl-behind', thai: 'ดูแลกันหลังกล้อง', cn: '镜头外互相照顾' },
    { id: 'bl-behind-012', cat: 'bl', sub: 'bl-behind', thai: 'บรรยากาศถ่ายทำดีมาก', cn: '拍摄氛围很好' },
    { id: 'bl-behind-013', cat: 'bl', sub: 'bl-behind', thai: 'อยากดูเบื้องหลังเพิ่ม', cn: '想看更多花絮' },
    { id: 'bl-behind-014', cat: 'bl', sub: 'bl-behind', thai: 'พวกเขาหัวเราะตลอด', cn: '他们一直在笑' },
    { id: 'bl-behind-015', cat: 'bl', sub: 'bl-behind', thai: 'กอดกันหลังกล้อง', cn: '镜头后拥抱' },
    { id: 'bl-behind-016', cat: 'bl', sub: 'bl-behind', thai: 'อินเทรนด์ตอนถ่าย', cn: '拍摄时入戏了' },
    { id: 'bl-behind-017', cat: 'bl', sub: 'bl-behind', thai: 'ขอบคุณทีมงานทุกคน', cn: '感谢所有工作人员' },
    { id: 'bl-behind-018', cat: 'bl', sub: 'bl-behind', thai: 'ทำออกมาได้ดีมาก', cn: '做得很好' },
    { id: 'bl-behind-019', cat: 'bl', sub: 'bl-behind', thai: 'เหนื่อยมากแต่สวยงาม', cn: '很累但很美' },
    { id: 'bl-behind-020', cat: 'bl', sub: 'bl-behind', thai: 'รอชมผลงานชิ้นต่อไป', cn: '期待下一部作品' },
    { id: 'gl-cp-001', cat: 'gl', sub: 'gl-cp', thai: 'พี่สาวเท่มาก', cn: '姐姐好飒' },
    { id: 'gl-cp-002', cat: 'gl', sub: 'gl-cp', thai: 'คู่นี้หวานจัง', cn: '这对好甜' },
    { id: 'gl-cp-003', cat: 'gl', sub: 'gl-cp', thai: 'อยากให้คบกันจริงๆ', cn: '好想她们真在一起' },
    { id: 'gl-cp-004', cat: 'gl', sub: 'gl-cp', thai: 'น้องสาวน่ารักมาก', cn: '妹妹好可爱' },
    { id: 'gl-cp-005', cat: 'gl', sub: 'gl-cp', thai: 'เคมีดีมาก', cn: '化学反应好强' },
    { id: 'gl-cp-006', cat: 'gl', sub: 'gl-cp', thai: 'คู่นี้ฟินสุด', cn: '这对太上头了' },
    { id: 'gl-cp-007', cat: 'gl', sub: 'gl-cp', thai: 'มองกันแล้วใจสั่น', cn: '对视就心动' },
    { id: 'gl-cp-008', cat: 'gl', sub: 'gl-cp', thai: 'ยิ้มให้กันน่ารักจัง', cn: '互笑好可爱' },
    { id: 'gl-cp-009', cat: 'gl', sub: 'gl-cp', thai: 'หัวใจละลาย', cn: '心都化了' },
    { id: 'gl-cp-010', cat: 'gl', sub: 'gl-cp', thai: 'ผู้หญิงรักกันสวยจัง', cn: '女生相爱好美' },
    { id: 'gl-cp-011', cat: 'gl', sub: 'gl-cp', thai: 'คู่นี้ล็อคแล้ว', cn: '这对锁了' },
    { id: 'gl-cp-012', cat: 'gl', sub: 'gl-cp', thai: 'ขอให้มีซีซัน 2', cn: '希望能有第二季' },
    { id: 'gl-cp-013', cat: 'gl', sub: 'gl-cp', thai: 'จับมือกันน่ารัก', cn: '牵手好可爱' },
    { id: 'gl-cp-014', cat: 'gl', sub: 'gl-cp', thai: 'ดูแลกันอบอุ่นมาก', cn: '互相照顾好温暖' },
    { id: 'gl-cp-015', cat: 'gl', sub: 'gl-cp', thai: 'ไม่ไหว หวานเกิน', cn: '不行了太甜了' },
    { id: 'gl-cp-016', cat: 'gl', sub: 'gl-cp', thai: 'ตาของเธอมีแต่ความรัก', cn: '她眼里全是爱' },
    { id: 'gl-cp-017', cat: 'gl', sub: 'gl-cp', thai: 'อยากเห็นคู่นี้จบแบบ HE', cn: '想看这对HE' },
    { id: 'gl-cp-018', cat: 'gl', sub: 'gl-cp', thai: 'คู่นี้คือของจริง', cn: '这对是真的' },
    { id: 'gl-cp-019', cat: 'gl', sub: 'gl-cp', thai: 'พี่สาวดูแลน้องดีมาก', cn: '姐姐照顾妹妹好细心' },
    { id: 'gl-cp-020', cat: 'gl', sub: 'gl-cp', thai: 'ความสัมพันธ์นี้สวยมาก', cn: '这段关系好美' },
    { id: 'gl-plot-001', cat: 'gl', sub: 'gl-plot', thai: 'ออกอากาศวันไหน', cn: '哪天播出' },
    { id: 'gl-plot-002', cat: 'gl', sub: 'gl-plot', thai: 'มีกี่ตอน', cn: '一共几集' },
    { id: 'gl-plot-003', cat: 'gl', sub: 'gl-plot', thai: 'ซีซัน 2 มีไหม', cn: '有第二季吗' },
    { id: 'gl-plot-004', cat: 'gl', sub: 'gl-plot', thai: 'ตอนใหม่ออกยัง', cn: '更新了吗' },
    { id: 'gl-plot-005', cat: 'gl', sub: 'gl-plot', thai: 'ยังไม่ได้ดู อย่าสปอยล์', cn: '还没看别剧透' },
    { id: 'gl-plot-006', cat: 'gl', sub: 'gl-plot', thai: 'ฉากนี้เด็ดสุด', cn: '这场戏绝了' },
    { id: 'gl-plot-007', cat: 'gl', sub: 'gl-plot', thai: 'พล็อตน่าสนใจมาก', cn: '剧情很吸引人' },
    { id: 'gl-plot-008', cat: 'gl', sub: 'gl-plot', thai: 'จบแบบนี้คือ HE หรือ BE', cn: '结局是HE还是BE' },
    { id: 'gl-plot-009', cat: 'gl', sub: 'gl-plot', thai: 'ความเร็วเรื่องดีพอดี', cn: '节奏刚好' },
    { id: 'gl-plot-010', cat: 'gl', sub: 'gl-plot', thai: 'ตอนนี้เจ็บมาก', cn: '这集好虐' },
    { id: 'gl-plot-011', cat: 'gl', sub: 'gl-plot', thai: 'ร้องไห้ตลอด', cn: '全程在哭' },
    { id: 'gl-plot-012', cat: 'gl', sub: 'gl-plot', thai: 'รอตอนใหม่ทุกสัปดาห์', cn: '每周等更新' },
    { id: 'gl-plot-013', cat: 'gl', sub: 'gl-plot', thai: 'คาดหวังเยอะมาก', cn: '期待值拉满' },
    { id: 'gl-plot-014', cat: 'gl', sub: 'gl-plot', thai: 'อยากให้ต่อยาว', cn: '想拍长一点' },
    { id: 'gl-plot-015', cat: 'gl', sub: 'gl-plot', thai: 'จบแล้วใจหาย', cn: '结束了心空了' },
    { id: 'gl-plot-016', cat: 'gl', sub: 'gl-plot', thai: 'บทเขียนดีมาก', cn: '剧本写得好' },
    { id: 'gl-plot-017', cat: 'gl', sub: 'gl-plot', thai: 'ชอบตอนที่สารภาพรัก', cn: '喜欢表白那场戏' },
    { id: 'gl-plot-018', cat: 'gl', sub: 'gl-plot', thai: 'คาดไม่ถึงว่าจะจบแบบนี้', cn: '没想到这样结局' },
    { id: 'gl-plot-019', cat: 'gl', sub: 'gl-plot', thai: 'ดูกี่รอบก็ไม่เบื่อ', cn: '看几遍都不腻' },
    { id: 'gl-plot-020', cat: 'gl', sub: 'gl-plot', thai: 'ใครเขียนบทเนี่ย', cn: '谁写的剧本啊' },
    { id: 'gl-exclusive-001', cat: 'gl', sub: 'gl-exclusive', thai: 'ใครเป็น T ใครเป็น P', cn: '谁T谁P' },
    { id: 'gl-exclusive-002', cat: 'gl', sub: 'gl-exclusive', thai: 'ผมสั้นสวยจัง', cn: '短发好美' },
    { id: 'gl-exclusive-003', cat: 'gl', sub: 'gl-exclusive', thai: 'หน้าตาเท่แบบทอม', cn: 'Tom风格好帅' },
    { id: 'gl-exclusive-004', cat: 'gl', sub: 'gl-exclusive', thai: 'น้องสาวน่ารักมาก', cn: '妹妹好可爱' },
    { id: 'gl-exclusive-005', cat: 'gl', sub: 'gl-exclusive', thai: 'ดูอบอุ่นมาก', cn: '看起来很温暖' },
    { id: 'gl-exclusive-006', cat: 'gl', sub: 'gl-exclusive', thai: 'ผู้หญิงเข้าใจกันได้ดีกว่า', cn: '女生更懂女生' },
    { id: 'gl-exclusive-007', cat: 'gl', sub: 'gl-exclusive', thai: 'ความรักไม่จำกัดเพศ', cn: '爱不分性别' },
    { id: 'gl-exclusive-008', cat: 'gl', sub: 'gl-exclusive', thai: 'ความสัมพันธ์นี้บริสุทธิ์', cn: '这段关系很纯粹' },
    { id: 'gl-exclusive-009', cat: 'gl', sub: 'gl-exclusive', thai: 'ทอมกับดี้', cn: 'Tom和Dee' },
    { id: 'gl-exclusive-010', cat: 'gl', sub: 'gl-exclusive', thai: 'ความรักของผู้หญิงสวยงาม', cn: '女性的爱情很美' },
    { id: 'gl-exclusive-011', cat: 'gl', sub: 'gl-exclusive', thai: 'ไม่ต้องสนใจสายตาคนอื่น', cn: '不用在意别人眼光' },
    { id: 'gl-exclusive-012', cat: 'gl', sub: 'gl-exclusive', thai: 'รักกันแบบเงียบๆ ก็ได้', cn: '安静地相爱就好' },
    { id: 'gl-exclusive-013', cat: 'gl', sub: 'gl-exclusive', thai: 'ความรักคือความรัก', cn: '爱就是爱' },
    { id: 'gl-exclusive-014', cat: 'gl', sub: 'gl-exclusive', thai: 'เธอทำให้ฉันรู้จักความรัก', cn: '她让我认识了爱' },
    { id: 'gl-exclusive-015', cat: 'gl', sub: 'gl-exclusive', thai: 'อยากเป็นเหมือนพวกเธอ', cn: '想成为像她们一样的人' },
    { id: 'gl-exclusive-016', cat: 'gl', sub: 'gl-exclusive', thai: 'กล้าหาญมากที่ออกมาเป็นตัวของตัวเอง', cn: '勇敢做自己' },
    { id: 'gl-exclusive-017', cat: 'gl', sub: 'gl-exclusive', thai: 'ความรักที่แท้จริง', cn: '真正的爱情' },
    { id: 'gl-exclusive-018', cat: 'gl', sub: 'gl-exclusive', thai: 'เธอสวยทั้งข้างนอกและข้างใน', cn: '她内外皆美' },
    { id: 'gl-char-001', cat: 'gl', sub: 'gl-char', thai: 'พี่สาวดูแลน้องดีมาก', cn: '姐姐照顾妹妹好细心' },
    { id: 'gl-char-002', cat: 'gl', sub: 'gl-char', thai: 'น้องสาวขี้อายน่ารัก', cn: '妹妹害羞好可爱' },
    { id: 'gl-char-003', cat: 'gl', sub: 'gl-char', thai: 'เธอเป็นคนเข้มแข็งแต่ใจอ่อน', cn: '外表坚强内心柔软' },
    { id: 'gl-char-004', cat: 'gl', sub: 'gl-char', thai: 'นิสัยอ่อนโยนดูแลคนอื่น', cn: '温柔体贴型' },
    { id: 'gl-char-005', cat: 'gl', sub: 'gl-char', thai: 'เย็นชาแต่ข้างในอบอุ่น', cn: '外冷内热' },
    { id: 'gl-char-006', cat: 'gl', sub: 'gl-char', thai: 'ขี้เล่นชอบแกล้ง', cn: '调皮爱逗人' },
    { id: 'gl-char-007', cat: 'gl', sub: 'gl-char', thai: 'จริงจังกับความรัก', cn: '对感情认真' },
    { id: 'gl-char-008', cat: 'gl', sub: 'gl-char', thai: 'หวงแหนคนรัก', cn: '占有欲强' },
    { id: 'gl-char-009', cat: 'gl', sub: 'gl-char', thai: 'ยอมทุกอย่างเพื่อคนรัก', cn: '为爱人什么都愿意' },
    { id: 'gl-char-010', cat: 'gl', sub: 'gl-char', thai: 'ปากแข็งแต่ใจอ่อน', cn: '嘴硬心软' },
    { id: 'gl-char-011', cat: 'gl', sub: 'gl-char', thai: 'เข้าอกเข้าใจคนอื่น', cn: '善解人意' },
    { id: 'gl-char-012', cat: 'gl', sub: 'gl-char', thai: 'เธอเก่งแต่ไม่อวด', cn: '她很厉害但不炫耀' },
    { id: 'gl-char-013', cat: 'gl', sub: 'gl-char', thai: 'ดูเด็กแต่ทำตัวเป็นผู้ใหญ่', cn: '长得嫩但行为成熟' },
    { id: 'gl-char-014', cat: 'gl', sub: 'gl-char', thai: 'เสียสละเพื่อคนรัก', cn: '为爱人牺牲' },
    { id: 'gl-char-015', cat: 'gl', sub: 'gl-char', thai: 'รอคอยคนรักตลอด', cn: '一直等待爱人' },
    { id: 'gl-char-016', cat: 'gl', sub: 'gl-char', thai: 'ซ่อนความรู้สึกไว้ข้างใน', cn: '把感情藏在心里' },
    { id: 'gl-char-017', cat: 'gl', sub: 'gl-char', thai: 'กล้าแสดงความรู้สึก', cn: '敢于表达感情' },
    { id: 'gl-char-018', cat: 'gl', sub: 'gl-char', thai: 'ขี้สงสารคนอื่น', cn: '心软善良' },
    { id: 'gl-emotion-001', cat: 'gl', sub: 'gl-emotion', thai: 'ร้องไห้กับเรื่องนี้', cn: '为这部哭了' },
    { id: 'gl-emotion-002', cat: 'gl', sub: 'gl-emotion', thai: 'ใจสั่นมาก', cn: '心动得不行' },
    { id: 'gl-emotion-003', cat: 'gl', sub: 'gl-emotion', thai: 'หัวใจเต้นแรง', cn: '心跳加速' },
    { id: 'gl-emotion-004', cat: 'gl', sub: 'gl-emotion', thai: 'ฟินจนไม่ไหว', cn: '上头到不行' },
    { id: 'gl-emotion-005', cat: 'gl', sub: 'gl-emotion', thai: 'น้ำตาไหล', cn: '眼泪流下来' },
    { id: 'gl-emotion-006', cat: 'gl', sub: 'gl-emotion', thai: 'หัวใจละลาย', cn: '心都化了' },
    { id: 'gl-emotion-007', cat: 'gl', sub: 'gl-emotion', thai: 'เจ็บจนหายใจไม่ออก', cn: '虐到喘不过气' },
    { id: 'gl-emotion-008', cat: 'gl', sub: 'gl-emotion', thai: 'ดีใจจนร้องไห้', cn: '高兴到哭' },
    { id: 'gl-emotion-009', cat: 'gl', sub: 'gl-emotion', thai: 'หวานจนฟันผุ', cn: '甜到蛀牙' },
    { id: 'gl-emotion-010', cat: 'gl', sub: 'gl-emotion', thai: 'ใจหายใจวูบ', cn: '心脏漏跳一拍' },
    { id: 'gl-emotion-011', cat: 'gl', sub: 'gl-emotion', thai: 'หลงรักเธอแล้ว', cn: '爱上她了' },
    { id: 'gl-emotion-012', cat: 'gl', sub: 'gl-emotion', thai: 'คิดถึงตลอด', cn: '一直在想' },
    { id: 'gl-emotion-013', cat: 'gl', sub: 'gl-emotion', thai: 'เรียกน้ำตา', cn: '催泪' },
    { id: 'gl-emotion-014', cat: 'gl', sub: 'gl-emotion', thai: 'ไม่อยากให้จบ', cn: '不想结束' },
    { id: 'gl-emotion-015', cat: 'gl', sub: 'gl-emotion', thai: 'เสียใจแทนเธอ', cn: '替她难过' },
    { id: 'gl-emotion-016', cat: 'gl', sub: 'gl-emotion', thai: 'โกรธแทนตัวละคร', cn: '替角色生气' },
    { id: 'gl-emotion-017', cat: 'gl', sub: 'gl-emotion', thai: 'มีความสุขมาก', cn: '很开心' },
    { id: 'gl-emotion-018', cat: 'gl', sub: 'gl-emotion', thai: 'เจ็บจัง', cn: '好虐' },
    { id: 'gl-rec-001', cat: 'gl', sub: 'gl-rec', thai: 'ดูเรื่องนี้ดีมาก', cn: '这部很好看' },
    { id: 'gl-rec-002', cat: 'gl', sub: 'gl-rec', thai: 'แนะนำเลย', cn: '推荐' },
    { id: 'gl-rec-003', cat: 'gl', sub: 'gl-rec', thai: 'ต้องดู', cn: '必看' },
    { id: 'gl-rec-004', cat: 'gl', sub: 'gl-rec', thai: 'ปลุกปลอบใจมาก', cn: '很治愈' },
    { id: 'gl-rec-005', cat: 'gl', sub: 'gl-rec', thai: 'ดูแล้วสบายใจ', cn: '看了很舒服' },
    { id: 'gl-rec-006', cat: 'gl', sub: 'gl-rec', thai: 'คุณภาพดีมาก', cn: '质量很高' },
    { id: 'gl-rec-007', cat: 'gl', sub: 'gl-rec', thai: 'นักแสดงเก่งมาก', cn: '演员演技很好' },
    { id: 'gl-rec-008', cat: 'gl', sub: 'gl-rec', thai: 'บทเขียนดี', cn: '剧本写得好' },
    { id: 'gl-rec-009', cat: 'gl', sub: 'gl-rec', thai: 'คุ้มค่าที่ดู', cn: '值得一看' },
    { id: 'gl-rec-010', cat: 'gl', sub: 'gl-rec', thai: 'อยากให้เพื่อนดูด้วย', cn: '想让朋友也看' },
    { id: 'gl-rec-011', cat: 'gl', sub: 'gl-rec', thai: 'รีวิวห้าดาว', cn: '五星好评' },
    { id: 'gl-rec-012', cat: 'gl', sub: 'gl-rec', thai: 'ดูจบในวันเดียว', cn: '一天刷完' },
    { id: 'gl-rec-013', cat: 'gl', sub: 'gl-rec', thai: 'ติดตามต่อแน่นอน', cn: '一定追' },
    { id: 'gl-rec-014', cat: 'gl', sub: 'gl-rec', thai: 'เรื่องนี้ต้องดู', cn: '这部必看' },
    { id: 'gl-rec-015', cat: 'gl', sub: 'gl-rec', thai: 'รอซีซันใหม่', cn: '等新一季' },
    { id: 'gl-rec-016', cat: 'gl', sub: 'gl-rec', thai: 'ดูซ้ำกี่รอบก็ไม่เบื่อ', cn: '看几遍都不腻' },
    { id: 'gl-rec-017', cat: 'gl', sub: 'gl-rec', thai: 'แชร์ให้เพื่อนดู', cn: '分享给朋友看' },
    { id: 'gl-rec-018', cat: 'gl', sub: 'gl-rec', thai: 'เรื่องเด็ดประจำปี', cn: '年度最佳' },
    { id: 'star-praise-001', cat: 'star', sub: 'star-praise', thai: 'หล่อมาก', cn: '好帅' },
    { id: 'star-praise-002', cat: 'star', sub: 'star-praise', thai: 'น่ารักที่สุด', cn: '最可爱了' },
    { id: 'star-praise-003', cat: 'star', sub: 'star-praise', thai: 'รักนะ', cn: '爱你' },
    { id: 'star-praise-004', cat: 'star', sub: 'star-praise', thai: 'เธอคือแสงของฉัน', cn: '你是我的光' },
    { id: 'star-praise-005', cat: 'star', sub: 'star-praise', thai: 'อยากเป็นแฟนคลับตลอดไป', cn: '想当一辈子粉丝' },
    { id: 'star-praise-006', cat: 'star', sub: 'star-praise', thai: 'หน้าตาเหมือนเทพนะ', cn: '长得像神仙' },
    { id: 'star-praise-007', cat: 'star', sub: 'star-praise', thai: 'สวยมาก', cn: '好美' },
    { id: 'star-praise-008', cat: 'star', sub: 'star-praise', thai: 'น่ารักทุกอย่าง', cn: '什么都可爱' },
    { id: 'star-praise-009', cat: 'star', sub: 'star-praise', thai: 'เก่งมากๆ', cn: '好厉害' },
    { id: 'star-praise-010', cat: 'star', sub: 'star-praise', thai: 'ไม่มีใครเท่าเธอ', cn: '没人比得上你' },
    { id: 'star-praise-011', cat: 'star', sub: 'star-praise', thai: 'ใจเธองดงาม', cn: '你的心灵很美' },
    { id: 'star-praise-012', cat: 'star', sub: 'star-praise', thai: 'เธอคือไอดอลของฉัน', cn: '你是我的偶像' },
    { id: 'star-praise-013', cat: 'star', sub: 'star-praise', thai: 'หลงรักตั้งแต่แรกเห็น', cn: '一见钟情' },
    { id: 'star-praise-014', cat: 'star', sub: 'star-praise', thai: 'ยิ้มสวยมาก', cn: '笑容好美' },
    { id: 'star-praise-015', cat: 'star', sub: 'star-praise', thai: 'เสียงดีมาก', cn: '声音好好听' },
    { id: 'star-praise-016', cat: 'star', sub: 'star-praise', thai: 'เต้นเก่งมาก', cn: '跳舞好厉害' },
    { id: 'star-praise-017', cat: 'star', sub: 'star-praise', thai: 'แสดงเก่งมาก', cn: '演技很好' },
    { id: 'star-praise-018', cat: 'star', sub: 'star-praise', thai: 'คนสมบูรณ์แบบ', cn: '完美的人' },
    { id: 'star-praise-019', cat: 'star', sub: 'star-praise', thai: 'ทำให้ฉันมีความสุข', cn: '你让我很开心' },
    { id: 'star-praise-020', cat: 'star', sub: 'star-praise', thai: 'ขอบคุณที่เกิดมา', cn: '感谢你的存在' },
    { id: 'star-praise-021', cat: 'star', sub: 'star-praise', thai: 'เธอคือแรงบันดาลใจของฉัน', cn: '你是我的动力' },
    { id: 'star-praise-022', cat: 'star', sub: 'star-praise', thai: 'รักเธอที่สุดเลย', cn: '最爱你了' },
    { id: 'star-praise-023', cat: 'star', sub: 'star-praise', thai: 'หล่อจนใจหวิว', cn: '帅到心慌' },
    { id: 'star-praise-024', cat: 'star', sub: 'star-praise', thai: 'จริงๆ ไม่มีข้อเสียเลย', cn: '真的没有缺点' },
    { id: 'star-praise-025', cat: 'star', sub: 'star-praise', thai: 'พี่คือ number one', cn: '哥哥是第一名' },
    { id: 'star-cheer-001', cat: 'star', sub: 'star-cheer', thai: 'สู้ๆ นะ', cn: '加油' },
    { id: 'star-cheer-002', cat: 'star', sub: 'star-cheer', thai: 'เรารักเธอนะ', cn: '我们爱你' },
    { id: 'star-cheer-003', cat: 'star', sub: 'star-cheer', thai: 'ไปด้วยกันตลอด', cn: '一直陪着你走' },
    { id: 'star-cheer-004', cat: 'star', sub: 'star-cheer', thai: 'ไม่มีใครเท่าเธอ', cn: '没人比得上你' },
    { id: 'star-cheer-005', cat: 'star', sub: 'star-cheer', thai: 'เธอทำได้', cn: '你能做到' },
    { id: 'star-cheer-006', cat: 'star', sub: 'star-cheer', thai: 'เชียร์เธอเสมอ', cn: '一直为你加油' },
    { id: 'star-cheer-007', cat: 'star', sub: 'star-cheer', thai: 'สู้เพื่อความฝัน', cn: '为梦想而战' },
    { id: 'star-cheer-008', cat: 'star', sub: 'star-cheer', thai: 'อย่ายอมแพ้นะ', cn: '不要放弃' },
    { id: 'star-cheer-009', cat: 'star', sub: 'star-cheer', thai: 'เราอยู่ข้างหลังเธอเสมอ', cn: '我们永远在你身后' },
    { id: 'star-cheer-010', cat: 'star', sub: 'star-cheer', thai: 'ภูมิใจในตัวเธอ', cn: '为你骄傲' },
    { id: 'star-cheer-011', cat: 'star', sub: 'star-cheer', thai: 'เธอคือดาวของเรา', cn: '你是我们的星星' },
    { id: 'star-cheer-012', cat: 'star', sub: 'star-cheer', thai: 'ทำต่อไปนะ', cn: '继续做下去' },
    { id: 'star-cheer-013', cat: 'star', sub: 'star-cheer', thai: 'เธอเก่งที่สุด', cn: '你最棒了' },
    { id: 'star-cheer-014', cat: 'star', sub: 'star-cheer', thai: 'ไม่ว่ายังไงก็สนับสนุน', cn: '不管怎样都支持你' },
    { id: 'star-cheer-015', cat: 'star', sub: 'star-cheer', thai: 'รอผลงานต่อไป', cn: '期待接下来的作品' },
    { id: 'star-cheer-016', cat: 'star', sub: 'star-cheer', thai: 'เธอคือความภูมิใจของเรา', cn: '你是我们的骄傲' },
    { id: 'star-cheer-017', cat: 'star', sub: 'star-cheer', thai: 'สู้นะพี่', cn: '加油哥哥' },
    { id: 'star-cheer-018', cat: 'star', sub: 'star-cheer', thai: 'เป็นกำลังใจให้', cn: '给你力量' },
    { id: 'star-cheer-019', cat: 'star', sub: 'star-cheer', thai: 'ทำเต็มที่นะ', cn: '全力以赴' },
    { id: 'star-cheer-020', cat: 'star', sub: 'star-cheer', thai: 'เราเชื่อในตัวเธอ', cn: '我们相信你' },
    { id: 'star-cheer-021', cat: 'star', sub: 'star-cheer', thai: 'ไปให้ถึงฝันนะ', cn: '去实现梦想吧' },
    { id: 'star-cheer-022', cat: 'star', sub: 'star-cheer', thai: 'เธอไม่ได้สู้คนเดียว', cn: '你不是一个人在战斗' },
    { id: 'star-airport-001', cat: 'star', sub: 'star-airport', thai: 'รออยู่ที่สนามบิน', cn: '在机场等' },
    { id: 'star-airport-002', cat: 'star', sub: 'star-airport', thai: 'ยินดีต้อนรับมาไทย', cn: '欢迎来泰国' },
    { id: 'star-airport-003', cat: 'star', sub: 'star-airport', thai: 'บินปลอดภัยนะ', cn: '飞行平安' },
    { id: 'star-airport-004', cat: 'star', sub: 'star-airport', thai: 'ได้เจอแล้ว คุ้มแล้ว', cn: '见到了值了' },
    { id: 'star-airport-005', cat: 'star', sub: 'star-airport', thai: 'เที่ยวบินกี่โมง', cn: '几点航班' },
    { id: 'star-airport-006', cat: 'star', sub: 'star-airport', thai: 'มารับที่สนามบิน', cn: '来机场接' },
    { id: 'star-airport-007', cat: 'star', sub: 'star-airport', thai: 'ส่งที่สนามบิน', cn: '去机场送' },
    { id: 'star-airport-008', cat: 'star', sub: 'star-airport', thai: 'กลับถึงบ้านหรือยัง', cn: '到家了吗' },
    { id: 'star-airport-009', cat: 'star', sub: 'star-airport', thai: 'เหนื่อยไหม', cn: '累吗' },
    { id: 'star-airport-010', cat: 'star', sub: 'star-airport', thai: 'พักผ่อนเยอะๆ นะ', cn: '多休息' },
    { id: 'star-airport-011', cat: 'star', sub: 'star-airport', thai: 'เดินทางดูแลตัวเองนะ', cn: '路上照顾好自己' },
    { id: 'star-airport-012', cat: 'star', sub: 'star-airport', thai: 'ขอถ่ายรูปหน่อยได้ไหม', cn: '可以拍个照吗' },
    { id: 'star-airport-013', cat: 'star', sub: 'star-airport', thai: 'ขอเซ็นให้หน่อย', cn: '可以签个名吗' },
    { id: 'star-airport-014', cat: 'star', sub: 'star-airport', thai: 'มาเที่ยวไทยอีกนะ', cn: '再来泰国玩啊' },
    { id: 'star-airport-015', cat: 'star', sub: 'star-airport', thai: 'จะคอยเธออยู่', cn: '会等你的' },
    { id: 'star-airport-016', cat: 'star', sub: 'star-airport', thai: 'คิดถึงนะ', cn: '想你' },
    { id: 'star-airport-017', cat: 'star', sub: 'star-airport', thai: 'รอวันที่ได้เจอกันอีก', cn: '期待再见面' },
    { id: 'star-airport-018', cat: 'star', sub: 'star-airport', thai: 'ขอบคุณที่มา', cn: '谢谢你的到来' },
    { id: 'star-airport-019', cat: 'star', sub: 'star-airport', thai: 'กลับไปแล้วฝันถึงกันนะ', cn: '回去后要梦到我哦' },
    { id: 'star-airport-020', cat: 'star', sub: 'star-airport', thai: 'ขอให้เดินทางราบรื่น', cn: '祝旅途顺利' },
    { id: 'star-sign-001', cat: 'star', sub: 'star-sign', thai: 'เซ็นชื่อให้หน่อยได้ไหม', cn: '可以签个名吗' },
    { id: 'star-sign-002', cat: 'star', sub: 'star-sign', thai: 'เซ็นที่นี่ได้ไหม', cn: '签在这里可以吗' },
    { id: 'star-sign-003', cat: 'star', sub: 'star-sign', thai: 'ขอเซ็นที่กระเป๋า', cn: '签在包上可以吗' },
    { id: 'star-sign-004', cat: 'star', sub: 'star-sign', thai: 'ขอบคุณมากนะ', cn: '非常感谢' },
    { id: 'star-sign-005', cat: 'star', sub: 'star-sign', thai: 'ขอเซ็นชื่อภาษาไทย', cn: '可以签泰文名字吗' },
    { id: 'star-sign-006', cat: 'star', sub: 'star-sign', thai: 'เขียนชื่ออะไรดี', cn: '写什么名字好' },
    { id: 'star-sign-007', cat: 'star', sub: 'star-sign', thai: 'เซ็นให้คนอื่นด้วยได้ไหม', cn: '可以帮别人也签一个吗' },
    { id: 'star-sign-008', cat: 'star', sub: 'star-sign', thai: 'ขอเซ็นพร้อมข้อความ', cn: '可以签带留言的吗' },
    { id: 'star-sign-009', cat: 'star', sub: 'star-sign', thai: 'เขียนว่าอะไรดี', cn: '写什么好呢' },
    { id: 'star-sign-010', cat: 'star', sub: 'star-sign', thai: 'ดีใจมากที่ได้เซ็น', cn: '很高兴能签到' },
    { id: 'star-sign-011', cat: 'star', sub: 'star-sign', thai: 'ขอถ่ายรูปตอนเซ็นได้ไหม', cn: '签的时候可以拍照吗' },
    { id: 'star-sign-012', cat: 'star', sub: 'star-sign', thai: 'รอคิวนานไหม', cn: '排队排很久吗' },
    { id: 'star-sign-013', cat: 'star', sub: 'star-sign', thai: 'ต้องซื้อของก่อนถึงเซ็นได้', cn: '需要先买东西才能签吗' },
    { id: 'star-sign-014', cat: 'star', sub: 'star-sign', thai: 'มีกี่คนในคิว', cn: '队伍有多少人' },
    { id: 'star-sign-015', cat: 'star', sub: 'star-sign', thai: 'เซ็นได้กี่ชิ้น', cn: '可以签几件' },
    { id: 'star-sign-016', cat: 'star', sub: 'star-sign', thai: 'ขอเซ็นอันนี้ด้วย', cn: '这个也签一下' },
    { id: 'star-sign-017', cat: 'star', sub: 'star-sign', thai: 'เซ็นเสร็จแล้ว', cn: '签完了' },
    { id: 'star-sign-018', cat: 'star', sub: 'star-sign', thai: 'ขอบคุณที่อุตส่าห์เซ็นให้', cn: '谢谢你签名' },
    { id: 'star-sign-019', cat: 'star', sub: 'star-sign', thai: 'จะเก็บรักษาดีๆ', cn: '会好好保管' },
    { id: 'star-sign-020', cat: 'star', sub: 'star-sign', thai: 'เป็นความทรงจำที่ดี', cn: '是美好的回忆' },
    { id: 'star-meet-001', cat: 'star', sub: 'star-meet', thai: 'ขอถ่ายรูปด้วย', cn: '可以合影吗' },
    { id: 'star-meet-002', cat: 'star', sub: 'star-meet', thai: 'ขอจับมือหน่อย', cn: '可以握个手吗' },
    { id: 'star-meet-003', cat: 'star', sub: 'star-meet', thai: 'มีคำถามจะถาม', cn: '有问题想问' },
    { id: 'star-meet-004', cat: 'star', sub: 'star-meet', thai: 'ดีใจที่ได้เจอ', cn: '很高兴见到你' },
    { id: 'star-meet-005', cat: 'star', sub: 'star-meet', thai: 'ฝันถึงวันนี้มานาน', cn: '梦到这一天很久了' },
    { id: 'star-meet-006', cat: 'star', sub: 'star-meet', thai: 'ตัวจริงหล่อกว่าในจอ', cn: '真人比屏幕上还帅' },
    { id: 'star-meet-007', cat: 'star', sub: 'star-meet', thai: 'ตัวจริงสวยกว่าในจอ', cn: '真人比屏幕上还美' },
    { id: 'star-meet-008', cat: 'star', sub: 'star-meet', thai: 'ขอบคุณที่มีกิจกรรมนี้', cn: '谢谢有这个活动' },
    { id: 'star-meet-009', cat: 'star', sub: 'star-meet', thai: 'ตั๋วแถวหน้าเลย', cn: '票在前排' },
    { id: 'star-meet-010', cat: 'star', sub: 'star-meet', thai: 'มองเห็นชัดมาก', cn: '看得很清楚' },
    { id: 'star-meet-011', cat: 'star', sub: 'star-meet', thai: 'ขอบคุณที่มาหาแฟนคลับ', cn: '谢谢来看粉丝' },
    { id: 'star-meet-012', cat: 'star', sub: 'star-meet', thai: 'ร้องเพลงให้ฟังหน่อย', cn: '唱首歌给我们听吧' },
    { id: 'star-meet-013', cat: 'star', sub: 'star-meet', thai: 'ทำใจไม่ได้ ดีใจมาก', cn: '无法平静太开心了' },
    { id: 'star-meet-014', cat: 'star', sub: 'star-meet', thai: 'วันนี้เป็นวันที่ดีที่สุด', cn: '今天是最棒的一天' },
    { id: 'star-meet-015', cat: 'star', sub: 'star-meet', thai: 'ขอกอดหน่อยได้ไหม', cn: '可以抱一下吗' },
    { id: 'star-meet-016', cat: 'star', sub: 'star-meet', thai: 'จะจำวันนี้ไปตลอดชีวิต', cn: '会记一辈子' },
    { id: 'star-meet-017', cat: 'star', sub: 'star-meet', thai: 'พี่อ่านจดหมายของฉันหรือเปล่า', cn: '哥哥看我的信了吗' },
    { id: 'star-meet-018', cat: 'star', sub: 'star-meet', thai: 'ขอให้มีกิจกรรมแบบนี้อีก', cn: '希望还有这样的活动' },
    { id: 'star-meet-019', cat: 'star', sub: 'star-meet', thai: 'แฟนคลับรักพี่นะ', cn: '粉丝爱你' },
    { id: 'star-meet-020', cat: 'star', sub: 'star-meet', thai: 'จะติดตามตลอดไป', cn: '会一直追随你' },
    { id: 'star-gift-001', cat: 'star', sub: 'star-gift', thai: 'นี่จดหมายเขียนเอง', cn: '这是我亲手写的信' },
    { id: 'star-gift-002', cat: 'star', sub: 'star-gift', thai: 'ของขวัญเล็กๆ นะ', cn: '小礼物' },
    { id: 'star-gift-003', cat: 'star', sub: 'star-gift', thai: 'อ่านแล้วร้องไห้', cn: '看了哭了' },
    { id: 'star-gift-004', cat: 'star', sub: 'star-gift', thai: 'ทำเองให้พี่เลย', cn: '亲手做给哥哥的' },
    { id: 'star-gift-005', cat: 'star', sub: 'star-gift', thai: 'หวังดีจากใจ', cn: '真心诚意' },
    { id: 'star-gift-006', cat: 'star', sub: 'star-gift', thai: 'ของขวัญไม่มีค่ามาก', cn: '礼物不贵' },
    { id: 'star-gift-007', cat: 'star', sub: 'star-gift', thai: 'แต่ทำด้วยใจ', cn: '但是用心做的' },
    { id: 'star-gift-008', cat: 'star', sub: 'star-gift', thai: 'หวังว่าพี่จะชอบ', cn: '希望哥哥喜欢' },
    { id: 'star-gift-009', cat: 'star', sub: 'star-gift', thai: 'อย่าลืมกินข้าวนะ', cn: '别忘了吃饭' },
    { id: 'star-gift-010', cat: 'star', sub: 'star-gift', thai: 'ดูแลสุขภาพด้วย', cn: '注意健康' },
    { id: 'star-gift-011', cat: 'star', sub: 'star-gift', thai: 'พักผ่อนเยอะๆ', cn: '多休息' },
    { id: 'star-gift-012', cat: 'star', sub: 'star-gift', thai: 'อย่าทำงานหนักเกินไป', cn: '别太累了' },
    { id: 'star-gift-013', cat: 'star', sub: 'star-gift', thai: 'เป็นห่วงเสมอ', cn: '一直担心你' },
    { id: 'star-gift-014', cat: 'star', sub: 'star-gift', thai: 'ขอให้มีความสุข', cn: '祝你幸福' },
    { id: 'star-gift-015', cat: 'star', sub: 'star-gift', thai: 'เลือกของขวัญให้เอง', cn: '自己挑的礼物' },
    { id: 'star-gift-016', cat: 'star', sub: 'star-gift', thai: 'พี่ชอบไหม', cn: '哥哥喜欢吗' },
    { id: 'star-gift-017', cat: 'star', sub: 'star-gift', thai: 'ห่วงใยจากใจ', cn: '真心的关怀' },
    { id: 'star-gift-018', cat: 'star', sub: 'star-gift', thai: 'ฝากไว้ข้างหลังเวที', cn: '放在后台了' },
    { id: 'star-gift-019', cat: 'star', sub: 'star-gift', thai: 'ได้รับแล้วหรือเปล่า', cn: '收到了吗' },
    { id: 'star-gift-020', cat: 'star', sub: 'star-gift', thai: 'เก็บไว้เป็นที่ระลึกนะ', cn: '留作纪念' },
    { id: 'concert-ticket-001', cat: 'concert', sub: 'concert-ticket', thai: 'ซื้อตั๋วออนไลน์ที่ไหน', cn: '网上在哪买票' },
    { id: 'concert-ticket-002', cat: 'concert', sub: 'concert-ticket', thai: 'ที่นั่งโซนอะไร', cn: '哪个区的座位' },
    { id: 'concert-ticket-003', cat: 'concert', sub: 'concert-ticket', thai: 'รับตั๋วที่ไหน', cn: '在哪取票' },
    { id: 'concert-ticket-004', cat: 'concert', sub: 'concert-ticket', thai: 'ตั๋วหมดแล้ว', cn: '票卖完了' },
    { id: 'concert-ticket-005', cat: 'concert', sub: 'concert-ticket', thai: 'ยังมีตั๋วเหลือไหม', cn: '还有票吗' },
    { id: 'concert-ticket-006', cat: 'concert', sub: 'concert-ticket', thai: 'ตั๋วราคาเท่าไหร่', cn: '票多少钱' },
    { id: 'concert-ticket-007', cat: 'concert', sub: 'concert-ticket', thai: 'ซื้อตั๋ว VIP ได้ไหม', cn: '可以买VIP票吗' },
    { id: 'concert-ticket-008', cat: 'concert', sub: 'concert-ticket', thai: 'ที่นั่งแถวหน้า', cn: '前排座位' },
    { id: 'concert-ticket-009', cat: 'concert', sub: 'concert-ticket', thai: 'ที่นั่งแถวหลัง', cn: '后排座位' },
    { id: 'concert-ticket-010', cat: 'concert', sub: 'concert-ticket', thai: 'คอนเสิร์ตกี่โมงเริ่ม', cn: '演唱会几点开始' },
    { id: 'concert-ticket-011', cat: 'concert', sub: 'concert-ticket', thai: 'ประตูเปิดกี่โมง', cn: '几点开门' },
    { id: 'concert-ticket-012', cat: 'concert', sub: 'concert-ticket', thai: 'ต้องมาก่อนกี่โมง', cn: '需要提前几小时来' },
    { id: 'concert-ticket-013', cat: 'concert', sub: 'concert-ticket', thai: 'ตั๋วหมดเร็วมาก', cn: '票卖得很快' },
    { id: 'concert-ticket-014', cat: 'concert', sub: 'concert-ticket', thai: 'แล้วแต่โชค', cn: '看运气' },
    { id: 'concert-ticket-015', cat: 'concert', sub: 'concert-ticket', thai: 'ซื้อตั๋ว resell ได้ไหม', cn: '可以买转让票吗' },
    { id: 'concert-ticket-016', cat: 'concert', sub: 'concert-ticket', thai: 'ต้องโชว์บัตรประชาชนไหม', cn: '需要出示身份证吗' },
    { id: 'concert-ticket-017', cat: 'concert', sub: 'concert-ticket', thai: 'ตั๋วส่งทางไปรษณีย์ไหม', cn: '票邮寄吗' },
    { id: 'concert-ticket-018', cat: 'concert', sub: 'concert-ticket', thai: 'ตั๋ว e-ticket ใช้ได้ไหม', cn: '电子票可以吗' },
    { id: 'concert-ticket-019', cat: 'concert', sub: 'concert-ticket', thai: 'คอนเสิร์ตอยู่ที่ไหน', cn: '演唱会在哪' },
    { id: 'concert-ticket-020', cat: 'concert', sub: 'concert-ticket', thai: 'มีคอนเสิร์ตวันไหนบ้าง', cn: '有哪几场' },
    { id: 'concert-venue-001', cat: 'concert', sub: 'concert-venue', thai: 'ทางเข้าอยู่ไหน', cn: '入口在哪' },
    { id: 'concert-venue-002', cat: 'concert', sub: 'concert-venue', thai: 'ห้องน้ำอยู่ไหน', cn: '洗手间在哪' },
    { id: 'concert-venue-003', cat: 'concert', sub: 'concert-venue', thai: 'ที่นั่งฉันอยู่ไกลไหม', cn: '我的座位远吗' },
    { id: 'concert-venue-004', cat: 'concert', sub: 'concert-venue', thai: 'เดินทางยังไง', cn: '怎么走' },
    { id: 'concert-venue-005', cat: 'concert', sub: 'concert-venue', thai: 'ลิฟต์อยู่ไหน', cn: '电梯在哪' },
    { id: 'concert-venue-006', cat: 'concert', sub: 'concert-venue', thai: 'บันไดอยู่ไหน', cn: '楼梯在哪' },
    { id: 'concert-venue-007', cat: 'concert', sub: 'concert-venue', thai: 'ทางออกฉุกเฉินอยู่ไหน', cn: '紧急出口在哪' },
    { id: 'concert-venue-008', cat: 'concert', sub: 'concert-venue', thai: 'มีที่นั่งพักไหม', cn: '有休息区吗' },
    { id: 'concert-venue-009', cat: 'concert', sub: 'concert-venue', thai: 'ร้านค้าอยู่ไหน', cn: '商店在哪' },
    { id: 'concert-venue-010', cat: 'concert', sub: 'concert-venue', thai: 'ที่จอดรถอยู่ไหน', cn: '停车场在哪' },
    { id: 'concert-venue-011', cat: 'concert', sub: 'concert-venue', thai: 'ที่นั่งหมายเลขกี่', cn: '座位号多少' },
    { id: 'concert-venue-012', cat: 'concert', sub: 'concert-venue', thai: 'โซนนี้ถูกไหม', cn: '这个区对吗' },
    { id: 'concert-venue-013', cat: 'concert', sub: 'concert-venue', thai: 'ตรงไปแล้วเลี้ยวขวา', cn: '直走然后右转' },
    { id: 'concert-venue-014', cat: 'concert', sub: 'concert-venue', thai: 'อยู่ชั้นกี่', cn: '在几楼' },
    { id: 'concert-venue-015', cat: 'concert', sub: 'concert-venue', thai: 'ขึ้นบันไดเลื่อน', cn: '坐扶梯上去' },
    { id: 'concert-venue-016', cat: 'concert', sub: 'concert-venue', thai: 'มีร้านขายของกินไหม', cn: '有卖吃的吗' },
    { id: 'concert-venue-017', cat: 'concert', sub: 'concert-venue', thai: 'น้ำดื่มซื้อได้ที่ไหน', cn: '在哪买水' },
    { id: 'concert-venue-018', cat: 'concert', sub: 'concert-venue', thai: 'เข้ามาได้กี่คน', cn: '可以进几个人' },
    { id: 'concert-venue-019', cat: 'concert', sub: 'concert-venue', thai: 'ทางออกอยู่ด้านไหน', cn: '出口在哪边' },
    { id: 'concert-venue-020', cat: 'concert', sub: 'concert-venue', thai: 'ใกล้จะถึงที่นั่งแล้ว', cn: '快到座位了' },
    { id: 'concert-cheer-001', cat: 'concert', sub: 'concert-cheer', thai: 'เปิดไฟฉายเลย', cn: '打开应援灯' },
    { id: 'concert-cheer-002', cat: 'concert', sub: 'concert-cheer', thai: 'ตะโกนตามฉัน', cn: '跟我喊' },
    { id: 'concert-cheer-003', cat: 'concert', sub: 'concert-cheer', thai: 'สีอะไร', cn: '应援色是什么' },
    { id: 'concert-cheer-004', cat: 'concert', sub: 'concert-cheer', thai: 'เพลงนี้', cn: '这首歌' },
    { id: 'concert-cheer-005', cat: 'concert', sub: 'concert-cheer', thai: 'ร้องตามกัน', cn: '一起唱' },
    { id: 'concert-cheer-006', cat: 'concert', sub: 'concert-cheer', thai: 'กระโดดสิ', cn: '跳起来' },
    { id: 'concert-cheer-007', cat: 'concert', sub: 'concert-cheer', thai: 'ขยับมาข้างหน้า', cn: '往前挪' },
    { id: 'concert-cheer-008', cat: 'concert', sub: 'concert-cheer', thai: 'ยกป้ายขึ้น', cn: '举起手幅' },
    { id: 'concert-cheer-009', cat: 'concert', sub: 'concert-cheer', thai: 'แฟนไลท์สีอะไร', cn: '应援棒什么颜色' },
    { id: 'concert-cheer-010', cat: 'concert', sub: 'concert-cheer', thai: 'เปลี่ยนสีแล้ว', cn: '换颜色了' },
    { id: 'concert-cheer-011', cat: 'concert', sub: 'concert-cheer', thai: 'ส่งเสียงดังๆ', cn: '大声喊' },
    { id: 'concert-cheer-012', cat: 'concert', sub: 'concert-cheer', thai: 'ฮึกเหิมมาก', cn: '气氛好燃' },
    { id: 'concert-cheer-013', cat: 'concert', sub: 'concert-cheer', thai: 'คอนเสิร์ตสุดยอด', cn: '演唱会太棒了' },
    { id: 'concert-cheer-014', cat: 'concert', sub: 'concert-cheer', thai: 'เสียงดนตรีดังมาก', cn: '音乐声好大' },
    { id: 'concert-cheer-015', cat: 'concert', sub: 'concert-cheer', thai: 'เห็นชัดมาก', cn: '看得很清楚' },
    { id: 'concert-cheer-016', cat: 'concert', sub: 'concert-cheer', thai: 'ขอแอนคอร์', cn: '安可安可' },
    { id: 'concert-cheer-017', cat: 'concert', sub: 'concert-cheer', thai: 'อีกเพลงนะ', cn: '再来一首' },
    { id: 'concert-cheer-018', cat: 'concert', sub: 'concert-cheer', thai: 'ไม่อยากให้จบ', cn: '不想结束' },
    { id: 'concert-cheer-019', cat: 'concert', sub: 'concert-cheer', thai: 'คุ้มค่ามาก', cn: '太值了' },
    { id: 'concert-cheer-020', cat: 'concert', sub: 'concert-cheer', thai: 'ขอบคุณสำหรับคอนเสิร์ต', cn: '感谢这场演唱会' },
    { id: 'concert-chart-001', cat: 'concert', sub: 'concert-chart', thai: 'ช่วยฟังเพลงนี้', cn: '请听这首歌' },
    { id: 'concert-chart-002', cat: 'concert', sub: 'concert-chart', thai: 'สตรีมมากขึ้น', cn: '多刷刷播放' },
    { id: 'concert-chart-003', cat: 'concert', sub: 'concert-chart', thai: 'กดไลค์ด้วย', cn: '点个赞' },
    { id: 'concert-chart-004', cat: 'concert', sub: 'concert-chart', thai: 'แชร์ให้หน่อย', cn: '帮分享' },
    { id: 'concert-chart-005', cat: 'concert', sub: 'concert-chart', thai: 'โหวตให้หน่อย', cn: '帮投票' },
    { id: 'concert-chart-006', cat: 'concert', sub: 'concert-chart', thai: 'เพลงขึ้นอันดับแล้ว', cn: '歌曲上榜了' },
    { id: 'concert-chart-007', cat: 'concert', sub: 'concert-chart', thai: 'อันดับ 1 แล้ว', cn: '第一了' },
    { id: 'concert-chart-008', cat: 'concert', sub: 'concert-chart', thai: 'สู้ๆ นะ', cn: '加油' },
    { id: 'concert-chart-009', cat: 'concert', sub: 'concert-chart', thai: 'ขอให้ขึ้นอันดับ 1', cn: '希望能上第一' },
    { id: 'concert-chart-010', cat: 'concert', sub: 'concert-chart', thai: 'ทำได้ดีมาก', cn: '做得很好' },
    { id: 'concert-chart-011', cat: 'concert', sub: 'concert-chart', thai: 'เก่งมาก', cn: '太厉害了' },
    { id: 'concert-chart-012', cat: 'concert', sub: 'concert-chart', thai: 'เพลงเพราะมาก', cn: '歌很好听' },
    { id: 'concert-chart-013', cat: 'concert', sub: 'concert-chart', thai: 'เล่นซ้ำ', cn: '单曲循环' },
    { id: 'concert-chart-014', cat: 'concert', sub: 'concert-chart', thai: 'ดาวน์โหลดเพลง', cn: '下载歌曲' },
    { id: 'concert-chart-015', cat: 'concert', sub: 'concert-chart', thai: 'เพิ่มในเพลย์ลิสต์', cn: '加入歌单' },
    { id: 'concert-chart-016', cat: 'concert', sub: 'concert-chart', thai: 'แนะนำเพลงนี้', cn: '推荐这首歌' },
    { id: 'concert-chart-017', cat: 'concert', sub: 'concert-chart', thai: 'เพลงใหม่ออกแล้ว', cn: '新歌发了' },
    { id: 'concert-chart-018', cat: 'concert', sub: 'concert-chart', thai: 'รอฟังเพลงใหม่', cn: '等新歌' },
    { id: 'concert-chart-019', cat: 'concert', sub: 'concert-chart', thai: 'ยอดวิวเยอะขึ้น', cn: '播放量涨了' },
    { id: 'concert-chart-020', cat: 'concert', sub: 'concert-chart', thai: 'ขอบคุณแฟนคลับ', cn: '感谢粉丝' },
    { id: 'concert-merch-001', cat: 'concert', sub: 'concert-merch', thai: 'ของใช้ลิมิเต็ดมีไหม', cn: '有限量周边吗' },
    { id: 'concert-merch-002', cat: 'concert', sub: 'concert-merch', thai: 'ราคาเท่าไหร่', cn: '多少钱' },
    { id: 'concert-merch-003', cat: 'concert', sub: 'concert-merch', thai: 'มีสต็อกไหม', cn: '有库存吗' },
    { id: 'concert-merch-004', cat: 'concert', sub: 'concert-merch', thai: 'ซื้อออนไลน์ได้ไหม', cn: '可以网购吗' },
    { id: 'concert-merch-005', cat: 'concert', sub: 'concert-merch', thai: 'ของหมดแล้ว', cn: '卖完了' },
    { id: 'concert-merch-006', cat: 'concert', sub: 'concert-merch', thai: 'มีส่วนลดไหม', cn: '有折扣吗' },
    { id: 'concert-merch-007', cat: 'concert', sub: 'concert-merch', thai: 'ของแถมมีไหม', cn: '有赠品吗' },
    { id: 'concert-merch-008', cat: 'concert', sub: 'concert-merch', thai: 'ซื้อกี่ชิ้น', cn: '买几件' },
    { id: 'concert-merch-009', cat: 'concert', sub: 'concert-merch', thai: 'สีอะไรมีบ้าง', cn: '有什么颜色' },
    { id: 'concert-merch-010', cat: 'concert', sub: 'concert-merch', thai: 'มีไซส์ไหนบ้าง', cn: '有什么尺码' },
    { id: 'concert-merch-011', cat: 'concert', sub: 'concert-merch', thai: 'ขอลองได้ไหม', cn: '可以试吗' },
    { id: 'concert-merch-012', cat: 'concert', sub: 'concert-merch', thai: 'แพงเกินไป', cn: '太贵了' },
    { id: 'concert-merch-013', cat: 'concert', sub: 'concert-merch', thai: 'ถูกกว่านี้ไหม', cn: '有便宜点的吗' },
    { id: 'concert-merch-014', cat: 'concert', sub: 'concert-merch', thai: 'ขอเช็กราคาก่อน', cn: '我先看看价格' },
    { id: 'concert-merch-015', cat: 'concert', sub: 'concert-merch', thai: 'ซื้อแล้ว', cn: '买了' },
    { id: 'concert-merch-016', cat: 'concert', sub: 'concert-merch', thai: 'ขอสีกัน', cn: '要这个颜色' },
    { id: 'concert-merch-017', cat: 'concert', sub: 'concert-merch', thai: 'มีแพ็คเกจไหม', cn: '有套餐吗' },
    { id: 'concert-merch-018', cat: 'concert', sub: 'concert-merch', thai: 'จองล่วงหน้าได้ไหม', cn: '可以预订吗' },
    { id: 'concert-merch-019', cat: 'concert', sub: 'concert-merch', thai: 'ส่งของเมื่อไหร่', cn: '什么时候发货' },
    { id: 'concert-merch-020', cat: 'concert', sub: 'concert-merch', thai: 'ค่าส่งเท่าไหร่', cn: '运费多少' },
    { id: 'concert-help-001', cat: 'concert', sub: 'concert-help', thai: 'ช่วยด้วย', cn: '救命' },
    { id: 'concert-help-002', cat: 'concert', sub: 'concert-help', thai: 'เจ็บขา', cn: '腿受伤了' },
    { id: 'concert-help-003', cat: 'concert', sub: 'concert-help', thai: 'รู้สึกไม่สบาย', cn: '不舒服' },
    { id: 'concert-help-004', cat: 'concert', sub: 'concert-help', thai: 'มีใครเบียดมาก', cn: '有人挤' },
    { id: 'concert-help-005', cat: 'concert', sub: 'concert-help', thai: 'ต้องการเจ้าหน้าที่', cn: '需要工作人员' },
    { id: 'concert-help-006', cat: 'concert', sub: 'concert-help', thai: 'ทางออกฉุกเฉินอยู่ไหน', cn: '紧急出口在哪' },
    { id: 'concert-help-007', cat: 'concert', sub: 'concert-help', thai: 'มีห้องพยาบาลไหม', cn: '有医务室吗' },
    { id: 'concert-help-008', cat: 'concert', sub: 'concert-help', thai: 'หายใจไม่ออก', cn: '呼吸困难' },
    { id: 'concert-help-009', cat: 'concert', sub: 'concert-help', thai: 'ขอน้ำหน่อย', cn: '请给点水' },
    { id: 'concert-help-010', cat: 'concert', sub: 'concert-help', thai: 'หาเพื่อนไม่เจอ', cn: '找不到朋友' },
    { id: 'concert-help-011', cat: 'concert', sub: 'concert-help', thai: 'โทรศัพท์หาย', cn: '手机丢了' },
    { id: 'concert-help-012', cat: 'concert', sub: 'concert-help', thai: 'กระเป๋าหาย', cn: '包丢了' },
    { id: 'concert-help-013', cat: 'concert', sub: 'concert-help', thai: 'ที่ไหนมีแอร์', cn: '哪里有空调' },
    { id: 'concert-help-014', cat: 'concert', sub: 'concert-help', thai: 'ร้อนมาก', cn: '好热' },
    { id: 'concert-help-015', cat: 'concert', sub: 'concert-help', thai: 'เวียนหัว', cn: '头晕' },
    { id: 'concert-help-016', cat: 'concert', sub: 'concert-help', thai: 'ขอนั่งพักหน่อย', cn: '想坐下来休息' },
    { id: 'concert-help-017', cat: 'concert', sub: 'concert-help', thai: 'พาไปทางออก', cn: '带我去出口' },
    { id: 'concert-help-018', cat: 'concert', sub: 'concert-help', thai: 'ขอโทรศัพท์ยืมหน่อย', cn: '借个电话' },
    { id: 'concert-help-019', cat: 'concert', sub: 'concert-help', thai: 'ขอให้เจ้าหน้าที่มา', cn: '请叫工作人员来' },
    { id: 'concert-help-020', cat: 'concert', sub: 'concert-help', thai: 'ขอบคุณมาก', cn: '非常感谢' },
    { id: 'social-twitter-001', cat: 'social', sub: 'social-twitter', thai: 'รีโพสต์ด้วยนะ', cn: '请转发' },
    { id: 'social-twitter-002', cat: 'social', sub: 'social-twitter', thai: 'แท็กหน่อย', cn: 'tag一下' },
    { id: 'social-twitter-003', cat: 'social', sub: 'social-twitter', thai: 'เทรนด์อันดับ 1', cn: '趋势第一' },
    { id: 'social-twitter-004', cat: 'social', sub: 'social-twitter', thai: 'โหวตให้หน่อย', cn: '帮投个票' },
    { id: 'social-twitter-005', cat: 'social', sub: 'social-twitter', thai: 'ชื่อแฮชแท็กอะไร', cn: '话题标签是什么' },
    { id: 'social-twitter-006', cat: 'social', sub: 'social-twitter', thai: 'แชร์โพสต์นี้', cn: '分享这条' },
    { id: 'social-twitter-007', cat: 'social', sub: 'social-twitter', thai: 'คอมเมนต์ด้วย', cn: '也评论一下' },
    { id: 'social-twitter-008', cat: 'social', sub: 'social-twitter', thai: 'เทรนด์อะไร', cn: '什么趋势' },
    { id: 'social-twitter-009', cat: 'social', sub: 'social-twitter', thai: 'ติดเทรนด์แล้ว', cn: '上趋势了' },
    { id: 'social-twitter-010', cat: 'social', sub: 'social-twitter', thai: 'โพสต์ล่าสุด', cn: '最新推文' },
    { id: 'social-twitter-011', cat: 'social', sub: 'social-twitter', thai: 'ฟอลลอว์กลับด้วย', cn: '求回关' },
    { id: 'social-twitter-012', cat: 'social', sub: 'social-twitter', thai: 'มีข่าวใหม่ไหม', cn: '有新消息吗' },
    { id: 'social-twitter-013', cat: 'social', sub: 'social-twitter', thai: 'เรทวิตให้แล้ว', cn: '已经转推了' },
    { id: 'social-twitter-014', cat: 'social', sub: 'social-twitter', thai: 'โปรไฟล์อัปเดตแล้ว', cn: '主页更新了' },
    { id: 'social-twitter-015', cat: 'social', sub: 'social-twitter', thai: 'ขอคอมเมนต์ดีๆ', cn: '求好评' },
    { id: 'social-twitter-016', cat: 'social', sub: 'social-twitter', thai: 'ช่วยกันเทรนด์', cn: '一起冲趋势' },
    { id: 'social-twitter-017', cat: 'social', sub: 'social-twitter', thai: 'กดถูกใจด้วย', cn: '也点赞' },
    { id: 'social-twitter-018', cat: 'social', sub: 'social-twitter', thai: 'อย่าลืมแท็ก', cn: '别忘了tag' },
    { id: 'social-twitter-019', cat: 'social', sub: 'social-twitter', thai: 'โพสต์ภาพนี้', cn: '发这张图' },
    { id: 'social-twitter-020', cat: 'social', sub: 'social-twitter', thai: 'บัญชีทวิตเตอร์คืออะไร', cn: '推特账号是什么' },
    { id: 'social-ig-001', cat: 'social', sub: 'social-ig', thai: 'สวยมาก', cn: '好美' },
    { id: 'social-ig-002', cat: 'social', sub: 'social-ig', thai: 'ขอฟอลล์กลับ', cn: '求回粉' },
    { id: 'social-ig-003', cat: 'social', sub: 'social-ig', thai: 'อัปเดทบ่อยๆ นะ', cn: '多更新哦' },
    { id: 'social-ig-004', cat: 'social', sub: 'social-ig', thai: 'เซลฟี่นี้ดีจัง', cn: '这自拍绝了' },
    { id: 'social-ig-005', cat: 'social', sub: 'social-ig', thai: 'ถ่ายภาพสวยมาก', cn: '拍得好好看' },
    { id: 'social-ig-006', cat: 'social', sub: 'social-ig', thai: 'ฟิลเตอร์อะไร', cn: '什么滤镜' },
    { id: 'social-ig-007', cat: 'social', sub: 'social-ig', thai: 'แต่งตัวสวยจัง', cn: '穿搭好美' },
    { id: 'social-ig-008', cat: 'social', sub: 'social-ig', thai: 'เสื้อผ้ายี่ห้ออะไร', cn: '衣服什么牌子' },
    { id: 'social-ig-009', cat: 'social', sub: 'social-ig', thai: 'ถ่ายที่ไหน', cn: '在哪拍的' },
    { id: 'social-ig-010', cat: 'social', sub: 'social-ig', thai: 'วิวสวยมาก', cn: '风景好美' },
    { id: 'social-ig-011', cat: 'social', sub: 'social-ig', thai: 'โพสต์ใหม่', cn: '新帖' },
    { id: 'social-ig-012', cat: 'social', sub: 'social-ig', thai: 'รอโพสต์ใหม่', cn: '等新帖' },
    { id: 'social-ig-013', cat: 'social', sub: 'social-ig', thai: 'สตอรี่น่ารัก', cn: 'story好可爱' },
    { id: 'social-ig-014', cat: 'social', sub: 'social-ig', thai: 'ขอสตอรี่เพิ่ม', cn: '多发story' },
    { id: 'social-ig-015', cat: 'social', sub: 'social-ig', thai: 'รีลดีมาก', cn: 'Reel很好看' },
    { id: 'social-ig-016', cat: 'social', sub: 'social-ig', thai: 'กดเซฟแล้ว', cn: '已收藏' },
    { id: 'social-ig-017', cat: 'social', sub: 'social-ig', thai: 'แชร์ให้เพื่อนดู', cn: '分享给朋友看' },
    { id: 'social-ig-018', cat: 'social', sub: 'social-ig', thai: 'คอมเมนต์แล้วนะ', cn: '已评论' },
    { id: 'social-ig-019', cat: 'social', sub: 'social-ig', thai: 'ไลค์แล้ว', cn: '已点赞' },
    { id: 'social-ig-020', cat: 'social', sub: 'social-ig', thai: 'บัญชี IG คืออะไร', cn: 'IG账号是什么' },
    { id: 'social-tiktok-001', cat: 'social', sub: 'social-tiktok', thai: 'ยอดวิวเยอะจัง', cn: '播放量好高' },
    { id: 'social-tiktok-002', cat: 'social', sub: 'social-tiktok', thai: 'ขอดูแดนซ์อีก', cn: '想再看舞蹈' },
    { id: 'social-tiktok-003', cat: 'social', sub: 'social-tiktok', thai: 'ติดเทรนด์เลย', cn: '上热门了' },
    { id: 'social-tiktok-004', cat: 'social', sub: 'social-tiktok', thai: 'เพลงนี้เพราะ', cn: '这首歌好听' },
    { id: 'social-tiktok-005', cat: 'social', sub: 'social-tiktok', thai: 'ขอทำชาเลนจ์', cn: '想做挑战' },
    { id: 'social-tiktok-006', cat: 'social', sub: 'social-tiktok', thai: 'วิดีโอติดเทรนด์', cn: '视频上热门了' },
    { id: 'social-tiktok-007', cat: 'social', sub: 'social-tiktok', thai: 'ขอวิดีโอใหม่', cn: '想要新视频' },
    { id: 'social-tiktok-008', cat: 'social', sub: 'social-tiktok', thai: 'ฟอลลอว์แล้ว', cn: '已关注' },
    { id: 'social-tiktok-009', cat: 'social', sub: 'social-tiktok', thai: 'แชร์วิดีโอ', cn: '分享视频' },
    { id: 'social-tiktok-010', cat: 'social', sub: 'social-tiktok', thai: 'คอมเมนต์ว่าดีมาก', cn: '评论说很好' },
    { id: 'social-tiktok-011', cat: 'social', sub: 'social-tiktok', thai: 'โพสต์วิดีโอใหม่เร็วๆ', cn: '快发新视频' },
    { id: 'social-tiktok-012', cat: 'social', sub: 'social-tiktok', thai: 'คลิปเด็ด', cn: '爆款视频' },
    { id: 'social-tiktok-013', cat: 'social', sub: 'social-tiktok', thai: 'คอมเมนต์กันเยอะๆ', cn: '多评论' },
    { id: 'social-tiktok-014', cat: 'social', sub: 'social-tiktok', thai: 'ไลค์เยอะมาก', cn: '点赞很多' },
    { id: 'social-tiktok-015', cat: 'social', sub: 'social-tiktok', thai: 'ขอลิงก์เพลง', cn: '求歌曲链接' },
    { id: 'social-tiktok-016', cat: 'social', sub: 'social-tiktok', thai: 'เก่งมาก', cn: '太厉害了' },
    { id: 'social-tiktok-017', cat: 'social', sub: 'social-tiktok', thai: 'น่ารักมาก', cn: '好可爱' },
    { id: 'social-tiktok-018', cat: 'social', sub: 'social-tiktok', thai: 'ทำเพิ่มนะ', cn: '多做几个' },
    { id: 'social-tiktok-019', cat: 'social', sub: 'social-tiktok', thai: 'ซีรีส์นี้ดี', cn: '这个系列好' },
    { id: 'social-tiktok-020', cat: 'social', sub: 'social-tiktok', thai: 'บัญชี TikTok คืออะไร', cn: 'TikTok账号是什么' },
    { id: 'social-slang-001', cat: 'social', sub: 'social-slang', thai: 'ฟีด', cn: '营业' },
    { id: 'social-slang-002', cat: 'social', sub: 'social-slang', thai: 'ชิป', cn: '磕' },
    { id: 'social-slang-003', cat: 'social', sub: 'social-slang', thai: 'บอยเลิฟ', cn: 'BL' },
    { id: 'social-slang-004', cat: 'social', sub: 'social-slang', thai: 'ยอดขาย', cn: '销量' },
    { id: 'social-slang-005', cat: 'social', sub: 'social-slang', thai: 'สตรีม', cn: '刷播放量' },
    { id: 'social-slang-006', cat: 'social', sub: 'social-slang', thai: 'ล็อค', cn: '锁了' },
    { id: 'social-slang-007', cat: 'social', sub: 'social-slang', thai: 'ฟิน', cn: '爽/上头' },
    { id: 'social-slang-008', cat: 'social', sub: 'social-slang', thai: 'เจ็บ', cn: '虐' },
    { id: 'social-slang-009', cat: 'social', sub: 'social-slang', thai: 'หวาน', cn: '甜' },
    { id: 'social-slang-010', cat: 'social', sub: 'social-slang', thai: 'คู่จิ้ง', cn: '磕的CP' },
    { id: 'social-slang-011', cat: 'social', sub: 'social-slang', thai: 'เคมี', cn: '化学反应' },
    { id: 'social-slang-012', cat: 'social', sub: 'social-slang', thai: 'ท็อป', cn: '攻' },
    { id: 'social-slang-013', cat: 'social', sub: 'social-slang', thai: 'บอท', cn: '受' },
    { id: 'social-slang-014', cat: 'social', sub: 'social-slang', thai: 'เรือล่ม', cn: '船翻' },
    { id: 'social-slang-015', cat: 'social', sub: 'social-slang', thai: 'สปอยล์', cn: '剧透' },
    { id: 'social-slang-016', cat: 'social', sub: 'social-slang', thai: 'HE', cn: '好结局' },
    { id: 'social-slang-017', cat: 'social', sub: 'social-slang', thai: 'BE', cn: '坏结局' },
    { id: 'social-slang-018', cat: 'social', sub: 'social-slang', thai: 'แฟนคลับ', cn: '粉丝' },
    { id: 'social-slang-019', cat: 'social', sub: 'social-slang', thai: 'ไอดอล', cn: '偶像' },
    { id: 'social-slang-020', cat: 'social', sub: 'social-slang', thai: 'คัมแบ็ก', cn: '回归' },
    { id: 'social-live-001', cat: 'social', sub: 'social-live', thai: 'มีไลฟ์ไลฟ์ไหม', cn: '有直播吗' },
    { id: 'social-live-002', cat: 'social', sub: 'social-live', thai: 'กดติดตามไว้', cn: '点关注' },
    { id: 'social-live-003', cat: 'social', sub: 'social-live', thai: 'ส่งของขวัญ', cn: '送礼物' },
    { id: 'social-live-004', cat: 'social', sub: 'social-live', thai: 'คอมเมนต์ให้แรง', cn: '多评论' },
    { id: 'social-live-005', cat: 'social', sub: 'social-live', thai: 'แชร์ไลฟ์', cn: '分享直播' },
    { id: 'social-live-006', cat: 'social', sub: 'social-live', thai: 'เข้ามาดูไลฟ์', cn: '进直播间' },
    { id: 'social-live-007', cat: 'social', sub: 'social-live', thai: 'ยอดวิวเยอะมาก', cn: '观看人数很多' },
    { id: 'social-live-008', cat: 'social', sub: 'social-live', thai: 'ไลฟ์นานไหม', cn: '直播多久' },
    { id: 'social-live-009', cat: 'social', sub: 'social-live', thai: 'เหนื่อยไหม', cn: '累吗' },
    { id: 'social-live-010', cat: 'social', sub: 'social-live', thai: 'พูดอีกครั้งได้ไหม', cn: '能再说一遍吗' },
    { id: 'social-live-011', cat: 'social', sub: 'social-live', thai: 'อ่านคอมเมนต์หน่อย', cn: '读一下评论' },
    { id: 'social-live-012', cat: 'social', sub: 'social-live', thai: 'ขอเพลง', cn: '点歌' },
    { id: 'social-live-013', cat: 'social', sub: 'social-live', thai: 'ขอให้มีไลฟ์บ่อยๆ', cn: '希望多直播' },
    { id: 'social-live-014', cat: 'social', sub: 'social-live', thai: 'รอไลฟ์หน้า', cn: '等下一场直播' },
    { id: 'social-live-015', cat: 'social', sub: 'social-live', thai: 'ไลฟ์สนุกมาก', cn: '直播很好玩' },
    { id: 'social-live-016', cat: 'social', sub: 'social-live', thai: 'หัวเราะตลอด', cn: '笑个不停' },
    { id: 'social-live-017', cat: 'social', sub: 'social-live', thai: 'ขอบคุณสำหรับไลฟ์', cn: '谢谢直播' },
    { id: 'social-live-018', cat: 'social', sub: 'social-live', thai: 'อย่าลืมกินข้าว', cn: '别忘了吃饭' },
    { id: 'social-live-019', cat: 'social', sub: 'social-live', thai: 'พักผ่อนบ้าง', cn: '休息一下' },
    { id: 'social-live-020', cat: 'social', sub: 'social-live', thai: 'รักนะ', cn: '爱你' },
    { id: 'social-vote-001', cat: 'social', sub: 'social-vote', thai: 'โหวตยังไง', cn: '怎么投票' },
    { id: 'social-vote-002', cat: 'social', sub: 'social-vote', thai: 'กดโหวต', cn: '点投票' },
    { id: 'social-vote-003', cat: 'social', sub: 'social-vote', thai: 'โหวตให้เขา', cn: '投给他' },
    { id: 'social-vote-004', cat: 'social', sub: 'social-vote', thai: 'ขอโหวตหน่อย', cn: '求投票' },
    { id: 'social-vote-005', cat: 'social', sub: 'social-vote', thai: 'ช่วยกันโหวต', cn: '一起投票' },
    { id: 'social-vote-006', cat: 'social', sub: 'social-vote', thai: 'ผ่านเข้ารอบแล้ว', cn: '进了吗' },
    { id: 'social-vote-007', cat: 'social', sub: 'social-vote', thai: 'เกือบชนะแล้ว', cn: '快赢了' },
    { id: 'social-vote-008', cat: 'social', sub: 'social-vote', thai: 'อีกนิดเดียว', cn: '差一点' },
    { id: 'social-vote-009', cat: 'social', sub: 'social-vote', thai: 'โหวตทุกวัน', cn: '每天投票' },
    { id: 'social-vote-010', cat: 'social', sub: 'social-vote', thai: 'ตั้งเตือนโหวต', cn: '设提醒投票' },
    { id: 'social-vote-011', cat: 'social', sub: 'social-vote', thai: 'แชร์ลิงก์โหวต', cn: '分享投票链接' },
    { id: 'social-vote-012', cat: 'social', sub: 'social-vote', thai: 'เกณฑ์เพื่อนโหวต', cn: '拉朋友投票' },
    { id: 'social-vote-013', cat: 'social', sub: 'social-vote', thai: 'ขอบคุณที่โหวต', cn: '谢谢投票' },
    { id: 'social-vote-014', cat: 'social', sub: 'social-vote', thai: 'เลขที่เท่าไหร่', cn: '几号' },
    { id: 'social-vote-015', cat: 'social', sub: 'social-vote', thai: 'ผลโหวตออกยัง', cn: '投票结果出了吗' },
    { id: 'social-vote-016', cat: 'social', sub: 'social-vote', thai: 'ชนะแล้ว', cn: '赢了' },
    { id: 'social-vote-017', cat: 'social', sub: 'social-vote', thai: 'เสียใจด้วย', cn: '可惜了' },
    { id: 'social-vote-018', cat: 'social', sub: 'social-vote', thai: 'คราวหน้าสู้ต่อ', cn: '下次继续努力' },
    { id: 'social-vote-019', cat: 'social', sub: 'social-vote', thai: 'ทำได้ดีแล้ว', cn: '已经做得很好了' },
    { id: 'social-vote-020', cat: 'social', sub: 'social-vote', thai: 'ภูมิใจในตัวเธอ', cn: '为你骄傲' },
    { id: 'offline-pilgrim-001', cat: 'offline', sub: 'offline-pilgrim', thai: 'ที่นี่ถ่ายหนังเรื่องอะไร', cn: '这里拍了什么剧' },
    { id: 'offline-pilgrim-002', cat: 'offline', sub: 'offline-pilgrim', thai: 'ร้านนี้พวกเขามากินจริงไหม', cn: '这家店他们真来吃过吗' },
    { id: 'offline-pilgrim-003', cat: 'offline', sub: 'offline-pilgrim', thai: 'ขอถ่ายรูปที่นี่', cn: '想在这里拍照' },
    { id: 'offline-pilgrim-004', cat: 'offline', sub: 'offline-pilgrim', thai: 'โรงเรียนนี้ใช้ถ่ายหนังหรือเปล่า', cn: '这学校是用来拍戏的吗' },
    { id: 'offline-pilgrim-005', cat: 'offline', sub: 'offline-pilgrim', thai: 'มาแล้ว ดีใจมาก', cn: '来了好开心' },
    { id: 'offline-pilgrim-006', cat: 'offline', sub: 'offline-pilgrim', thai: 'เหมือนในหนังเลย', cn: '跟剧里一样' },
    { id: 'offline-pilgrim-007', cat: 'offline', sub: 'offline-pilgrim', thai: 'ฉากนี้ถ่ายที่นี่', cn: '这场戏在这里拍的' },
    { id: 'offline-pilgrim-008', cat: 'offline', sub: 'offline-pilgrim', thai: 'ขอนั่งโต๊ะเดียวกับในหนัง', cn: '可以坐剧中那张桌子吗' },
    { id: 'offline-pilgrim-009', cat: 'offline', sub: 'offline-pilgrim', thai: 'มีเมนูละครด้วย', cn: '有剧中同款菜单' },
    { id: 'offline-pilgrim-010', cat: 'offline', sub: 'offline-pilgrim', thai: 'ขอสั่งอันนั้นด้วย', cn: '来一份' },
    { id: 'offline-pilgrim-011', cat: 'offline', sub: 'offline-pilgrim', thai: 'สถานที่ถ่ายทำ', cn: '拍摄地点' },
    { id: 'offline-pilgrim-012', cat: 'offline', sub: 'offline-pilgrim', thai: 'แฟนคลับมาเยอะไหม', cn: '粉丝来多吗' },
    { id: 'offline-pilgrim-013', cat: 'offline', sub: 'offline-pilgrim', thai: 'ขอเซลฟี่ที่นี่', cn: '想在这里自拍' },
    { id: 'offline-pilgrim-014', cat: 'offline', sub: 'offline-pilgrim', thai: 'วิวสวยจัง', cn: '风景好美' },
    { id: 'offline-pilgrim-015', cat: 'offline', sub: 'offline-pilgrim', thai: 'คุ้มค่าที่มา', cn: '值得来' },
    { id: 'offline-pilgrim-016', cat: 'offline', sub: 'offline-pilgrim', thai: 'อยากมาอีก', cn: '想再来' },
    { id: 'offline-pilgrim-017', cat: 'offline', sub: 'offline-pilgrim', thai: 'เส้นทางศักดิ์สิทธิ์', cn: '圣地路线' },
    { id: 'offline-pilgrim-018', cat: 'offline', sub: 'offline-pilgrim', thai: 'ตามรอยพวกเขา', cn: '追寻他们的足迹' },
    { id: 'offline-pilgrim-019', cat: 'offline', sub: 'offline-pilgrim', thai: 'ร้านนี้มีป้ายหนัง', cn: '这家店有剧集招牌' },
    { id: 'offline-pilgrim-020', cat: 'offline', sub: 'offline-pilgrim', thai: 'ถ่ายทำที่ไหนบ้าง', cn: '在哪里拍的' },
    { id: 'offline-merch-001', cat: 'offline', sub: 'offline-merch', thai: 'ของแฟนคลับมีไหม', cn: '有粉丝周边吗' },
    { id: 'offline-merch-002', cat: 'offline', sub: 'offline-merch', thai: 'ของใช้ลิมิเต็ดมีไหม', cn: '有限量周边吗' },
    { id: 'offline-merch-003', cat: 'offline', sub: 'offline-merch', thai: 'ราคาเท่าไหร่', cn: '多少钱' },
    { id: 'offline-merch-004', cat: 'offline', sub: 'offline-merch', thai: 'มีสต็อกไหม', cn: '有库存吗' },
    { id: 'offline-merch-005', cat: 'offline', sub: 'offline-merch', thai: 'ซื้อออนไลน์ได้ไหม', cn: '可以网购吗' },
    { id: 'offline-merch-006', cat: 'offline', sub: 'offline-merch', thai: 'ของหมดแล้ว', cn: '卖完了' },
    { id: 'offline-merch-007', cat: 'offline', sub: 'offline-merch', thai: 'มีแพ็คเกจไหม', cn: '有套餐吗' },
    { id: 'offline-merch-008', cat: 'offline', sub: 'offline-merch', thai: 'มีลายใหม่ไหม', cn: '有新款式吗' },
    { id: 'offline-merch-009', cat: 'offline', sub: 'offline-merch', thai: 'ขอดูอันนั้น', cn: '看那个' },
    { id: 'offline-merch-010', cat: 'offline', sub: 'offline-merch', thai: 'ขอลองดู', cn: '让我看看' },
    { id: 'offline-merch-011', cat: 'offline', sub: 'offline-merch', thai: 'สีอะไรมีบ้าง', cn: '有什么颜色' },
    { id: 'offline-merch-012', cat: 'offline', sub: 'offline-merch', thai: 'มีไซส์ไหนบ้าง', cn: '有什么尺码' },
    { id: 'offline-merch-013', cat: 'offline', sub: 'offline-merch', thai: 'ซื้อกี่ชิ้น', cn: '买几件' },
    { id: 'offline-merch-014', cat: 'offline', sub: 'offline-merch', thai: 'ลดราคาไหม', cn: '有折扣吗' },
    { id: 'offline-merch-015', cat: 'offline', sub: 'offline-merch', thai: 'ของแถมมีไหม', cn: '有赠品吗' },
    { id: 'offline-merch-016', cat: 'offline', sub: 'offline-merch', thai: 'ขอเซ็นบนของได้ไหม', cn: '可以在周边上签名吗' },
    { id: 'offline-merch-017', cat: 'offline', sub: 'offline-merch', thai: 'จะมีของใหม่ไหม', cn: '会有新品吗' },
    { id: 'offline-merch-018', cat: 'offline', sub: 'offline-merch', thai: 'ซื้อเป็นของขวัญ', cn: '买来送人' },
    { id: 'offline-merch-019', cat: 'offline', sub: 'offline-merch', thai: 'ห่อของขวัญได้ไหม', cn: '可以包装成礼物吗' },
    { id: 'offline-merch-020', cat: 'offline', sub: 'offline-merch', thai: 'ค่าส่งเท่าไหร่', cn: '运费多少' },
    { id: 'offline-wreath-001', cat: 'offline', sub: 'offline-wreath', thai: 'สั่งพวงมาลัย', cn: '订花篮' },
    { id: 'offline-wreath-002', cat: 'offline', sub: 'offline-wreath', thai: 'ขอเขียนการ์ด', cn: '想写卡片' },
    { id: 'offline-wreath-003', cat: 'offline', sub: 'offline-wreath', thai: 'ส่งถึงสถานที่จัดกิจกรรม', cn: '送到活动场地' },
    { id: 'offline-wreath-004', cat: 'offline', sub: 'offline-wreath', thai: 'พวงมาลัยราคาเท่าไหร่', cn: '花篮多少钱' },
    { id: 'offline-wreath-005', cat: 'offline', sub: 'offline-wreath', thai: 'ขนาดเท่าไหร่', cn: '多大尺寸' },
    { id: 'offline-wreath-006', cat: 'offline', sub: 'offline-wreath', thai: 'ส่งถึงวันไหน', cn: '送到哪天' },
    { id: 'offline-wreath-007', cat: 'offline', sub: 'offline-wreath', thai: 'เขียนข้อความอะไรดี', cn: '写什么好' },
    { id: 'offline-wreath-008', cat: 'offline', sub: 'offline-wreath', thai: 'ขอสีชมพู', cn: '要粉色' },
    { id: 'offline-wreath-009', cat: 'offline', sub: 'offline-wreath', thai: 'ขอสีฟ้า', cn: '要蓝色' },
    { id: 'offline-wreath-010', cat: 'offline', sub: 'offline-wreath', thai: 'ดอกไม้อะไร', cn: '什么花' },
    { id: 'offline-wreath-011', cat: 'offline', sub: 'offline-wreath', thai: 'ขอดูแบบ', cn: '看款式' },
    { id: 'offline-wreath-012', cat: 'offline', sub: 'offline-wreath', thai: 'ตั้งอยู่หน้างาน', cn: '放在活动门口' },
    { id: 'offline-wreath-013', cat: 'offline', sub: 'offline-wreath', thai: 'ขอเขียนชื่อแฟนคลับ', cn: '写粉丝团名字' },
    { id: 'offline-wreath-014', cat: 'offline', sub: 'offline-wreath', thai: 'ส่งถึงสถานี', cn: '送到电视台' },
    { id: 'offline-wreath-015', cat: 'offline', sub: 'offline-wreath', thai: 'ส่งถึงโรงภาพยนตร์', cn: '送到影院' },
    { id: 'offline-wreath-016', cat: 'offline', sub: 'offline-wreath', thai: 'ขอใบเสร็จ', cn: '要收据' },
    { id: 'offline-wreath-017', cat: 'offline', sub: 'offline-wreath', thai: 'สั่งกี่วันล่วงหน้า', cn: '提前几天订' },
    { id: 'offline-wreath-018', cat: 'offline', sub: 'offline-wreath', thai: 'มีบริการจัดส่งไหม', cn: '有配送服务吗' },
    { id: 'offline-wreath-019', cat: 'offline', sub: 'offline-wreath', thai: 'พวงมาลัยสวยมาก', cn: '花篮很美' },
    { id: 'offline-wreath-020', cat: 'offline', sub: 'offline-wreath', thai: 'ขอบคุณมาก', cn: '非常感谢' },
    { id: 'offline-fanclub-001', cat: 'offline', sub: 'offline-fanclub', thai: 'สมัครแฟนคลับยังไง', cn: '怎么加入粉丝团' },
    { id: 'offline-fanclub-002', cat: 'offline', sub: 'offline-fanclub', thai: 'ค่าสมาชิกเท่าไหร่', cn: '会费多少' },
    { id: 'offline-fanclub-003', cat: 'offline', sub: 'offline-fanclub', thai: 'มีกิจกรรมไหม', cn: '有活动吗' },
    { id: 'offline-fanclub-004', cat: 'offline', sub: 'offline-fanclub', thai: 'สมัครแล้ว', cn: '已加入' },
    { id: 'offline-fanclub-005', cat: 'offline', sub: 'offline-fanclub', thai: 'เลิกสมาชิกยังไง', cn: '怎么退会' },
    { id: 'offline-fanclub-006', cat: 'offline', sub: 'offline-fanclub', thai: 'มีสิทธิประโยชน์อะไรบ้าง', cn: '有什么福利' },
    { id: 'offline-fanclub-007', cat: 'offline', sub: 'offline-fanclub', thai: 'มีของแถมไหม', cn: '有赠品吗' },
    { id: 'offline-fanclub-008', cat: 'offline', sub: 'offline-fanclub', thai: 'มีไลน์กลุ่มไหม', cn: '有LINE群吗' },
    { id: 'offline-fanclub-009', cat: 'offline', sub: 'offline-fanclub', thai: 'มีกิจกรรมต่อไปไหม', cn: '有后续活动吗' },
    { id: 'offline-fanclub-010', cat: 'offline', sub: 'offline-fanclub', thai: 'พบกันเมื่อไหร่', cn: '什么时候见面' },
    { id: 'offline-fanclub-011', cat: 'offline', sub: 'offline-fanclub', thai: 'มีการประชุมไหม', cn: '有聚会吗' },
    { id: 'offline-fanclub-012', cat: 'offline', sub: 'offline-fanclub', thai: 'สมัครออนไลน์ได้ไหม', cn: '可以网上加入吗' },
    { id: 'offline-fanclub-013', cat: 'offline', sub: 'offline-fanclub', thai: 'ต้องมีบัตรประชาชนไหม', cn: '需要身份证吗' },
    { id: 'offline-fanclub-014', cat: 'offline', sub: 'offline-fanclub', thai: 'สมาชิกกี่คนแล้ว', cn: '有多少会员了' },
    { id: 'offline-fanclub-015', cat: 'offline', sub: 'offline-fanclub', thai: 'มีส่วนลดซื้อของไหม', cn: '有购物折扣吗' },
    { id: 'offline-fanclub-016', cat: 'offline', sub: 'offline-fanclub', thai: 'มีงานฉลองไหม', cn: '有庆祝活动吗' },
    { id: 'offline-fanclub-017', cat: 'offline', sub: 'offline-fanclub', thai: 'ขอเข้ากลุ่ม', cn: '请让我进群' },
    { id: 'offline-fanclub-018', cat: 'offline', sub: 'offline-fanclub', thai: 'มีป้ายชื่อไหม', cn: '有名牌吗' },
    { id: 'offline-fanclub-019', cat: 'offline', sub: 'offline-fanclub', thai: 'เสื้อแฟนคลับ', cn: '粉丝团T恤' },
    { id: 'offline-fanclub-020', cat: 'offline', sub: 'offline-fanclub', thai: 'ภูมิใจที่เป็นแฟนคลับ', cn: '以粉丝身份为荣' },
    { id: 'offline-audition-001', cat: 'offline', sub: 'offline-audition', thai: 'โหวตยังไง', cn: '怎么投票' },
    { id: 'offline-audition-002', cat: 'offline', sub: 'offline-audition', thai: 'หมายเลขกี่', cn: '几号' },
    { id: 'offline-audition-003', cat: 'offline', sub: 'offline-audition', thai: 'ผ่านเข้ารอบไหม', cn: '进了吗' },
    { id: 'offline-audition-004', cat: 'offline', sub: 'offline-audition', thai: 'ผู้เข้าแข่งงานที่ชอบ', cn: '喜欢的选手' },
    { id: 'offline-audition-005', cat: 'offline', sub: 'offline-audition', thai: 'แชมป์', cn: '冠军' },
    { id: 'offline-audition-006', cat: 'offline', sub: 'offline-audition', thai: 'ตกรอบ', cn: '淘汰了' },
    { id: 'offline-audition-007', cat: 'offline', sub: 'offline-audition', thai: 'โหวตฟรี', cn: '免费投票' },
    { id: 'offline-audition-008', cat: 'offline', sub: 'offline-audition', thai: 'กดโหวต', cn: '点投票' },
    { id: 'offline-audition-009', cat: 'offline', sub: 'offline-audition', thai: 'ขอโหวตหน่อย', cn: '求投票' },
    { id: 'offline-audition-010', cat: 'offline', sub: 'offline-audition', thai: 'โหวตทุกวัน', cn: '每天投票' },
    { id: 'offline-audition-011', cat: 'offline', sub: 'offline-audition', thai: 'รอบต่อไป', cn: '下一轮' },
    { id: 'offline-audition-012', cat: 'offline', sub: 'offline-audition', thai: 'รอบชิง', cn: '决赛' },
    { id: 'offline-audition-013', cat: 'offline', sub: 'offline-audition', thai: 'ผ่านเข้ารอบชิง', cn: '进决赛了' },
    { id: 'offline-audition-014', cat: 'offline', sub: 'offline-audition', thai: 'ทำได้ดีมาก', cn: '做得很好' },
    { id: 'offline-audition-015', cat: 'offline', sub: 'offline-audition', thai: 'เสียดาย', cn: '可惜' },
    { id: 'offline-audition-016', cat: 'offline', sub: 'offline-audition', thai: 'คราวหน้าสู้ต่อ', cn: '下次继续' },
    { id: 'offline-audition-017', cat: 'offline', sub: 'offline-audition', thai: 'เก่งมาก', cn: '很厉害' },
    { id: 'offline-audition-018', cat: 'offline', sub: 'offline-audition', thai: 'ภูมิใจในตัวเธอ', cn: '为你骄傲' },
    { id: 'offline-audition-019', cat: 'offline', sub: 'offline-audition', thai: 'รอผล', cn: '等结果' },
    { id: 'offline-audition-020', cat: 'offline', sub: 'offline-audition', thai: 'ผลออกยัง', cn: '结果出了吗' },
    { id: 'offline-emergency-001', cat: 'offline', sub: 'offline-emergency', thai: 'หากันไม่เจอ', cn: '走散了' },
    { id: 'offline-emergency-002', cat: 'offline', sub: 'offline-emergency', thai: 'ทางออกอยู่ไหน', cn: '出口在哪' },
    { id: 'offline-emergency-003', cat: 'offline', sub: 'offline-emergency', thai: 'ห้องน้ำอยู่ไหน', cn: '洗手间在哪' },
    { id: 'offline-emergency-004', cat: 'offline', sub: 'offline-emergency', thai: 'ที่นั่งฉันอยู่ไหน', cn: '我的座位在哪' },
    { id: 'offline-emergency-005', cat: 'offline', sub: 'offline-emergency', thai: 'ขอถามทาง', cn: '问个路' },
    { id: 'offline-emergency-006', cat: 'offline', sub: 'offline-emergency', thai: 'โทรเรียกแท็กซี่', cn: '打电话叫出租车' },
    { id: 'offline-emergency-007', cat: 'offline', sub: 'offline-emergency', thai: 'มี Wi-Fi ไหม', cn: '有Wi-Fi吗' },
    { id: 'offline-emergency-008', cat: 'offline', sub: 'offline-emergency', thai: 'ขอชาร์จโทรศัพท์', cn: '充电' },
    { id: 'offline-emergency-009', cat: 'offline', sub: 'offline-emergency', thai: 'ที่ชาร์จหาย', cn: '充电器丢了' },
    { id: 'offline-emergency-010', cat: 'offline', sub: 'offline-emergency', thai: 'เบอร์โทรเท่าไหร่', cn: '电话多少' },
    { id: 'offline-emergency-011', cat: 'offline', sub: 'offline-emergency', thai: 'ขอเบอร์หน่อย', cn: '要个电话' },
    { id: 'offline-emergency-012', cat: 'offline', sub: 'offline-emergency', thai: 'ติดต่อเจ้าหน้าที่', cn: '联系工作人员' },
    { id: 'offline-emergency-013', cat: 'offline', sub: 'offline-emergency', thai: 'ขอความช่วยเหลือ', cn: '需要帮助' },
    { id: 'offline-emergency-014', cat: 'offline', sub: 'offline-emergency', thai: 'รู้สึกไม่สบาย', cn: '不舒服' },
    { id: 'offline-emergency-015', cat: 'offline', sub: 'offline-emergency', thai: 'มีร้านขายยาไหม', cn: '有药店吗' },
    { id: 'offline-emergency-016', cat: 'offline', sub: 'offline-emergency', thai: 'โรงพยาบาลใกล้สุด', cn: '最近的医院' },
    { id: 'offline-emergency-017', cat: 'offline', sub: 'offline-emergency', thai: 'มีแผนที่ไหม', cn: '有地图吗' },
    { id: 'offline-emergency-018', cat: 'offline', sub: 'offline-emergency', thai: 'ขอน้ำดื่ม', cn: '要饮用水' },
    { id: 'offline-emergency-019', cat: 'offline', sub: 'offline-emergency', thai: 'ที่พักใกล้นี้', cn: '附近住宿' },
    { id: 'offline-emergency-020', cat: 'offline', sub: 'offline-emergency', thai: 'ขอบคุณมาก', cn: '非常感谢' },
  ],
  DIALOGUES: [
    { id: 'dlg-bl-01', cat: 'bl', title: '签售会与爱豆面对面', scene: '在签售会上终于见到喜欢的爱豆', turns: [{ s: '你', t: 'สวัสดีค่ะ ดีใจมากที่ได้เจอ', c: '你好，很高兴见到你' }, { s: '爱豆', t: 'ดีใจที่ได้เจอเช่นกัน มาจากประเทศจีนเหรอ', c: '我也很高兴，从中国来的吗' }, { s: '你', t: 'ใช่ค่ะ บินมาเฉพาะเพื่อมาเจอพี่เลย', c: '对，专门飞来见你的' }, { s: '爱豆', t: 'ขอบคุณมากนะ ที่อุสาห์บินมาไกลขนาดนี้', c: '谢谢你大老远飞来' }, { s: '你', t: 'ดูทุกเรื่องเลยค่ะ ชอบมาก', c: '每部剧都看了，很喜欢' }, { s: '爱豆', t: 'เรื่องไหนชอบที่สุด', c: '最喜欢哪部' }, { s: '你', t: 'เรื่องล่าสุดค่ะ ฉากสุดท้ายร้องไห้เลย', c: '最新的那部，最后一场哭了' }, { s: '爱豆', t: 'จะมีเรื่องใหม่เร็วๆ นี้ รอดูนะ', c: '马上有新剧，敬请期待' }, { s: '你', t: 'จะรอดูค่ะ สู้ๆ นะคะ', c: '会等的，加油' }] },
    { id: 'dlg-bl-02', cat: 'bl', title: '粉丝之间磕CP', scene: '两个粉丝讨论最新一集的CP互动', turns: [{ s: 'A', t: 'ตอนใหม่ดูยัง หวานสุด', c: '新的一集看了吗，甜炸了' }, { s: 'B', t: 'ยังเลย กลัวเจ็บ ไม่กล้าดู', c: '还没，怕虐不敢看' }, { s: 'A', t: 'ไม่เจ็บหรอก คู่นี้ล็อคแล้ว', c: '不虐，这对锁了' }, { s: 'B', t: 'จริงเหรอ แล้วฉากในทีเซอร์ล่ะ', c: '真的吗？预告里那场呢' }, { s: 'A', t: 'อันนั้นโอเค ไม่เศร้า', c: '那个没事' }, { s: 'B', t: 'แล้วมีจู้จี้ไหม', c: '有亲密戏吗' }, { s: 'A', t: 'มี ฉากสุดท้าย', c: '有！最后一场' }, { s: 'B', t: 'อ้าาา ดูเลยแล้วกัน', c: '啊啊啊那我去看' }, { s: 'A', t: 'ฟีดจริงๆ คู่นี้', c: '真的在营业，这对' }] },
    { id: 'dlg-bl-03', cat: 'bl', title: '讨论新剧播出时间', scene: '粉丝群讨论新剧什么时候播', turns: [{ s: 'A', t: 'ซีรีส์ใหม่ออกอากาศวันไหน', c: '新剧哪天播' }, { s: 'B', t: 'ฟังว่าวันพุธค่ะ', c: '听说周三' }, { s: 'A', t: 'กี่โมง', c: '几点' }, { s: 'B', t: 'สี่ทุ่มค่ะ ตอนละชั่วโมง', c: '晚上十点，每集一小时' }, { s: 'A', t: 'มีกี่ตอน', c: '一共几集' }, { s: 'B', t: 'สิบสองตอนค่ะ', c: '十二集' }, { s: 'A', t: 'พี่แสดงเรื่องนี้ด้วยใช่ไหม', c: '哥哥也演了这部对吧' }, { s: 'B', t: 'ใช่เลย บทเด็ดมาก', c: '对，角色很棒' }] },
    { id: 'dlg-bl-04', cat: 'bl', title: '剧评讨论', scene: '看完剧后跟朋友讨论剧情', turns: [{ s: 'A', t: 'จบแล้ว คุณว่ายังไง', c: '看完了，你觉得怎么样' }, { s: 'B', t: 'ดีมาก แต่เสียดายจบเร็ว', c: '很好，但可惜太短了' }, { s: 'A', t: 'ใช่เลย อยากให้ต่อยาวกว่านี้', c: '对，想再长一点' }, { s: 'B', t: 'ฉากสุดท้ายฟินสุด', c: '最后一场太爽了' }, { s: 'A', t: 'เคมีดีมาก คู่นี้', c: '这对化学反应好强' }, { s: 'B', t: 'มีซีซัน 2 ไหม', c: '有第二季吗' }, { s: 'A', t: 'ยังไม่มีข่าว แต่น่าจะมี', c: '还没消息，但应该有' }, { s: 'B', t: 'รอดูค่ะ', c: '期待' }] },
    { id: 'dlg-bl-05', cat: 'bl', title: 'CP是否解绑', scene: '讨论喜欢的CP是否还在一起营业', turns: [{ s: 'A', t: 'คู่นี้ยังฟีดกันอยู่ไหม', c: '这对还在营业吗' }, { s: 'B', t: 'ยังเลย อีเวนต์ล่าสุดยังมาด้วยกัน', c: '还在，最近活动还一起' }, { s: 'A', t: 'ดีใจมาก กลัวเลิกคู่กัน', c: '太好了，怕他们解绑' }, { s: 'B', t: 'ยังไม่มีข่าวเลิกคู่', c: '还没解绑消息' }, { s: 'A', t: 'คู่นี้เคมีไม่เคยเปลี่ยน', c: '这对化学反应从未变过' }, { s: 'B', t: 'จริงๆ คู่นี้คือตำนาน', c: '真的，这对是传奇' }] },
    { id: 'dlg-bl-06', cat: 'bl', title: '推荐BL剧给朋友', scene: '向朋友安利一部好看的BL剧', turns: [{ s: 'A', t: 'ดูซีรีส์อะไรดี', c: '看什么剧好' }, { s: 'B', t: 'เรื่องนี้เลย ดีมาก', c: '看这部，很好看' }, { s: 'A', t: 'เรื่องอะไร', c: '什么剧' }, { s: 'B', t: 'BL เรื่องใหม่ พี่แสดงเอง', c: '新BL，哥哥演的' }, { s: 'A', t: 'หวานไหม', c: '甜吗' }, { s: 'B', t: 'หวานมาก ฟินจนไม่ไหว', c: '很甜，上头到不行' }, { s: 'A', t: 'กี่ตอน', c: '几集' }, { s: 'B', t: 'สิบตอน ดูจบในวันเดียว', c: '十集，一天刷完' }, { s: 'A', t: 'ดูเลยแล้วกัน', c: '那我去看' }] },
    { id: 'dlg-bl-07', cat: 'bl', title: '幕后花絮讨论', scene: '看到新的幕后花絮后跟朋友讨论', turns: [{ s: 'A', t: 'ดูบุพพอยแล้วหรือยัง', c: '看花絮了吗' }, { s: 'B', t: 'ยังเลย อยู่ไหน', c: '还没，在哪' }, { s: 'A', t: 'ในยูทูป ขำจนไม่ไหว', c: 'YouTube上，笑到不行' }, { s: 'B', t: 'มีอะไร', c: '有什么' }, { s: 'A', t: 'แกล้งกันตลอด ล้อกันเพลิน', c: '一直恶搞，互怼不停' }, { s: 'B', t: 'ดูแล้วรักมากขึ้น', c: '看了会更喜欢' }, { s: 'A', t: 'เขาสนิทกันจริงๆ', c: '他们真的好熟' }, { s: 'B', t: 'ดูเลยแล้วกัน', c: '去看吧' }] },
    { id: 'dlg-bl-08', cat: 'bl', title: '剧集结局讨论', scene: '讨论一部刚追完的剧的结局', turns: [{ s: 'A', t: 'จบแล้ว คุณชอบไหม', c: '结束了，你喜欢吗' }, { s: 'B', t: 'ชอบมาก จบแบบ HE', c: '很喜欢，HE结局' }, { s: 'A', t: 'ฉันก็ชอบ ไม่เจ็บเลย', c: '我也喜欢，一点都不虐' }, { s: 'B', t: 'ฉากสุดท้ายเรียกน้ำตา', c: '最后一场催泪' }, { s: 'A', t: 'ร้องไห้ตลอดตอน', c: '全程在哭' }, { s: 'B', t: 'แต่จบสวย คุ้มค่า', c: '但结局很美，值得' }, { s: 'A', t: 'อยากให้มีซีซัน 2', c: '希望有第二季' }, { s: 'B', t: 'รอข่าวดี', c: '等好消息' }] },
    { id: 'dlg-gl-01', cat: 'gl', title: '安利GL剧', scene: '向朋友推荐一部好看的GL剧', turns: [{ s: 'A', t: 'มีซีรีส์ GL แนะนำไหม', c: '有GL剧推荐吗' }, { s: 'B', t: 'เรื่องนี้เลย คุณภาพดีมาก', c: '看这部，质量很高' }, { s: 'A', t: 'หวานไหม', c: '甜吗' }, { s: 'B', t: 'หวานมาก คู่นี้ฟินสุด', c: '很甜，这对太上头了' }, { s: 'A', t: 'กี่ตอน', c: '几集' }, { s: 'B', t: 'แปดตอน ดูจบวันเดียว', c: '八集，一天看完' }, { s: 'A', t: 'นักแสดงเก่งไหม', c: '演员演技好吗' }, { s: 'B', t: 'เก่งมาก เคมีดีมาก', c: '很好，化学反应强' }, { s: 'A', t: 'ดูเลยแล้วกัน', c: '那我去看' }] },
    { id: 'dlg-gl-02', cat: 'gl', title: '讨论GL角色', scene: '讨论剧中喜欢的角色', turns: [{ s: 'A', t: 'ชอบตัวละครไหน', c: '喜欢哪个角色' }, { s: 'B', t: 'พี่สาวเท่มาก', c: '姐姐好飒' }, { s: 'A', t: 'ฉันชอบน้องสาว น่ารักมาก', c: '我喜欢妹妹，好可爱' }, { s: 'B', t: 'คู่นี้ดูแลกันอบอุ่นมาก', c: '这对互相照顾好温暖' }, { s: 'A', t: 'ใช่เลย พี่สาวดูแลน้องดีมาก', c: '对，姐姐照顾妹妹好细心' }, { s: 'B', t: 'ผู้หญิงเข้าใจกันได้ดีกว่า', c: '女生更懂女生' }, { s: 'A', t: 'ความสัมพันธ์นี้สวยมาก', c: '这段关系好美' }] },
    { id: 'dlg-gl-03', cat: 'gl', title: 'GL剧情讨论', scene: '讨论最新一集的剧情', turns: [{ s: 'A', t: 'ตอนใหม่ดูยัง', c: '新的一集看了吗' }, { s: 'B', t: 'ดูแล้ว หวานจัง', c: '看了，好甜' }, { s: 'A', t: 'ฉากสารภาพรักฟินสุด', c: '表白那场戏太上头了' }, { s: 'B', t: 'ใช่เลย ใจหายใจวูบ', c: '对，心脏漏跳一拍' }, { s: 'A', t: 'มีซีซัน 2 ไหม', c: '有第二季吗' }, { s: 'B', t: 'ยังไม่มีข่าว แต่น่าจะมี', c: '还没消息，但应该有' }, { s: 'A', t: 'รอดูค่ะ', c: '期待' }] },
    { id: 'dlg-gl-04', cat: 'gl', title: '讨论百合专属话题', scene: '讨论剧中角色类型', turns: [{ s: 'A', t: 'ใครเป็น T ใครเป็น P', c: '谁T谁P' }, { s: 'B', t: 'พี่สาวเป็น T น้องเป็น P', c: '姐姐是T，妹妹是P' }, { s: 'A', t: 'ผมสั้นสวยจัง', c: '短发好美' }, { s: 'B', t: 'หน้าตาเท่แบบทอม', c: 'Tom风格好帅' }, { s: 'A', t: 'ความรักไม่จำกัดเพศ', c: '爱不分性别' }, { s: 'B', t: 'ความรักของผู้หญิงสวยงาม', c: '女性的爱情很美' }] },
    { id: 'dlg-gl-05', cat: 'gl', title: '推荐GL剧列表', scene: '向新粉丝推荐几部GL剧', turns: [{ s: 'A', t: 'เพิ่งเริ่มดู GL มีอะไรแนะนำ', c: '刚入坑GL，有什么推荐' }, { s: 'B', t: 'เรื่องนี้เลย ปลุกปลอบใจมาก', c: '看这部，很治愈' }, { s: 'A', t: 'อีกเรื่องไหม', c: '还有吗' }, { s: 'B', t: 'เรื่องนี้ด้วย ดูแล้วสบายใจ', c: '这部也是，看了很舒服' }, { s: 'A', t: 'ขอบคุณค่ะ', c: '谢谢' }, { s: 'B', t: 'ไม่เป็นไร ดูเพลินๆ', c: '不客气，慢慢看' }] },
    { id: 'dlg-gl-06', cat: 'gl', title: 'GL剧评', scene: '看完一部GL剧后的感想', turns: [{ s: 'A', t: 'ดูจบแล้ว รีวิวห้าดาว', c: '看完了，五星好评' }, { s: 'B', t: 'จริงเหรอ ดีขนาดนั้น', c: '真的吗，那么好' }, { s: 'A', t: 'บทเขียนดีมาก นักแสดงเก่ง', c: '剧本好，演技好' }, { s: 'B', t: 'คุ้มค่าที่ดู', c: '值得一看' }, { s: 'A', t: 'อยากให้เพื่อนดูด้วย', c: '想让朋友也看' }, { s: 'B', t: 'แชร์ให้เพื่อนดูเลย', c: '分享给朋友看吧' }] },
    { id: 'dlg-gl-07', cat: 'gl', title: '期待GL新剧', scene: '讨论即将播出的新GL剧', turns: [{ s: 'A', t: 'มี GL ใหม่ออกเร็วๆ นี้', c: '马上有新GL播出' }, { s: 'B', t: 'จริงเหรอ วันไหน', c: '真的吗，哪天' }, { s: 'A', t: 'อาทิตย์หน้าค่ะ', c: '下周' }, { s: 'B', t: 'คาดหวังเยอะมาก', c: '期待值拉满' }, { s: 'A', t: 'น้องคนนั้นแสดงเอง', c: '那个妹妹演的' }, { s: 'B', t: 'รอดูค่ะ', c: '期待' }] },
    { id: 'dlg-gl-08', cat: 'gl', title: 'GL粉丝互动', scene: '跟泰国粉丝讨论GL剧', turns: [{ s: '你', t: 'สวัสดีค่ะ แฟนคลับจากจีนเลย', c: '你好，我是中国粉丝' }, { s: '泰粉', t: 'ยินดีที่ได้รู้จัก ดูละครเรื่องไหนอยู่', c: '很高兴认识你，在追哪部剧' }, { s: '你', t: 'เรื่อง GL อะ', c: 'GL的那部' }, { s: '泰粉', t: 'เรื่องไหน ฉันก็ดู', c: '哪部，我也在看' }, { s: '你', t: 'คู่นี้หวานมาก', c: '这对好甜' }, { s: '泰粉', t: 'ใช่เลย ที่นี่ก็พูดถึงกันทั่ว', c: '对，这边也都在讨论' }, { s: '你', t: 'มีข่าวซีซัน 2 ไหม', c: '有第二季的消息吗' }, { s: '泰粉', t: 'ยังไม่มีข่าวแน่ชัด แต่น่าจะมี', c: '还没确切消息，但应该有' }, { s: '你', t: 'รอดูค่ะ ขอบคุณนะ', c: '期待，谢谢' }] },
    { id: 'dlg-star-01', cat: 'star', title: '接机遇到其他粉丝', scene: '在机场接机时遇到其他粉丝', turns: [{ s: '你', t: 'รอพี่เหมือนกันเหรอ', c: '你也在等哥哥吗' }, { s: 'B', t: 'ใช่เลย มาตั้งแต่เช้า', c: '对，一早就来了' }, { s: '你', t: 'เที่ยวบินกี่โมง', c: '几点的航班' }, { s: 'B', t: 'สองทุ่มค่ะ อีกประมาณชั่วโมงเดียว', c: '晚上八点，还有大概一小时' }, { s: '你', t: 'ขอยืนข้างๆ ได้ไหม', c: '可以站旁边吗' }, { s: 'B', t: 'ได้เลย มีของขวัญให้พี่ด้วยเหรอ', c: '可以，你也有礼物要送吗' }, { s: '你', t: 'มีจดหมายค่ะ เขียนเองเลย', c: '有封信，亲手写的' }, { s: 'B', t: 'พี่จะดีใจมาก', c: '他一定会很高兴' }] },
    { id: 'dlg-star-02', cat: 'star', title: '见面会合影', scene: '在粉丝见面会上跟爱豆合影', turns: [{ s: '你', t: 'ขอถ่ายรูปด้วยค่ะ', c: '可以合影吗' }, { s: '爱豆', t: 'ได้เลยครับ ยิ้มให้กล้อง', c: '可以，笑一个' }, { s: '你', t: 'ตัวจริงหล่อกว่าในจอ', c: '真人比屏幕上还帅' }, { s: '爱豆', t: 'ขอบคุณครับ ดีใจที่ได้เจอ', c: '谢谢，很高兴见到你' }, { s: '你', t: 'ดูทุกเรื่องเลยค่ะ', c: '每部都看了' }, { s: '爱豆', t: 'ขอบคุณที่ติดตาม', c: '感谢你的支持' }, { s: '你', t: 'สู้ๆ นะคะ รอผลงานต่อไป', c: '加油，期待下一部' }] },
    { id: 'dlg-star-03', cat: 'star', title: '签售会签名', scene: '在签售会上请爱豆签名', turns: [{ s: '你', t: 'เซ็นชื่อให้หน่อยได้ไหมคะ', c: '可以签个名吗' }, { s: '爱豆', t: 'ได้เลยครับ เขียนชื่ออะไร', c: '可以，写什么名字' }, { s: '你', t: 'เขียนชื่อฉันเลยค่ะ', c: '写我的名字就好' }, { s: '爱豆', t: 'เสร็จแล้วครับ', c: '签好了' }, { s: '你', t: 'ขอบคุณมากค่ะ จะเก็บรักษาดีๆ', c: '非常感谢，会好好保管' }, { s: '爱豆', t: 'ขอบคุณที่มา', c: '谢谢你的到来' }] },
    { id: 'dlg-star-04', cat: 'star', title: '送礼物给爱豆', scene: '在活动中把礼物交给爱豆', turns: [{ s: '你', t: 'นี่ของขวัญเล็กๆ นะคะ', c: '这是小礼物' }, { s: '爱豆', t: 'โอ้ ขอบคุณมาก', c: '哦，非常感谢' }, { s: '你', t: 'ทำเองเลยค่ะ', c: '亲手做的' }, { s: '爱豆', t: 'สวยมาก จะเก็บไว้', c: '好美，会收好的' }, { s: '你', t: 'อย่าลืมกินข้าวนะคะ', c: '别忘了吃饭' }, { s: '爱豆', t: 'จะกินแน่นอน ขอบคุณจริงๆ', c: '一定吃，真的谢谢' }] },
    { id: 'dlg-star-05', cat: 'star', title: '打call应援', scene: '在活动现场跟其他粉丝一起打call', turns: [{ s: 'A', t: 'ตะโกนตามฉันนะ', c: '跟我喊' }, { s: 'B', t: 'โอเค', c: '好的' }, { s: 'A', t: 'พี่สู้ๆ', c: '哥哥加油' }, { s: 'B', t: 'พี่สู้ๆ', c: '哥哥加油' }, { s: 'A', t: 'เรารักพี่', c: '我们爱你' }, { s: 'B', t: 'เรารักพี่', c: '我们爱你' }, { s: 'A', t: 'เปิดไฟฉายเลย', c: '打开应援灯' }, { s: 'B', t: 'เปลี่ยนสีแล้ว', c: '换颜色了' }] },
    { id: 'dlg-star-06', cat: 'star', title: '送机告别', scene: '在机场送爱豆离开', turns: [{ s: '你', t: 'บินปลอดภัยนะคะ', c: '飞行平安' }, { s: '爱豆', t: 'ขอบคุณที่มาส่ง', c: '谢谢来送我' }, { s: '你', t: 'กลับไปดูแลตัวเองนะ', c: '回去照顾好自己' }, { s: '爱豆', t: 'จะดูแลตัวเอง ไม่ต้องห่วง', c: '会的，不用担心' }, { s: '你', t: 'รอวันที่ได้เจอกันอีก', c: '期待再见面' }, { s: '爱豆', t: 'จะกลับมาเร็วๆ นี้', c: '很快会回来的' }] },
    { id: 'dlg-star-07', cat: 'star', title: '夸赞爱豆', scene: '跟朋友夸赞喜欢的爱豆', turns: [{ s: 'A', t: 'พี่หล่อมาก', c: '哥哥好帅' }, { s: 'B', t: 'ใช่เลย ยิ้มสวยมาก', c: '对，笑容好美' }, { s: 'A', t: 'เสียงดีมากด้วย', c: '声音也好听' }, { s: 'B', t: 'เต้นเก่งมาก', c: '跳舞也好厉害' }, { s: 'A', t: 'จริงๆ ไม่มีข้อเสียเลย', c: '真的没有缺点' }, { s: 'B', t: 'พี่คือ number one', c: '哥哥是第一名' }] },
    { id: 'dlg-star-08', cat: 'star', title: '写信给爱豆', scene: '跟朋友讨论要给爱豆写什么信', turns: [{ s: 'A', t: 'เขียนจดหมายให้พี่ไหม', c: '要给哥哥写信吗' }, { s: 'B', t: 'เขียนแน่นอน', c: '一定写' }, { s: 'A', t: 'เขียนว่าอะไรดี', c: '写什么好' }, { s: 'B', t: 'ขอบคุณที่เกิดมา', c: '感谢你的存在' }, { s: 'A', t: 'ดีเลย อย่าลืมกินข้าวก็ด้วย', c: '好，别忘了加一句要吃饭' }, { s: 'B', t: 'จะเขียนเองเลย', c: '会亲手写' }] },
    { id: 'dlg-con-01', cat: 'concert', title: '演唱会门口找座位', scene: '在演唱会场馆找自己的座位', turns: [{ s: '你', t: 'ขอถามหน่อยค่ะ ที่นั่งโซน B ทางไหน', c: '请问B区座位往哪走' }, { s: '工作人员', t: 'ตรงไปเลย แล้วเลี้ยวขวา', c: '直走然后右转' }, { s: '你', t: 'ไกลไหม', c: '远吗' }, { s: '工作人员', t: 'ไม่ไกล เดินประมาณสามนาที', c: '不远，走三分钟左右' }, { s: '你', t: 'ขอบคุณค่ะ แล้วห้องน้ำอยู่ไหน', c: '谢谢，洗手间在哪' }, { s: '工作人员', t: 'อยู่ข้างๆ ทางเข้า', c: '入口旁边' }, { s: '你', t: 'ขอบคุณมากค่ะ', c: '非常感谢' }] },
    { id: 'dlg-con-02', cat: 'concert', title: '买演唱会门票', scene: '跟朋友讨论买演唱会票', turns: [{ s: 'A', t: 'ซื้อตั๋วยัง', c: '买票了吗' }, { s: 'B', t: 'ยังเลย ซื้อยังไง', c: '还没，怎么买' }, { s: 'A', t: 'ซื้อออนไลน์เลย', c: '网上买' }, { s: 'B', t: 'ราคาเท่าไหร่', c: '多少钱' }, { s: 'A', t: 'แถวหน้าสี่พันบาท', c: '前排四千泰铢' }, { s: 'B', t: 'แพงไหม', c: '贵吗' }, { s: 'A', t: 'ไม่แพงเทียบกับคุณค่า', c: '跟价值比不贵' }, { s: 'B', t: 'ซื้อเลยแล้วกัน', c: '那买吧' }] },
    { id: 'dlg-con-03', cat: 'concert', title: '演唱会应援', scene: '在演唱会现场跟旁边粉丝一起应援', turns: [{ s: 'A', t: 'เปิดไฟฉายเลย', c: '打开应援灯' }, { s: 'B', t: 'เปิดแล้ว', c: '开了' }, { s: 'A', t: 'สีอะไร', c: '什么颜色' }, { s: 'B', t: 'สีฟ้า สีของพี่', c: '蓝色，哥哥的颜色' }, { s: 'A', t: 'ร้องตามกัน', c: '一起唱' }, { s: 'B', t: 'ตะโกนดังๆ', c: '大声喊' }] },
    { id: 'dlg-con-04', cat: 'concert', title: '演唱会安可', scene: '演唱会结束后想要安可', turns: [{ s: 'A', t: 'ขอแอนคอร์', c: '安可安可' }, { s: 'B', t: 'อีกเพลงนะ', c: '再来一首' }, { s: 'A', t: 'ไม่อยากให้จบ', c: '不想结束' }, { s: 'B', t: 'คุ้มค่ามาก', c: '太值了' }, { s: 'A', t: 'คอนเสิร์ตสุดยอด', c: '演唱会太棒了' }] },
    { id: 'dlg-con-05', cat: 'concert', title: '音乐打榜', scene: '跟粉丝讨论帮爱豆打榜', turns: [{ s: 'A', t: 'ช่วยสตรีมเพลงใหม่', c: '帮刷新歌播放' }, { s: 'B', t: 'กดไลค์ด้วย', c: '也点赞' }, { s: 'A', t: 'แชร์ให้หน่อย', c: '帮分享' }, { s: 'B', t: 'แชร์แล้ว', c: '分享了' }, { s: 'A', t: 'ช่วยกันทำให้ขึ้นอันดับ 1', c: '一起冲第一' }, { s: 'B', t: 'สู้ๆ', c: '加油' }] },
    { id: 'dlg-con-06', cat: 'concert', title: '场馆求助', scene: '在场馆不舒服需要帮助', turns: [{ s: '你', t: 'ช่วยด้วย รู้สึกไม่สบาย', c: '救命，不舒服' }, { s: '工作人员', t: 'เป็นอะไรไหม', c: '怎么了' }, { s: '你', t: 'เวียนหัว ร้อนมาก', c: '头晕，好热' }, { s: '工作人员', t: 'มานั่งพักทางนี้', c: '来这里坐下休息' }, { s: '你', t: 'ขอน้ำหน่อย', c: '请给点水' }, { s: '工作人员', t: 'นี่น้ำ ดื่มเยอะๆ', c: '给你水，多喝点' }] },
    { id: 'dlg-con-07', cat: 'concert', title: '买周边', scene: '在演唱会周边商店买东西', turns: [{ s: '你', t: 'ของใช้ลิมิเต็ดมีไหม', c: '有限量周边吗' }, { s: '店员', t: 'มีครับ อันนี้เลย', c: '有，这个' }, { s: '你', t: 'ราคาเท่าไหร่', c: '多少钱' }, { s: '店员', t: 'ห้าร้อยบาทครับ', c: '五百泰铢' }, { s: '你', t: 'ขอสีฟ้า', c: '要蓝色' }, { s: '店员', t: 'ได้ครับ', c: '好的' }, { s: '你', t: 'ซื้อแล้ว ขอบคุณ', c: '买了，谢谢' }] },
    { id: 'dlg-con-08', cat: 'concert', title: '等演唱会开始', scene: '在场馆等待演唱会开始', turns: [{ s: 'A', t: 'กี่โมงเริ่ม', c: '几点开始' }, { s: 'B', t: 'สี่ทุ่ม', c: '晚上十点' }, { s: 'A', t: 'ประตูเปิดยัง', c: '开门了吗' }, { s: 'B', t: 'เปิดแล้ว ไปกันเถอะ', c: '开了，走吧' }, { s: 'A', t: 'ที่นั่งแถวหน้าเลย', c: '前排座位' }, { s: 'B', t: 'เห็นชัดมากแน่นอน', c: '一定看得很清楚' }] },
    { id: 'dlg-soc-01', cat: 'social', title: '社交媒体互动', scene: '跟泰国粉丝在社交媒体上互动', turns: [{ s: '你', t: 'สวัสดีค่ะ แฟนคลับจากจีนเลย', c: '你好，我是中国粉丝' }, { s: '泰粉', t: 'ยินดีที่ได้รู้จัก', c: '很高兴认识你' }, { s: '你', t: 'รีโพสต์ด้วยนะ', c: '请转发' }, { s: '泰粉', t: 'เรทวิตให้แล้ว', c: '已经转推了' }, { s: '你', t: 'ช่วยกันเทรนด์', c: '一起冲趋势' }, { s: '泰粉', t: 'โอเค ติดเทรนด์แล้ว', c: '好的，上趋势了' }] },
    { id: 'dlg-soc-02', cat: 'social', title: 'TikTok视频评论', scene: '在爱豆的TikTok视频下评论', turns: [{ s: 'A', t: 'ยอดวิวเยอะจัง', c: '播放量好高' }, { s: 'B', t: 'เก่งมาก', c: '太厉害了' }, { s: 'A', t: 'ขอดูแดนซ์อีก', c: '想再看舞蹈' }, { s: 'B', t: 'น่ารักมาก', c: '好可爱' }, { s: 'A', t: 'แชร์วิดีโอ', c: '分享视频' }, { s: 'B', t: 'คอมเมนต์กันเยอะๆ', c: '多评论' }] },
    { id: 'dlg-soc-03', cat: 'social', title: '超话打榜', scene: '粉丝群讨论帮爱豆投票打榜', turns: [{ s: 'A', t: 'โหวตยังไง', c: '怎么投票' }, { s: 'B', t: 'กดโหวตในแอป', c: '在app里点投票' }, { s: 'A', t: 'โหวตทุกวันนะ', c: '每天投票' }, { s: 'B', t: 'ตั้งเตือนแล้ว', c: '设了提醒' }, { s: 'A', t: 'ช่วยกันโหวต', c: '一起投票' }, { s: 'B', t: 'เกือบชนะแล้ว', c: '快赢了' }] },
    { id: 'dlg-soc-04', cat: 'social', title: 'Instagram追更', scene: '在Instagram上等爱豆更新', turns: [{ s: 'A', t: 'โพสต์ใหม่ยัง', c: '有新帖吗' }, { s: 'B', t: 'ยังเลย รอโพสต์ใหม่', c: '还没，等新帖' }, { s: 'A', t: 'อัปเดทบ่อยๆ นะ', c: '多更新哦' }, { s: 'B', t: 'ขอสตอรี่เพิ่ม', c: '多发story' }, { s: 'A', t: 'เซลฟี่นี้ดีจัง', c: '这自拍绝了' }, { s: 'B', t: 'สวยมาก', c: '好美' }] },
    { id: 'dlg-soc-05', cat: 'social', title: '直播互动', scene: '在爱豆直播中互动', turns: [{ s: 'A', t: 'เข้ามาดูไลฟ์', c: '进直播间' }, { s: 'B', t: 'มาแล้ว', c: '来了' }, { s: 'A', t: 'กดติดตามไว้', c: '点关注' }, { s: 'B', t: 'ติดตามแล้ว', c: '关注了' }, { s: 'A', t: 'ส่งของขวัญ', c: '送礼物' }, { s: 'B', t: 'คอมเมนต์ให้แรง', c: '多评论' }] },
    { id: 'dlg-soc-06', cat: 'social', title: '饭圈黑话解释', scene: '向新粉丝解释饭圈术语', turns: [{ s: 'A', t: 'ฟีดคืออะไร', c: '营业是什么意思' }, { s: 'B', t: 'ฟีดคือให้อาหาร แปลว่าทำให้แฟนคลับฟิน', c: 'feeding，让粉丝上头' }, { s: 'A', t: 'แล้วชิปล่ะ', c: '那磕呢' }, { s: 'B', t: 'ชิปคือจิ้น คือชอบคู่', c: 'ship，喜欢一对CP' }, { s: 'A', t: 'HE คืออะไร', c: 'HE是什么' }, { s: 'B', t: 'HE คือ happy ending จบสวย', c: 'HE是好结局' }, { s: 'A', t: 'เข้าใจแล้ว ขอบคุณ', c: '懂了，谢谢' }] },
    { id: 'dlg-soc-07', cat: 'social', title: 'Twitter冲趋势', scene: '粉丝群讨论帮爱豆冲Twitter趋势', turns: [{ s: 'A', t: 'ชื่อแฮชแท็กอะไร', c: '话题标签是什么' }, { s: 'B', t: 'ดูในบัญชีทางการ', c: '看官方账号' }, { s: 'A', t: 'ช่วยกันเทรนด์', c: '一起冲趋势' }, { s: 'B', t: 'ติดเทรนด์แล้ว', c: '上趋势了' }, { s: 'A', t: 'อันดับ 1 แล้ว', c: '第一了' }, { s: 'B', t: 'เก่งมาก', c: '太厉害了' }] },
    { id: 'dlg-soc-08', cat: 'social', title: '投票结果讨论', scene: '讨论选秀投票结果', turns: [{ s: 'A', t: 'ผลโหวตออกยัง', c: '投票结果出了吗' }, { s: 'B', t: 'ออกแล้ว ชนะ', c: '出了，赢了' }, { s: 'A', t: 'ดีใจมาก', c: '太开心了' }, { s: 'B', t: 'ภูมิใจในตัวเธอ', c: '为你骄傲' }, { s: 'A', t: 'ขอบคุณที่โหวต', c: '谢谢投票' }, { s: 'B', t: 'ไม่เป็นไร สมควรแล้ว', c: '不客气，实至名归' }] },
    { id: 'dlg-off-01', cat: 'offline', title: '取景地打卡', scene: '在剧集取景地打卡', turns: [{ s: '你', t: 'ร้านนี้ถ่ายละครเรื่องอะไรคะ', c: '这家店拍了什么剧' }, { s: '店员', t: 'เรื่อง BL ครับ มาดูกันเยอะ', c: 'BL剧，很多人来看' }, { s: '你', t: 'นั่งโต๊ะเดียวกับในหนังได้ไหม', c: '可以坐剧中那张桌子吗' }, { s: '店员', t: 'ได้เลยครับ โต๊ะตรงนั้น', c: '可以，那张桌子' }, { s: '你', t: 'ขอถ่ายรูปหน่อย', c: '想拍个照' }, { s: '店员', t: 'ถ่ายได้เลยครับ มีเมนูละครด้วย', c: '随便拍，还有剧中同款菜单' }, { s: '你', t: 'จริงเหรอ ขอสั่งอันนั้นด้วย', c: '真的吗？来一份' }] },
    { id: 'dlg-off-02', cat: 'offline', title: '周边商店', scene: '在周边商店买东西', turns: [{ s: '你', t: 'ของแฟนคลับมีไหม', c: '有粉丝周边吗' }, { s: '店员', t: 'มีครับ ดูอันนี้', c: '有，看这个' }, { s: '你', t: 'ราคาเท่าไหร่', c: '多少钱' }, { s: '店员', t: 'สามร้อยบาท', c: '三百泰铢' }, { s: '你', t: 'มีสีอะไรบ้าง', c: '有什么颜色' }, { s: '店员', t: 'มีสีชมพูกับสีฟ้า', c: '有粉色和蓝色' }, { s: '你', t: 'ขอสีฟ้า ซื้อแล้ว', c: '要蓝色，买了' }] },
    { id: 'dlg-off-03', cat: 'offline', title: '订花篮', scene: '为爱豆的活动订花篮', turns: [{ s: '你', t: 'สั่งพวงมาลัย', c: '订花篮' }, { s: '店员', t: 'ขนาดเท่าไหร่', c: '多大尺寸' }, { s: '你', t: 'ขนาดใหญ่ ส่งถึงสถานที่จัดกิจกรรม', c: '大的，送到活动场地' }, { s: '店员', t: 'เขียนการ์ดไหม', c: '要写卡片吗' }, { s: '你', t: 'ขอเขียนการ์ด สีชมพู', c: '要写卡片，粉色' }, { s: '店员', t: 'ส่งถึงวันไหน', c: '送到哪天' }, { s: '你', t: 'พรุ่งนี้เลย', c: '明天' }, { s: '店员', t: 'โอเคครับ', c: '好的' }] },
    { id: 'dlg-off-04', cat: 'offline', title: '加入粉丝团', scene: '询问如何加入粉丝团', turns: [{ s: '你', t: 'สมัครแฟนคลับยังไง', c: '怎么加入粉丝团' }, { s: '工作人员', t: 'สมัครออนไลน์ได้', c: '可以网上加入' }, { s: '你', t: 'ค่าสมาชิกเท่าไหร่', c: '会费多少' }, { s: '工作人员', t: 'ฟรีครับ', c: '免费' }, { s: '你', t: 'มีสิทธิประโยชน์อะไรบ้าง', c: '有什么福利' }, { s: '工作人员', t: 'มีส่วนลดซื้อของ และเข้ากิจกรรม', c: '有购物折扣和参加活动' }, { s: '你', t: 'สมัครเลย', c: '加入' }] },
    { id: 'dlg-off-05', cat: 'offline', title: '选秀投票', scene: '讨论选秀节目投票', turns: [{ s: 'A', t: 'โหวตยังไง', c: '怎么投票' }, { s: 'B', t: 'กดโหวตในแอป', c: '在app里投票' }, { s: 'A', t: 'หมายเลขกี่', c: '几号' }, { s: 'B', t: 'หมายเลขสาม', c: '三号' }, { s: 'A', t: 'ผ่านเข้ารอบไหม', c: '进了吗' }, { s: 'B', t: 'ผ่านแล้ว', c: '进了' }] },
    { id: 'dlg-off-06', cat: 'offline', title: '走散找朋友', scene: '在活动中跟朋友走散了', turns: [{ s: '你', t: 'หาเพื่อนไม่เจอ', c: '找不到朋友' }, { s: '工作人员', t: 'เบอร์โทรเพื่อนไหม', c: '要打电话给朋友吗' }, { s: '你', t: 'ขอโทรศัพท์ยืมหน่อย', c: '借个电话' }, { s: '工作人员', t: 'ได้ครับ ใช้เลย', c: '可以，用吧' }, { s: '你', t: 'ขอบคุณมาก', c: '非常感谢' }] },
    { id: 'dlg-off-07', cat: 'offline', title: '圣地巡礼问路', scene: '在取景地附近问路', turns: [{ s: '你', t: 'ขอถามทางหน่อย', c: '问个路' }, { s: '路人', t: 'ถามได้เลย', c: '问吧' }, { s: '你', t: 'โรงเรียนนี้อยู่ไหน', c: '这个学校在哪' }, { s: '路人', t: 'ตรงไปแล้วเลี้ยวซ้าย', c: '直走然后左转' }, { s: '你', t: 'ไกลไหม', c: '远吗' }, { s: '路人', t: 'ไม่ไกล เดินห้านาที', c: '不远，走五分钟' }, { s: '你', t: 'ขอบคุณค่ะ', c: '谢谢' }] },
    { id: 'dlg-off-08', cat: 'offline', title: '不舒服求助', scene: '在活动中感觉不舒服', turns: [{ s: '你', t: 'รู้สึกไม่สบาย', c: '不舒服' }, { s: '工作人员', t: 'เป็นอะไรไหม', c: '怎么了' }, { s: '你', t: 'เวียนหัว', c: '头晕' }, { s: '工作人员', t: 'มีห้องพยาบาล ไปทางนี้', c: '有医务室，这边走' }, { s: '你', t: 'ขอน้ำหน่อย', c: '请给点水' }, { s: '工作人员', t: 'นี่น้ำ พักก่อนนะ', c: '给你水，先休息' }, { s: '你', t: 'ขอบคุณมาก', c: '非常感谢' }] },
  ]
};